#!/bin/bash
# Session Start Hook
# Runs at the beginning of each Claude Code session
# Purpose: Initialize environment, load project state, prepare workspace

set -e

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
CLAUDE_ENV_FILE="${CLAUDE_ENV_FILE:-}"

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}[ggen] Initializing session...${NC}"

# 1. Set project environment variables
export RUST_BACKTRACE=1
export RUST_LOG=info
export CARGO_TERM_COLOR=always
export NODE_ENV=development

# 2. Load custom environment variables if session file exists
if [ -n "$CLAUDE_ENV_FILE" ] && [ -f "$CLAUDE_ENV_FILE" ]; then
    echo -e "${BLUE}[ggen] Loading session environment...${NC}"
    set +e
    source "$CLAUDE_ENV_FILE"
    set -e
fi

# 3. Verify Rust toolchain
if command -v rustc &> /dev/null; then
    RUSTC_VERSION=$(rustc --version)
    echo -e "${GREEN}[ggen] ✓ $RUSTC_VERSION${NC}"
else
    echo -e "${YELLOW}[ggen] ⚠ Rust toolchain not found${NC}"
    exit 1
fi

# 4. Verify cargo-make installed
if ! command -v cargo-make &> /dev/null; then
    echo -e "${YELLOW}[ggen] Installing cargo-make...${NC}"
    cargo install cargo-make --quiet || true
fi

# 5. Check git status
if cd "$PROJECT_DIR" && git rev-parse --git-dir > /dev/null 2>&1; then
    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    echo -e "${GREEN}[ggen] ✓ Branch: $GIT_BRANCH${NC}"

    # Check for uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        CHANGES=$(git status --short | wc -l)
        echo -e "${YELLOW}[ggen] ⚠ Uncommitted changes: $CHANGES${NC}"
    fi
fi

# 6. Verify .specify/ structure
if [ ! -d "$PROJECT_DIR/.specify" ]; then
    echo -e "${YELLOW}[ggen] ⚠ .specify/ directory not found${NC}"
fi

# 7. Print quick start reminder
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}[ggen] Session Ready${NC}"
echo -e "${BLUE}Quick start commands:${NC}"
echo -e "  ${GREEN}cargo make check${NC}          - Quick compilation check"
echo -e "  ${GREEN}cargo make test-unit${NC}      - Run unit tests"
echo -e "  ${GREEN}cargo make lint${NC}           - Run clippy linter"
echo -e "  ${GREEN}cargo make pre-commit${NC}     - Full validation"
echo -e ""
echo -e "${BLUE}Slash commands:${NC}"
echo -e "  ${GREEN}/optimize${NC}                 - Optimize code performance"
echo -e "  ${GREEN}/test-audit${NC}               - Run test quality audit"
echo -e "  ${GREEN}/bench-compare${NC}            - Compare benchmarks"
echo -e "  ${GREEN}/speckit-check${NC}            - Validate specifications"
echo -e "  ${GREEN}/review-errors${NC}            - Audit error handling"
echo -e ""
echo -e "${BLUE}Agents:${NC}"
echo -e "  ${GREEN}rust-coder${NC}                - Rust implementation"
echo -e "  ${GREEN}test-engineer${NC}             - Test writing"
echo -e "  ${GREEN}reviewer${NC}                  - Code review"
echo -e "  ${GREEN}speckit-architect${NC}         - RDF specifications"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Save environment file for future use
if [ -n "$CLAUDE_ENV_FILE" ]; then
    mkdir -p "$(dirname "$CLAUDE_ENV_FILE")"
    {
        echo "# Generated by session-start.sh"
        echo "export RUST_BACKTRACE=1"
        echo "export RUST_LOG=info"
        echo "export CARGO_TERM_COLOR=always"
        echo "export NODE_ENV=development"
    } > "$CLAUDE_ENV_FILE"
fi

exit 0
