//! Proof test for `cargo-cicd-pack`'s generated static catalog
//! (`src/cargo_cicd_catalog.rs`).
//!
//! GENERATED by `cargo-cicd-pack`. Per-row expected-value assertions below
//! are rendered from the SAME SPARQL query that produced
//! `src/cargo_cicd_catalog.rs` -- NOT hand-transcribed literals. This closes
//! the drift gap the prior version of this proof had: editing
//! `ontology.ttl` (adding/removing/renaming a command) and re-running
//! `ggen sync run` now regenerates BOTH the catalog and this proof's
//! expected values in lockstep, with no human hand-edit step required for
//! the per-row checks. What is NOT tautological: every assertion below
//! calls the real `find_command`/`commands_for_noun`/`is_valid_command`
//! functions against the compiled `CARGO_CICD_COMMANDS` table, so a bug in
//! how the catalog template assembles the table (wrong field order, dropped
//! row, typo in a struct literal) still fails this proof even though the
//! expected values are SPARQL-sourced. The structural invariants further
//! below (uniqueness, sortedness, the doctor-migration shape) are computed
//! independently in Rust, not sourced from the query at all.

#[path = "../src/cargo_cicd_catalog.rs"]
mod cargo_cicd_catalog;

use cargo_cicd_catalog::{
    all_commands_share_return_contract, args_are_consistent, commands_for_noun, distinct_nouns,
    find_command, is_valid_command, parse_args, CARGO_CICD_COMMANDS, CARGO_CICD_ERROR_ENUM,
    CARGO_CICD_ERROR_VARIANTS, CARGO_CICD_RETURN_TYPE,
};

/// Exact row count, sourced from the same SPARQL query as the catalog
/// (`52` rows at generation time) -- not a hand-counted
/// literal, so this assertion never goes stale relative to `ontology.ttl`.
#[test]
fn catalog_row_count_matches_ontology_query() {
    assert_eq!(
        CARGO_CICD_COMMANDS.len(),
        52,
        "catalog row count drifted from the generating SPARQL query"
    );
}

/// Every row the generating SPARQL query returned must be independently
/// retrievable from the compiled catalog via `find_command`, with the exact
/// doc string and source file the query produced. This is the per-row
/// lockstep check: if the catalog template ever drops, duplicates, or
/// mis-assembles a row, this loop fails even though the expected values
/// come from the same query -- it exercises the *generated table*, not the
/// query result a second time.
#[test]
fn every_queried_row_is_present_with_matching_fields() {
    {
        let row = find_command("certification", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "certification", "show"));
        assert_eq!(row.doc, "IEC 61508 / ISO 26262 compliance summary for cargo-cicd certification.", "doc mismatch for certification/show");
        assert_eq!(row.source_file, "src/nouns/certification.rs", "source_file mismatch for certification/show");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for certification/show");
        assert_eq!(row.args, "", "args mismatch for certification/show");
    }
    {
        let row = find_command("claude_context", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "claude_context", "show"));
        assert_eq!(row.doc, "Shows the Claude agent context snapshot for the current repository.", "doc mismatch for claude_context/show");
        assert_eq!(row.source_file, "src/nouns/claude_context.rs", "source_file mismatch for claude_context/show");
        assert_eq!(row.arg_count, 1, "arg_count mismatch for claude_context/show");
        assert_eq!(row.args, "repo:Option<String>", "args mismatch for claude_context/show");
    }
    {
        let row = find_command("doctor", "")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "doctor", ""));
        assert_eq!(row.doc, "DEPRECATED 2026-07-18: superseded by cc:doctor-repo/cc:doctor-evidence/cc:doctor-diff -- source audit found doctor is not actually a bare noun with an empty verb; retained only so previously-generated literal shapes do not silently vanish.", "doc mismatch for doctor/");
        assert_eq!(row.source_file, "", "source_file mismatch for doctor/");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for doctor/");
        assert_eq!(row.args, "", "args mismatch for doctor/");
    }
    {
        let row = find_command("doctor", "diff")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "doctor", "diff"));
        assert_eq!(row.doc, "Diffs current repository health against a previously written baseline.", "doc mismatch for doctor/diff");
        assert_eq!(row.source_file, "src/nouns/doctor.rs", "source_file mismatch for doctor/diff");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for doctor/diff");
        assert_eq!(row.args, "repo:Option<String>;baseline:Option<String>", "args mismatch for doctor/diff");
    }
    {
        let row = find_command("doctor", "evidence")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "doctor", "evidence"));
        assert_eq!(row.doc, "", "doc mismatch for doctor/evidence");
        assert_eq!(row.source_file, "src/nouns/doctor.rs", "source_file mismatch for doctor/evidence");
        assert_eq!(row.arg_count, 1, "arg_count mismatch for doctor/evidence");
        assert_eq!(row.args, "json:bool", "args mismatch for doctor/evidence");
    }
    {
        let row = find_command("doctor", "repo")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "doctor", "repo"));
        assert_eq!(row.doc, "Diagnoses repository health against a recorded baseline and reports evidence drift.", "doc mismatch for doctor/repo");
        assert_eq!(row.source_file, "src/nouns/doctor.rs", "source_file mismatch for doctor/repo");
        assert_eq!(row.arg_count, 5, "arg_count mismatch for doctor/repo");
        assert_eq!(row.args, "repo:Option<String>;json:bool;write_baseline:Option<String>;baseline:Option<String>;diff:bool", "args mismatch for doctor/repo");
    }
    {
        let row = find_command("evidence", "audit")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "evidence", "audit"));
        assert_eq!(row.doc, "", "doc mismatch for evidence/audit");
        assert_eq!(row.source_file, "src/nouns/evidence.rs", "source_file mismatch for evidence/audit");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for evidence/audit");
        assert_eq!(row.args, "", "args mismatch for evidence/audit");
    }
    {
        let row = find_command("evidence", "doctor")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "evidence", "doctor"));
        assert_eq!(row.doc, "Adjudicates and inspects recorded process evidence (XES/OCEL logs).", "doc mismatch for evidence/doctor");
        assert_eq!(row.source_file, "src/nouns/evidence.rs", "source_file mismatch for evidence/doctor");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for evidence/doctor");
        assert_eq!(row.args, "", "args mismatch for evidence/doctor");
    }
    {
        let row = find_command("evidence", "list")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "evidence", "list"));
        assert_eq!(row.doc, "", "doc mismatch for evidence/list");
        assert_eq!(row.source_file, "src/nouns/evidence.rs", "source_file mismatch for evidence/list");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for evidence/list");
        assert_eq!(row.args, "", "args mismatch for evidence/list");
    }
    {
        let row = find_command("evidence", "reset")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "evidence", "reset"));
        assert_eq!(row.doc, "", "doc mismatch for evidence/reset");
        assert_eq!(row.source_file, "src/nouns/evidence.rs", "source_file mismatch for evidence/reset");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for evidence/reset");
        assert_eq!(row.args, "", "args mismatch for evidence/reset");
    }
    {
        let row = find_command("evidence", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "evidence", "show"));
        assert_eq!(row.doc, "", "doc mismatch for evidence/show");
        assert_eq!(row.source_file, "src/nouns/evidence.rs", "source_file mismatch for evidence/show");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for evidence/show");
        assert_eq!(row.args, "", "args mismatch for evidence/show");
    }
    {
        let row = find_command("gate", "repo")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "gate", "repo"));
        assert_eq!(row.doc, "Evaluates repository-level release gate conditions.", "doc mismatch for gate/repo");
        assert_eq!(row.source_file, "src/nouns/gate.rs", "source_file mismatch for gate/repo");
        assert_eq!(row.arg_count, 3, "arg_count mismatch for gate/repo");
        assert_eq!(row.args, "repo:Option<String>;json:bool;sarif:bool", "args mismatch for gate/repo");
    }
    {
        let row = find_command("git", "close")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "close"));
        assert_eq!(row.doc, "Lawful branch-close sequence.", "doc mismatch for git/close");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/close");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/close");
        assert_eq!(row.args, "", "args mismatch for git/close");
    }
    {
        let row = find_command("git", "commit")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "commit"));
        assert_eq!(row.doc, "", "doc mismatch for git/commit");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/commit");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/commit");
        assert_eq!(row.args, "", "args mismatch for git/commit");
    }
    {
        let row = find_command("git", "diff")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "diff"));
        assert_eq!(row.doc, "", "doc mismatch for git/diff");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/diff");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/diff");
        assert_eq!(row.args, "", "args mismatch for git/diff");
    }
    {
        let row = find_command("git", "fetch")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "fetch"));
        assert_eq!(row.doc, "", "doc mismatch for git/fetch");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/fetch");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/fetch");
        assert_eq!(row.args, "", "args mismatch for git/fetch");
    }
    {
        let row = find_command("git", "stage")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "stage"));
        assert_eq!(row.doc, "", "doc mismatch for git/stage");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/stage");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/stage");
        assert_eq!(row.args, "", "args mismatch for git/stage");
    }
    {
        let row = find_command("git", "status")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "git", "status"));
        assert_eq!(row.doc, "", "doc mismatch for git/status");
        assert_eq!(row.source_file, "src/nouns/git.rs", "source_file mismatch for git/status");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for git/status");
        assert_eq!(row.args, "", "args mismatch for git/status");
    }
    {
        let row = find_command("hooks", "install")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "hooks", "install"));
        assert_eq!(row.doc, "Installs git hooks that integrate cargo-cicd with an external CI provider.", "doc mismatch for hooks/install");
        assert_eq!(row.source_file, "src/nouns/hooks.rs", "source_file mismatch for hooks/install");
        assert_eq!(row.arg_count, 3, "arg_count mismatch for hooks/install");
        assert_eq!(row.args, "repo:Option<String>;provider:Option<String>;json:bool", "args mismatch for hooks/install");
    }
    {
        let row = find_command("hooks", "pre-tool-use")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "hooks", "pre-tool-use"));
        assert_eq!(row.doc, "", "doc mismatch for hooks/pre-tool-use");
        assert_eq!(row.source_file, "src/nouns/hooks.rs", "source_file mismatch for hooks/pre-tool-use");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for hooks/pre-tool-use");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for hooks/pre-tool-use");
    }
    {
        let row = find_command("hooks", "uninstall")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "hooks", "uninstall"));
        assert_eq!(row.doc, "", "doc mismatch for hooks/uninstall");
        assert_eq!(row.source_file, "src/nouns/hooks.rs", "source_file mismatch for hooks/uninstall");
        assert_eq!(row.arg_count, 3, "arg_count mismatch for hooks/uninstall");
        assert_eq!(row.args, "repo:Option<String>;provider:Option<String>;json:bool", "args mismatch for hooks/uninstall");
    }
    {
        let row = find_command("ocel", "replay")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "ocel", "replay"));
        assert_eq!(row.doc, "Replays recorded OCEL process-evidence events.", "doc mismatch for ocel/replay");
        assert_eq!(row.source_file, "src/nouns/ocel.rs", "source_file mismatch for ocel/replay");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for ocel/replay");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for ocel/replay");
    }
    {
        let row = find_command("pipeline", "run")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "pipeline", "run"));
        assert_eq!(row.doc, "Runs the workspace's CI/CD pipeline definition.", "doc mismatch for pipeline/run");
        assert_eq!(row.source_file, "src/nouns/pipeline.rs", "source_file mismatch for pipeline/run");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for pipeline/run");
        assert_eq!(row.args, "", "args mismatch for pipeline/run");
    }
    {
        let row = find_command("pipeline", "status")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "pipeline", "status"));
        assert_eq!(row.doc, "", "doc mismatch for pipeline/status");
        assert_eq!(row.source_file, "src/nouns/pipeline.rs", "source_file mismatch for pipeline/status");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for pipeline/status");
        assert_eq!(row.args, "", "args mismatch for pipeline/status");
    }
    {
        let row = find_command("pipeline", "validate")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "pipeline", "validate"));
        assert_eq!(row.doc, "", "doc mismatch for pipeline/validate");
        assert_eq!(row.source_file, "src/nouns/pipeline.rs", "source_file mismatch for pipeline/validate");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for pipeline/validate");
        assert_eq!(row.args, "", "args mismatch for pipeline/validate");
    }
    {
        let row = find_command("publish", "check")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "publish", "check"));
        assert_eq!(row.doc, "", "doc mismatch for publish/check");
        assert_eq!(row.source_file, "src/nouns/publish.rs", "source_file mismatch for publish/check");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for publish/check");
        assert_eq!(row.args, "", "args mismatch for publish/check");
    }
    {
        let row = find_command("publish", "run")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "publish", "run"));
        assert_eq!(row.doc, "Publishes eligible workspace crates to crates.io after verifying release readiness.", "doc mismatch for publish/run");
        assert_eq!(row.source_file, "src/nouns/publish.rs", "source_file mismatch for publish/run");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for publish/run");
        assert_eq!(row.args, "", "args mismatch for publish/run");
    }
    {
        let row = find_command("publish", "validate")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "publish", "validate"));
        assert_eq!(row.doc, "", "doc mismatch for publish/validate");
        assert_eq!(row.source_file, "src/nouns/publish.rs", "source_file mismatch for publish/validate");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for publish/validate");
        assert_eq!(row.args, "", "args mismatch for publish/validate");
    }
    {
        let row = find_command("receipt", "audit")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "receipt", "audit"));
        assert_eq!(row.doc, "", "doc mismatch for receipt/audit");
        assert_eq!(row.source_file, "src/nouns/receipt.rs", "source_file mismatch for receipt/audit");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for receipt/audit");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for receipt/audit");
    }
    {
        let row = find_command("receipt", "verify")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "receipt", "verify"));
        assert_eq!(row.doc, "Verifies a recorded receipt's integrity.", "doc mismatch for receipt/verify");
        assert_eq!(row.source_file, "src/nouns/receipt.rs", "source_file mismatch for receipt/verify");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for receipt/verify");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for receipt/verify");
    }
    {
        let row = find_command("release_gate", "check")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "release_gate", "check"));
        assert_eq!(row.doc, "Checks whether release-gate conditions are currently satisfied.", "doc mismatch for release_gate/check");
        assert_eq!(row.source_file, "src/nouns/release_gate.rs", "source_file mismatch for release_gate/check");
        assert_eq!(row.arg_count, 3, "arg_count mismatch for release_gate/check");
        assert_eq!(row.args, "repo:Option<String>;release_id:Option<String>;json:bool", "args mismatch for release_gate/check");
    }
    {
        let row = find_command("sbom", "generate")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "sbom", "generate"));
        assert_eq!(row.doc, "Generates a Software Bill of Materials (SBOM) via CycloneDX.", "doc mismatch for sbom/generate");
        assert_eq!(row.source_file, "src/nouns/sbom.rs", "source_file mismatch for sbom/generate");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for sbom/generate");
        assert_eq!(row.args, "", "args mismatch for sbom/generate");
    }
    {
        let row = find_command("sbom", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "sbom", "show"));
        assert_eq!(row.doc, "", "doc mismatch for sbom/show");
        assert_eq!(row.source_file, "src/nouns/sbom.rs", "source_file mismatch for sbom/show");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for sbom/show");
        assert_eq!(row.args, "", "args mismatch for sbom/show");
    }
    {
        let row = find_command("standing", "refresh")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "standing", "refresh"));
        assert_eq!(row.doc, "Refreshes generated standing documents from current repository state.", "doc mismatch for standing/refresh");
        assert_eq!(row.source_file, "src/nouns/standing.rs", "source_file mismatch for standing/refresh");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for standing/refresh");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for standing/refresh");
    }
    {
        let row = find_command("standing", "report")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "standing", "report"));
        assert_eq!(row.doc, "", "doc mismatch for standing/report");
        assert_eq!(row.source_file, "src/nouns/standing.rs", "source_file mismatch for standing/report");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for standing/report");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for standing/report");
    }
    {
        let row = find_command("standing", "verify")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "standing", "verify"));
        assert_eq!(row.doc, "", "doc mismatch for standing/verify");
        assert_eq!(row.source_file, "src/nouns/standing.rs", "source_file mismatch for standing/verify");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for standing/verify");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for standing/verify");
    }
    {
        let row = find_command("status", "audit")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "status", "audit"));
        assert_eq!(row.doc, "", "doc mismatch for status/audit");
        assert_eq!(row.source_file, "src/nouns/status.rs", "source_file mismatch for status/audit");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for status/audit");
        assert_eq!(row.args, "", "args mismatch for status/audit");
    }
    {
        let row = find_command("status", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "status", "show"));
        assert_eq!(row.doc, "Workspace status: dirty files, pending tests, trybuild result, publish readiness.", "doc mismatch for status/show");
        assert_eq!(row.source_file, "src/nouns/status.rs", "source_file mismatch for status/show");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for status/show");
        assert_eq!(row.args, "", "args mismatch for status/show");
    }
    {
        let row = find_command("target", "prune")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "target", "prune"));
        assert_eq!(row.doc, "", "doc mismatch for target/prune");
        assert_eq!(row.source_file, "src/nouns/target.rs", "source_file mismatch for target/prune");
        assert_eq!(row.arg_count, 1, "arg_count mismatch for target/prune");
        assert_eq!(row.args, "apply:bool", "args mismatch for target/prune");
    }
    {
        let row = find_command("target", "show")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "target", "show"));
        assert_eq!(row.doc, "Reports target/ directory size.", "doc mismatch for target/show");
        assert_eq!(row.source_file, "src/nouns/target.rs", "source_file mismatch for target/show");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for target/show");
        assert_eq!(row.args, "", "args mismatch for target/show");
    }
    {
        let row = find_command("test", "bench")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "test", "bench"));
        assert_eq!(row.doc, "", "doc mismatch for test/bench");
        assert_eq!(row.source_file, "src/nouns/test.rs", "source_file mismatch for test/bench");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for test/bench");
        assert_eq!(row.args, "", "args mismatch for test/bench");
    }
    {
        let row = find_command("test", "changed")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "test", "changed"));
        assert_eq!(row.doc, "Runs only tests for crates whose source changed since the last green commit.", "doc mismatch for test/changed");
        assert_eq!(row.source_file, "src/nouns/test.rs", "source_file mismatch for test/changed");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for test/changed");
        assert_eq!(row.args, "", "args mismatch for test/changed");
    }
    {
        let row = find_command("test", "run")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "test", "run"));
        assert_eq!(row.doc, "", "doc mismatch for test/run");
        assert_eq!(row.source_file, "src/nouns/test.rs", "source_file mismatch for test/run");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for test/run");
        assert_eq!(row.args, "", "args mismatch for test/run");
    }
    {
        let row = find_command("trace", "profile")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "trace", "profile"));
        assert_eq!(row.doc, "Profiles and reports timing traces for cargo-cicd operations.", "doc mismatch for trace/profile");
        assert_eq!(row.source_file, "src/nouns/trace.rs", "source_file mismatch for trace/profile");
        assert_eq!(row.arg_count, 3, "arg_count mismatch for trace/profile");
        assert_eq!(row.args, "repo:Option<String>;profile:String;json:bool", "args mismatch for trace/profile");
    }
    {
        let row = find_command("trybuild", "changed")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "trybuild", "changed"));
        assert_eq!(row.doc, "Runs trybuild compile-fail/compile-pass fixtures for crates changed since the last green commit.", "doc mismatch for trybuild/changed");
        assert_eq!(row.source_file, "src/nouns/trybuild.rs", "source_file mismatch for trybuild/changed");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for trybuild/changed");
        assert_eq!(row.args, "", "args mismatch for trybuild/changed");
    }
    {
        let row = find_command("trybuild", "review")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "trybuild", "review"));
        assert_eq!(row.doc, "", "doc mismatch for trybuild/review");
        assert_eq!(row.source_file, "src/nouns/trybuild.rs", "source_file mismatch for trybuild/review");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for trybuild/review");
        assert_eq!(row.args, "", "args mismatch for trybuild/review");
    }
    {
        let row = find_command("trybuild", "update")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "trybuild", "update"));
        assert_eq!(row.doc, "", "doc mismatch for trybuild/update");
        assert_eq!(row.source_file, "src/nouns/trybuild.rs", "source_file mismatch for trybuild/update");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for trybuild/update");
        assert_eq!(row.args, "", "args mismatch for trybuild/update");
    }
    {
        let row = find_command("verify", "repo")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "verify", "repo"));
        assert_eq!(row.doc, "Verifies a repository against configured checks, including semver compatibility.", "doc mismatch for verify/repo");
        assert_eq!(row.source_file, "src/nouns/verify.rs", "source_file mismatch for verify/repo");
        assert_eq!(row.arg_count, 2, "arg_count mismatch for verify/repo");
        assert_eq!(row.args, "repo:Option<String>;json:bool", "args mismatch for verify/repo");
    }
    {
        let row = find_command("workspace", "doctor")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "workspace", "doctor"));
        assert_eq!(row.doc, "Diagnoses Cargo.toml, toolchain, git repo, cicd.toml.", "doc mismatch for workspace/doctor");
        assert_eq!(row.source_file, "src/nouns/workspace.rs", "source_file mismatch for workspace/doctor");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for workspace/doctor");
        assert_eq!(row.args, "", "args mismatch for workspace/doctor");
    }
    {
        let row = find_command("workspace", "list")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "workspace", "list"));
        assert_eq!(row.doc, "", "doc mismatch for workspace/list");
        assert_eq!(row.source_file, "src/nouns/workspace.rs", "source_file mismatch for workspace/list");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for workspace/list");
        assert_eq!(row.args, "", "args mismatch for workspace/list");
    }
    {
        let row = find_command("workspace", "sync")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "workspace", "sync"));
        assert_eq!(row.doc, "", "doc mismatch for workspace/sync");
        assert_eq!(row.source_file, "src/nouns/workspace.rs", "source_file mismatch for workspace/sync");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for workspace/sync");
        assert_eq!(row.args, "", "args mismatch for workspace/sync");
    }
    {
        let row = find_command("workspace", "validate")
            .unwrap_or_else(|| panic!("missing row noun={:?} verb={:?}", "workspace", "validate"));
        assert_eq!(row.doc, "", "doc mismatch for workspace/validate");
        assert_eq!(row.source_file, "src/nouns/workspace.rs", "source_file mismatch for workspace/validate");
        assert_eq!(row.arg_count, 0, "arg_count mismatch for workspace/validate");
        assert_eq!(row.args, "", "args mismatch for workspace/validate");
    }
}

/// Round-3 addition: `parse_args` must recover exactly `arg_count` pairs for
/// EVERY row in the catalog, not just a hand-picked sample -- an independent
/// structural check between the two ontology facts (`cc:argCount`,
/// `cc:args`), computed in Rust rather than sourced a second time from
/// SPARQL.
#[test]
fn parsed_arg_count_matches_declared_arg_count_for_every_row() {
    for c in CARGO_CICD_COMMANDS {
        assert_eq!(
            parse_args(c).len() as u8,
            c.arg_count,
            "parse_args() length disagrees with arg_count for {}/{}",
            c.noun,
            c.verb
        );
    }
    assert!(args_are_consistent());
}

/// Adversarial: a command with `arg_count == 0` must parse to an empty
/// argument list, not a spurious one-element list from splitting an empty
/// string.
#[test]
fn zero_arg_command_parses_to_empty_arg_list() {
    let row = find_command("git", "status").expect("git status must exist");
    assert_eq!(row.arg_count, 0);
    assert!(parse_args(row).is_empty());
}

/// Positive: a real multi-argument command (`doctor repo`, 5 args per the
/// 2026-07-18 source audit) parses to exactly 5 named, typed pairs, and the
/// first one is `("repo", "Option<String>")` -- checked against the actual
/// generated data, not a re-invented literal.
#[test]
fn doctor_repo_parses_five_typed_arguments() {
    let row = find_command("doctor", "repo").expect("doctor repo must exist");
    let parsed = parse_args(row);
    assert_eq!(parsed.len(), 5);
    assert_eq!(parsed[0], ("repo", "Option<String>"));
}

/// Structural invariant, computed independently of the query: no duplicate
/// (noun, verb) pair exists in the compiled catalog.
#[test]
fn no_duplicate_noun_verb_pairs() {
    let mut seen: Vec<(&str, &str)> = Vec::new();
    for c in CARGO_CICD_COMMANDS {
        let key = (c.noun, c.verb);
        assert!(
            !seen.contains(&key),
            "duplicate (noun, verb) pair: {:?}",
            key
        );
        seen.push(key);
    }
}

/// Structural invariant: the catalog is generated `ORDER BY ?noun ?verb`,
/// so consecutive rows must be non-decreasing by (noun, verb) -- checked by
/// direct comparison, not by re-sorting and diffing (which would be
/// tautological).
#[test]
fn catalog_is_sorted_by_noun_then_verb() {
    for w in CARGO_CICD_COMMANDS.windows(2) {
        let (a, b) = (w[0], w[1]);
        assert!(
            (a.noun, a.verb) <= (b.noun, b.verb),
            "catalog not sorted: {:?} appears before {:?}",
            a,
            b
        );
    }
}

/// Structural invariant: `distinct_nouns()` (a real function over the real
/// table) returns a sorted, deduplicated noun list with no empty entries.
#[test]
fn distinct_nouns_is_sorted_and_nonempty() {
    let nouns = distinct_nouns();
    assert!(!nouns.is_empty());
    for w in nouns.windows(2) {
        assert!(w[0] < w[1], "distinct_nouns() not strictly sorted: {:?}", w);
    }
    assert!(nouns.iter().all(|n| !n.is_empty()));
}

/// Structural invariant: `commands_for_noun("doctor")` returns at least the
/// three real verbs the 2026-07-18 source audit found (`repo`, `evidence`,
/// `diff`) -- catching any regression back to treating `doctor` as a bare
/// noun.
#[test]
fn doctor_noun_has_real_verbs_not_only_the_deprecated_bare_row() {
    let doctor_verbs: Vec<&str> = commands_for_noun("doctor").map(|c| c.verb).collect();
    assert!(doctor_verbs.contains(&"repo"), "missing doctor repo");
    assert!(doctor_verbs.contains(&"evidence"), "missing doctor evidence");
    assert!(doctor_verbs.contains(&"diff"), "missing doctor diff");
}

/// `is_valid_command` returns `false` for a command that plausibly does not
/// exist -- the negative-path proof this pack lacked before (adversarial:
/// a syntactically-similar but wrong noun/verb pair).
#[test]
fn unknown_command_is_not_valid() {
    assert!(!is_valid_command("status", "delete"));
    assert!(!is_valid_command("nonexistent-noun", "show"));
}

/// `find_command` returns `None`, not a panic or a default value, for an
/// unknown pair.
#[test]
fn find_command_returns_none_for_unknown_pair() {
    assert!(find_command("evidence", "nonexistent-verb").is_none());
}

/// Round 4 (2026-07-19): every command shares one real, source-verified
/// error contract -- `clap_noun_verb::Result<()>` parameterized over
/// `NounVerbError` (`~/clap-noun-verb/src/error.rs`). Exact-count assertion
/// sourced from the same SPARQL query that generated
/// `CARGO_CICD_ERROR_VARIANTS`, not a hand-typed literal.
#[test]
fn error_variant_count_matches_ontology_query() {
    assert_eq!(
        CARGO_CICD_ERROR_VARIANTS.len(),
        10,
        "error variant count drifted from the generating SPARQL query"
    );
}

/// Every queried variant name is independently present in the compiled
/// `CARGO_CICD_ERROR_VARIANTS` slice, in the query's own sorted order --
/// exercises the generated const array, not the query result a second time.
#[test]
fn every_queried_error_variant_is_present_and_sorted() {
    let expected: &[&str] = &[
        "ArgumentError",
        "CommandNotFound",
        "ExecutionError",
        "Generic",
        "InvalidStructure",
        "MiddlewareError",
        "PluginError",
        "TelemetryError",
        "ValidationFailed",
        "VerbNotFound",
    ];
    assert_eq!(CARGO_CICD_ERROR_VARIANTS, expected);
    for w in CARGO_CICD_ERROR_VARIANTS.windows(2) {
        assert!(w[0] < w[1], "error variants not strictly sorted: {:?}", w);
    }
}

/// Adversarial: the error-variant list must not silently include an empty
/// string or a duplicate -- a real check on the generated data, not a
/// re-statement of the count check above.
#[test]
fn no_empty_or_duplicate_error_variants() {
    assert!(CARGO_CICD_ERROR_VARIANTS.iter().all(|v| !v.is_empty()));
    let mut seen: Vec<&str> = Vec::new();
    for v in CARGO_CICD_ERROR_VARIANTS {
        assert!(!seen.contains(v), "duplicate error variant: {}", v);
        seen.push(v);
    }
}

/// Every command in the catalog shares the same documented return contract
/// (`clap_noun_verb::Result<()>` / `NounVerbError`) -- source-verified
/// uniform relation across all 51 live rows (see ontology.ttl Round 4
/// comment for the grep evidence).
#[test]
fn return_contract_is_populated_and_uniform() {
    assert!(all_commands_share_return_contract());
    assert_eq!(CARGO_CICD_RETURN_TYPE, "clap_noun_verb::Result<()>");
    assert_eq!(CARGO_CICD_ERROR_ENUM, "NounVerbError");
}
