//! Skill handlers for GroqCoderHandler — generated by ggen
//! Source: ontology/a2a-groq-agent.ttl
//! DO NOT EDIT — regenerate with: ggen sync

use a2a_rs::domain::{A2AError, Message, Part, Role, Task, TaskState, TaskStatus};
use a2a_rs::port::AsyncMessageHandler;
use async_trait::async_trait;
use ggen_ai::{GenAiClient, LlmClient};
use std::sync::Arc;
use uuid::Uuid;

/// Top-level handler that dispatches to Groq-powered skill implementations.
/// Implements only AsyncMessageHandler; storage is managed by the AgentBuilder framework.
#[derive(Clone)]
pub struct GroqCoderHandler {
    genai_client: Arc<GenAiClient>,
}

impl GroqCoderHandler {
    pub fn with_client(genai_client: GenAiClient) -> Self {
        Self {
            genai_client: Arc::new(genai_client),
        }
    }

    fn extract_text(message: &Message) -> String {
        message
            .parts
            .iter()
            .filter_map(|p| {
                if let Part::Text { text, .. } = p {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join(" ")
    }

    async fn dispatch(&self, input: &str) -> Result<String, A2AError> {
        // NOTE: Skill routing uses prefix matching as a demo simplification.
        // A production system should use structured commands, a router with
        // regex, or an LLM-based intent classifier for robust skill detection.
        let trimmed = input.trim();
        if trimmed.starts_with("generate-code") {
            return self.generate_code(input).await;
        }
        if trimmed.starts_with("explain-code") {
            return self.explain_code(input).await;
        }
        if trimmed.starts_with("review-code") {
            return self.review_code(input).await;
        }
        if trimmed.starts_with("refactor-code") {
            return self.refactor_code(input).await;
        }
        Ok(format!(
            "Unknown skill. Available: generate-code, explain-code, review-code, refactor-code"
        ))
    }

    /// Generate code from a natural language description
    async fn generate_code(&self, input: &str) -> Result<String, A2AError> {
        let system_prompt = "You are a code generator. Given a description, output ONLY the code without explanations. Use best practices and include necessary imports.";
        let prompt = format!("{}\n\nUser request:\n{}", system_prompt, input);

        match self.genai_client.complete(&prompt).await {
            Ok(response) => Ok(response.content),
            Err(e) => Err(A2AError::Internal(format!("Groq call failed: {}", e))),
        }
    }

    /// Explain what a given piece of code does
    async fn explain_code(&self, input: &str) -> Result<String, A2AError> {
        let system_prompt =
            "You are a code explainer. Explain the given code clearly and concisely. \
             Cover what it does, how it works, and any notable patterns.";
        let prompt = format!("{}\n\nUser request:\n{}", system_prompt, input);

        match self.genai_client.complete(&prompt).await {
            Ok(response) => Ok(response.content),
            Err(e) => Err(A2AError::Internal(format!("Groq call failed: {}", e))),
        }
    }

    /// Review code for bugs, style issues, and performance problems
    async fn review_code(&self, input: &str) -> Result<String, A2AError> {
        let system_prompt =
            "You are a code reviewer. Review the given code for bugs, security issues, \
             style violations, and performance problems. Provide specific line references \
             and suggested fixes.";
        let prompt = format!("{}\n\nUser request:\n{}", system_prompt, input);

        match self.genai_client.complete(&prompt).await {
            Ok(response) => Ok(response.content),
            Err(e) => Err(A2AError::Internal(format!("Groq call failed: {}", e))),
        }
    }

    /// Suggest refactored/improved version of given code
    async fn refactor_code(&self, input: &str) -> Result<String, A2AError> {
        let system_prompt =
            "You are a refactoring expert. Given code, suggest an improved version that is \
             cleaner, more maintainable, and follows best practices. Output ONLY the \
             refactored code.";
        let prompt = format!("{}\n\nUser request:\n{}", system_prompt, input);

        match self.genai_client.complete(&prompt).await {
            Ok(response) => Ok(response.content),
            Err(e) => Err(A2AError::Internal(format!("Groq call failed: {}", e))),
        }
    }
}

#[async_trait]
impl AsyncMessageHandler for GroqCoderHandler {
    async fn process_message<'a>(
        &self,
        task_id: &'a str,
        message: &'a Message,
        session_id: Option<&'a str>,
    ) -> Result<Task, A2AError> {
        let context_id = session_id.unwrap_or("default").to_string();
        let input = Self::extract_text(message);
        tracing::info!(task_id = %task_id, "Dispatching message to skill handler");

        let result_text = self.dispatch(&input).await?;

        let response = Message::builder()
            .role(Role::Agent)
            .message_id(Uuid::new_v4().to_string())
            .context_id(context_id.clone())
            .parts(vec![Part::text(result_text)])
            .build();

        Ok(Task::builder()
            .id(task_id.to_string())
            .context_id(context_id)
            .status(TaskStatus {
                state: TaskState::Completed,
                message: Some(response.clone()),
                timestamp: Some(chrono::Utc::now()),
            })
            .history(vec![message.clone(), response])
            .build())
    }
}
