//! `clap-noun-verb-cli` — binary entry point.
//!
//! Auto-discovers every `#[verb]` command registered by
//! `src/clap_noun_verb_routes.rs` (generated by `ggen sync` from
//! `schema/clap-noun-verb-ontology.ttl`) via `clap_noun_verb::run()`'s
//! distributed-slice registry scan. No explicit command wiring needed here.

use std::process;

fn main() {
    match clap_noun_verb_cli::run() {
        Ok(()) => process::exit(0),
        Err(e) => {
            eprintln!("ERROR: {}", e);
            process::exit(1);
        }
    }
}
