//! Chicago-TDD end-to-end proof for `packs/dspy-pack`: real filesystem
//! (`TempDir`), real graph engine, real Tera, the real `ggen_engine::sync`
//! pipeline — no hand-rolled reimplementation of SPARQL/template rendering.
//!
//! Supersedes `scripts/verify_python_framework_packs.py`'s coverage of this
//! pack for the same reason `typer_pack_e2e.rs`/`fastmcp_pack_e2e.rs` do.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::path::{Path, PathBuf};
use std::process::Command;

use ggen_engine::sync::{sync, SyncOptions};
use support::{assert_gate_refuses, assert_idempotent, read, scaffold_pack};

fn packs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packs")
}

#[test]
fn dspy_pack_generates_valid_python_and_is_idempotent() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("dspy-pack"));

    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("first sync");

    let generated = read(&project, "src/dspy_program.py");
    assert!(
        generated.contains("# GENERATED by ggen from dspy-pack/ontology.ttl"),
        "missing generated marker: {generated}"
    );
    assert!(
        generated.contains("class AnswerQuestion(dspy.Signature):"),
        "signature class name must be real, interpolated content: {generated}"
    );
    assert!(
        generated.contains(r#""""Answer a question with a concise response.""""#),
        "{generated}"
    );
    assert!(
        generated.contains(r#"question: str = dspy.InputField(desc="Question to answer.")"#),
        "input field must render with real type/description: {generated}"
    );
    assert!(
        generated.contains(r#"answer: str = dspy.OutputField(desc="Concise answer.")"#),
        "output field must render with real type/description: {generated}"
    );
    assert!(
        generated.contains("program = dspy.Predict(AnswerQuestion)"),
        "module instantiation must reference the real signature class: {generated}"
    );

    let generated_path = project.join("src/dspy_program.py");
    let parse = Command::new("python3")
        .args(["-c", "import ast,sys; ast.parse(open(sys.argv[1]).read())"])
        .arg(&generated_path)
        .output()
        .expect("spawn python3 -c ast.parse");
    assert!(
        parse.status.success(),
        "generated dspy_program.py is not valid Python: {}",
        String::from_utf8_lossy(&parse.stderr)
    );

    assert_idempotent(&project);
}

/// Sabotage: a fully-formed `dspy:Module` whose `dspy:kind` is outside the
/// admitted set (`"Predict"`/`"ChainOfThought"`) must be refused — the same
/// negative falsifier the superseded script exercised
/// (`dspy_unadmitted_module_kind`, which mutated the real `answer-program`
/// individual to `dspy:kind "AmbientActuator"`), now proven against the real
/// engine. Every OTHER required property is present so the gate's
/// "outside the admitted module set" branch fires specifically, not a
/// missing-property branch.
#[test]
fn dspy_pack_gate_refuses_module_with_unadmitted_kind() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("dspy-pack"));

    assert_gate_refuses(
        &project,
        "@prefix dspy: <http://seanchatmangpt.github.io/packs/dspy#> .\n\
         @prefix dcterms: <http://purl.org/dc/terms/> .\n\
         dspy:sabotage-signature a dspy:Signature ;\n\
         \u{20}   dcterms:title \"Sabotage\" ;\n\
         \u{20}   dcterms:description \"Sabotage signature.\" ;\n\
         \u{20}   dspy:className \"Sabotage\" ;\n\
         \u{20}   dspy:hasInput dspy:sabotage-input ;\n\
         \u{20}   dspy:hasOutput dspy:sabotage-output .\n\
         dspy:sabotage-input a dspy:InputField ;\n\
         \u{20}   dcterms:description \"in\" ; dspy:name \"x\" ; dspy:pythonType \"str\" .\n\
         dspy:sabotage-output a dspy:OutputField ;\n\
         \u{20}   dcterms:description \"out\" ; dspy:name \"y\" ; dspy:pythonType \"str\" .\n\
         dspy:sabotage-module a dspy:Module ;\n\
         \u{20}   dcterms:description \"Sabotage module.\" ;\n\
         \u{20}   dspy:name \"sabotage\" ;\n\
         \u{20}   dspy:kind \"AmbientActuator\" ;\n\
         \u{20}   dspy:signature dspy:sabotage-signature .\n",
        "010_admission",
    );
}
