//! Chicago-TDD end-to-end proof for `packs/fastmcp-pack`: real filesystem
//! (`TempDir`), real graph engine, real Tera, the real `ggen_engine::sync`
//! pipeline — no hand-rolled reimplementation of SPARQL/template rendering.
//!
//! Supersedes `scripts/verify_python_framework_packs.py`'s coverage of this
//! pack for the same reason `typer_pack_e2e.rs` does: that script's own
//! rdflib+Jinja2 pipeline only proves its own simulation renders correctly,
//! never that the real ggen engine does.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::path::{Path, PathBuf};
use std::process::Command;

use ggen_engine::sync::{sync, SyncOptions};
use support::{assert_gate_refuses, assert_idempotent, read, scaffold_pack};

fn packs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packs")
}

#[test]
fn fastmcp_pack_generates_valid_python_and_is_idempotent() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("fastmcp-pack"));

    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("first sync");

    let generated = read(&project, "src/fastmcp_server.py");
    assert!(
        generated.contains("# GENERATED by ggen from fastmcp-pack/ontology.ttl"),
        "missing generated marker: {generated}"
    );
    assert!(
        generated.contains(r#"mcp = FastMCP("ggen-fastmcp")"#),
        "server name must be real, interpolated content: {generated}"
    );
    assert!(
        generated.contains(
            r#"@mcp.tool(name="greet", description="Return a deterministic greeting without external actuation.")"#
        ),
        "{generated}"
    );
    assert!(
        generated.contains("def greet(name: str) -> str:"),
        "tool function derived from the ontology's fmcp:function: {generated}"
    );
    assert!(
        generated.contains("name: Subject to greet."),
        "argument description must be real content: {generated}"
    );
    assert!(
        generated.contains(r#"return "Hello, {name}!".format(name=name)"#),
        "return template must render with the real format-string idiom: {generated}"
    );
    assert!(
        generated.contains("mcp.run()"),
        "server entrypoint must be present: {generated}"
    );

    let generated_path = project.join("src/fastmcp_server.py");
    let parse = Command::new("python3")
        .args(["-c", "import ast,sys; ast.parse(open(sys.argv[1]).read())"])
        .arg(&generated_path)
        .output()
        .expect("spawn python3 -c ast.parse");
    assert!(
        parse.status.success(),
        "generated fastmcp_server.py is not valid Python: {}",
        String::from_utf8_lossy(&parse.stderr)
    );

    assert_idempotent(&project);
}

/// Sabotage: a `fmcp:Tool` missing `fmcp:argument` (and every other required
/// property) must be refused — the same negative falsifier class the
/// superseded script exercised (`fastmcp_missing_argument`), now proven
/// against the real engine.
#[test]
fn fastmcp_pack_gate_refuses_tool_missing_required_properties() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("fastmcp-pack"));

    assert_gate_refuses(
        &project,
        "@prefix fmcp: <http://seanchatmangpt.github.io/packs/fastmcp#> .\n\
         fmcp:SabotageTool a fmcp:Tool .\n",
        "010_admission",
    );
}
