//! Chicago-TDD end-to-end proof for `packs/github-actions-combinatorial-pack`:
//! real filesystem, real RDF/SPARQL gate execution, real Tera, and the real
//! `ggen_engine::sync` pipeline. The pack preserves an open GitHub cloud /
//! Actions / Marketplace capability graph while projecting only a bounded
//! exact-head workflow, machine-readable Marketplace lock, and cloud doctrine.
//! No test here claims the hosted workflow ran; runtime standing belongs to
//! an exact published commit's Actions run receipt.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::path::{Path, PathBuf};

use ggen_engine::sync::{sync, SyncOptions};
use support::{assert_gate_refuses, assert_idempotent, read, scaffold_pack};

fn packs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packs")
}

#[test]
fn github_actions_pack_generates_bounded_pinned_exact_head_products() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));

    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("first sync");

    let workflow = read(&project, ".github/workflows/crown-ci.yml");
    assert!(
        workflow.contains("# GENERATED by ggen from github-actions-combinatorial-pack/ontology.ttl"),
        "generated authority marker missing: {workflow}"
    );
    for event in ["push:", "pull_request:", "workflow_dispatch:"] {
        assert!(workflow.contains(event), "missing admitted event {event}: {workflow}");
    }
    assert!(
        workflow.contains("contents: read"),
        "least-privilege contents grant missing: {workflow}"
    );
    assert!(
        workflow.contains("cancel-in-progress: true"),
        "WIP cancellation missing: {workflow}"
    );
    assert!(
        workflow.contains("crown-ci-${{ github.workflow }}-${{ github.ref }}"),
        "concurrency identity must remain a GitHub expression after Tera rendering: {workflow}"
    );

    for uses in [
        "actions/checkout@11d5960a326750d5838078e36cf38b85af677262",
        "actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830",
        "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02",
    ] {
        assert!(
            workflow.contains(uses),
            "action is not immutable-pinned: {uses}\n{workflow}"
        );
    }
    assert!(
        !workflow.contains("actions/checkout@v4")
            && !workflow.contains("actions/cache@v4")
            && !workflow.contains("actions/upload-artifact@v4"),
        "floating Marketplace refs must never reach the projection: {workflow}"
    );
    assert!(
        workflow.contains(
            "cargo test -p ggen-engine --test github_actions_combinatorial_pack_e2e"
        ),
        "selected repository-native verifier missing: {workflow}"
    );
    assert!(
        workflow.contains("\"head_sha\": os.environ.get(\"GITHUB_SHA\", \"\")"),
        "receipt must bind exact workflow head SHA: {workflow}"
    );
    assert!(
        workflow.contains("if-no-files-found: error"),
        "receipt upload may not silently disappear: {workflow}"
    );

    let marketplace_lock = read(&project, ".github/ggen/marketplace-lock.yml");
    assert!(
        marketplace_lock.contains("schema: ggen.github-actions.marketplace-lock/v1")
            && marketplace_lock.contains("open_world_candidates: true"),
        "Marketplace lock policy missing: {marketplace_lock}"
    );
    for expected in [
        "source_repository: \"actions/checkout\"",
        "source_repository: \"actions/cache\"",
        "source_repository: \"actions/upload-artifact\"",
        "capability: \"source-checkout\"",
        "capability: \"dependency-cache\"",
        "capability: \"artifact-upload\"",
    ] {
        assert!(
            marketplace_lock.contains(expected),
            "Marketplace lock missing {expected}: {marketplace_lock}"
        );
    }

    let doctrine = read(&project, "docs/github-actions/cloud-operating-doctrine.md");
    for expected in [
        "`github-connector`",
        "`github-actions`",
        "`artifacts`",
        "`local-verification-capsule`",
        "`cli-fallback`",
        "`gh-fix-ci`",
        "`yeet`",
        "`image_version`",
        "false `BLOCKED`",
    ] {
        assert!(
            doctrine.contains(expected),
            "cloud doctrine missing {expected}: {doctrine}"
        );
    }

    assert_idempotent(&project);
}

#[test]
fn github_actions_pack_refuses_unpinned_marketplace_action() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:bad-action a ci:MarketplaceAction ;\n\
           ci:usesPath \"octo/action\" ; ci:sha \"v4\" ; ci:role \"verify\" ;\n\
           ci:trustedPublisher true ; ci:networkRequired false ; ci:sideEffect \"read\" .\n",
        "020_supply_chain",
    );
}

#[test]
fn github_actions_pack_refuses_permission_dependency_gap() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:oidc-cap a ci:ActionCapability ; ci:key \"oidc-test\" .\n\
         ci:oidc-action a ci:MarketplaceAction ; ci:usesPath \"octo/oidc\" ;\n\
           ci:sourceRepository \"octo/oidc\" ; ci:publisher \"octo\" ;\n\
           ci:sha \"0123456789abcdef0123456789abcdef01234567\" ; ci:role \"deploy\" ;\n\
           ci:providesCapability ci:oidc-cap ; ci:trustedPublisher true ;\n\
           ci:provenanceChecked true ; ci:networkRequired true ; ci:sideEffect \"read\" ;\n\
           ci:requiresScope \"id-token\" .\n\
         ci:bad-job a ci:JobPlan ; ci:id \"bad\" ; ci:runner \"ubuntu-latest\" ;\n\
           ci:timeoutMinutes 10 ; ci:networkPolicy \"egress-allow\" ; ci:emitsReceipt true ;\n\
           ci:verifyCommand \"true\" ; ci:checkoutAction ci:oidc-action ; ci:cacheAction ci:oidc-action ;\n\
           ci:uploadAction ci:oidc-action ; ci:usesAction ci:oidc-action .\n\
         ci:bad-plan a ci:WorkflowPlan ; ci:name \"bad\" ; ci:concurrencyGroup \"bad\" ;\n\
           ci:hasEvent ci:selected-push ; ci:hasPermission ci:contents-read ; ci:defaultJob ci:bad-job ;\n\
           ci:exactHeadRequired true ; ci:receiptRequired true .\n",
        "020_supply_chain",
    );
}

#[test]
fn github_actions_pack_refuses_unreceipted_consequence() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:write-cap a ci:ActionCapability ; ci:key \"write-test\" .\n\
         ci:write-action a ci:MarketplaceAction ; ci:usesPath \"octo/write\" ;\n\
           ci:sourceRepository \"octo/write\" ; ci:publisher \"octo\" ;\n\
           ci:sha \"0123456789abcdef0123456789abcdef01234567\" ; ci:role \"write\" ;\n\
           ci:providesCapability ci:write-cap ; ci:trustedPublisher true ;\n\
           ci:provenanceChecked true ; ci:networkRequired false ;\n\
           ci:sideEffect \"repository-write\" .\n\
         ci:unreceipted-job a ci:JobPlan ; ci:id \"bad\" ; ci:runner \"ubuntu-latest\" ;\n\
           ci:timeoutMinutes 10 ; ci:networkPolicy \"deny\" ; ci:emitsReceipt false ;\n\
           ci:verifyCommand \"true\" ; ci:checkoutAction ci:write-action ; ci:cacheAction ci:write-action ;\n\
           ci:uploadAction ci:write-action ; ci:usesAction ci:write-action .\n",
        "030_authority_receipt",
    );
}

#[test]
fn github_actions_pack_refuses_false_blocker_while_route_remains() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:false-blocked a ci:Task ; ci:standing ci:Blocked ; ci:hasRoute ci:still-open .\n\
         ci:still-open a ci:RouteAttempt ; ci:route ci:connector-native ;\n\
           ci:routeState ci:RouteAvailable .\n",
        "040_topology",
    );
}

#[test]
fn github_actions_pack_refuses_actions_token_cross_repo_authority_conflation() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:private-dependency a ci:CrossRepoDependency ;\n\
           ci:consumerRepo \"seanchatmangpt/autofde\" ;\n\
           ci:dependencyRepo \"seanchatmangpt/gymact\" ;\n\
           ci:authorizedBy ci:actions-github-token-principal .\n",
        "040_topology",
    );
}
