//! Chicago-TDD end-to-end proof for `packs/github-actions-combinatorial-pack`:
//! real filesystem, real RDF/SPARQL gate execution, real Tera, and the real
//! `ggen_engine::sync` pipeline. The pack preserves an open GitHub Actions /
//! Marketplace capability graph while projecting only one bounded admitted
//! exact-head workflow. No test here claims the hosted workflow ran; that
//! standing belongs to an exact published commit's Actions run receipt.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::path::{Path, PathBuf};

use ggen_engine::sync::{sync, SyncOptions};
use support::{assert_gate_refuses, assert_idempotent, read, scaffold_pack};

fn packs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packs")
}

#[test]
fn github_actions_pack_generates_bounded_pinned_exact_head_workflow() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));

    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("first sync");

    let workflow = read(&project, ".github/workflows/crown-ci.yml");
    assert!(
        workflow.contains("# GENERATED by ggen from github-actions-combinatorial-pack/ontology.ttl"),
        "generated authority marker missing: {workflow}"
    );
    for event in ["push:", "pull_request:", "workflow_dispatch:"] {
        assert!(workflow.contains(event), "missing admitted event {event}: {workflow}");
    }
    assert!(workflow.contains("contents: read"), "least-privilege contents grant missing: {workflow}");
    assert!(workflow.contains("cancel-in-progress: true"), "WIP cancellation missing: {workflow}");
    assert!(
        workflow.contains("crown-ci-${{ github.workflow }}-${{ github.ref }}"),
        "concurrency identity must remain a GitHub expression after Tera rendering: {workflow}"
    );

    for uses in [
        "actions/checkout@11d5960a326750d5838078e36cf38b85af677262",
        "actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830",
        "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02",
    ] {
        assert!(workflow.contains(uses), "action is not immutable-pinned: {uses}\n{workflow}");
    }
    assert!(
        !workflow.contains("actions/checkout@v4")
            && !workflow.contains("actions/cache@v4")
            && !workflow.contains("actions/upload-artifact@v4"),
        "floating Marketplace refs must never reach the projection: {workflow}"
    );
    assert!(
        workflow.contains("cargo test -p ggen-engine --test github_actions_combinatorial_pack_e2e"),
        "selected repository-native verifier missing: {workflow}"
    );
    assert!(
        workflow.contains("\"head_sha\": os.environ.get(\"GITHUB_SHA\", \"\")"),
        "receipt must bind exact workflow head SHA: {workflow}"
    );
    assert!(workflow.contains("if-no-files-found: error"), "receipt upload may not silently disappear: {workflow}");

    assert_idempotent(&project);
}

#[test]
fn github_actions_pack_refuses_unpinned_marketplace_action() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:bad-action a ci:MarketplaceAction ;\n\
           ci:usesPath \"octo/action\" ; ci:sha \"v4\" ; ci:role \"verify\" ;\n\
           ci:trustedPublisher true ; ci:networkRequired false ; ci:sideEffect \"read\" .\n",
        "020_supply_chain",
    );
}

#[test]
fn github_actions_pack_refuses_permission_dependency_gap() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:oidc-action a ci:MarketplaceAction ; ci:usesPath \"octo/oidc\" ;\n\
           ci:sha \"0123456789abcdef0123456789abcdef01234567\" ; ci:role \"deploy\" ;\n\
           ci:trustedPublisher true ; ci:networkRequired true ; ci:sideEffect \"read\" ;\n\
           ci:requiresScope \"id-token\" .\n\
         ci:bad-job a ci:JobPlan ; ci:id \"bad\" ; ci:runner \"ubuntu-latest\" ;\n\
           ci:timeoutMinutes 10 ; ci:networkPolicy \"egress-allow\" ; ci:emitsReceipt true ;\n\
           ci:verifyCommand \"true\" ; ci:checkoutAction ci:oidc-action ; ci:cacheAction ci:oidc-action ;\n\
           ci:uploadAction ci:oidc-action ; ci:usesAction ci:oidc-action .\n\
         ci:bad-plan a ci:WorkflowPlan ; ci:name \"bad\" ; ci:concurrencyGroup \"bad\" ;\n\
           ci:hasEvent ci:selected-push ; ci:hasPermission ci:contents-read ; ci:defaultJob ci:bad-job ;\n\
           ci:exactHeadRequired true ; ci:receiptRequired true .\n",
        "020_supply_chain",
    );
}

#[test]
fn github_actions_pack_refuses_unreceipted_consequence() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("github-actions-combinatorial-pack"));
    assert_gate_refuses(
        &project,
        "@prefix ci: <http://seanchatmangpt.github.io/packs/github-actions-ci#> .\n\
         ci:write-action a ci:MarketplaceAction ; ci:usesPath \"octo/write\" ;\n\
           ci:sha \"0123456789abcdef0123456789abcdef01234567\" ; ci:role \"write\" ;\n\
           ci:trustedPublisher true ; ci:networkRequired false ; ci:sideEffect \"repository-write\" .\n\
         ci:unreceipted-job a ci:JobPlan ; ci:id \"bad\" ; ci:runner \"ubuntu-latest\" ;\n\
           ci:timeoutMinutes 10 ; ci:networkPolicy \"deny\" ; ci:emitsReceipt false ;\n\
           ci:verifyCommand \"true\" ; ci:checkoutAction ci:write-action ; ci:cacheAction ci:write-action ;\n\
           ci:uploadAction ci:write-action ; ci:usesAction ci:write-action .\n",
        "030_authority_receipt",
    );
}
