//! T10 — portable receipt envelope witnesses (RFC-GPACK-001 §54/§55/§56/§57).
//!
//! Chicago-TDD: real filesystem, real oxigraph, real `sync()`, no mocks.
//! Three RFC-mandated witnesses:
//!
//! 1. happy-path sync → envelope parses AND its §54 field set schema-checks
//!    (presence + exact identity strings, not merely JSON-parseability);
//! 2. gate-refused sync → the envelope exists AND reports the typed refusal
//!    with standing `REFUSED:GATE_VIOLATION` — the §57 falsifier: a receipt
//!    existing is not standing, it must REPORT the refusal;
//! 3. `subject.pack_digest` equals an INDEPENDENT in-test implementation of
//!    the §38 canonical pack digest for the same pack (cross-field identity
//!    witness: the test computes both), and is NOT the legacy BLAKE3 hash
//!    (§56: the formats are not byte-equivalent).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use ggen_engine::portable_receipt::{
    PORTABLE_RECEIPT_REL_PATH, PORTABLE_RECEIPT_SCHEMA, PORTABLE_RECEIPT_SPEC,
};
use ggen_engine::sync::{sync, SyncOptions, SyncReceipt, RECEIPT_REL_PATH};
use sha2::Digest;
use tempfile::TempDir;

const PACK_NAME: &str = "widget";
const PACK_VERSION: &str = "1.0.0";

/// Scratch layout:
///
/// ```text
/// <dir>/widget-pack/       — the pack (pack.toml, ontology.ttl, template)
/// <dir>/project/           — the consumer (ggen.toml → ../widget-pack)
/// ```
struct Fixture {
    _dir: TempDir,
    project: PathBuf,
    pack: PathBuf,
}

fn write_fixture(violating_pack_gate: bool, passing_law_gate: bool) -> Fixture {
    let dir = TempDir::new().expect("tempdir");
    let pack = dir.path().join("widget-pack");
    let project = dir.path().join("project");

    std::fs::create_dir_all(pack.join("templates")).expect("pack templates dir");
    std::fs::write(
        pack.join("pack.toml"),
        format!(
            "[pack]\nname = \"{PACK_NAME}-canonical\"\nversion = \"{PACK_VERSION}\"\n\
                 description = \"T10 portable envelope fixture pack\"\n"
        ),
    )
    .expect("write pack.toml");
    std::fs::write(
        pack.join("ontology.ttl"),
        "@prefix ex: <http://example.com/t10#> .\nex:Widget a ex:Class .\n",
    )
    .expect("write ontology.ttl");
    std::fs::write(
        pack.join("templates/widget.rs.tmpl"),
        "---\nto: src/widget.rs\n---\n// generated by the T10 fixture pack\n",
    )
    .expect("write template");

    if violating_pack_gate {
        std::fs::create_dir_all(pack.join("gates")).expect("pack gates dir");
        // SELECT returning >= 1 row over the union graph => violation
        // (RFC §14: Violation = RowCount > 0).
        std::fs::write(
            pack.join("gates/010_refuse.rq"),
            "SELECT ?s WHERE { ?s ?p ?o }",
        )
        .expect("write violating gate");
    }

    std::fs::create_dir_all(project.join("templates")).expect("project templates dir");
    std::fs::write(project.join("ontology.ttl"), "").expect("write project ontology");
    let mut ggen_toml = format!(
        "[project]\nname = \"t10-fixture\"\n\n[ontology]\nsource = \"ontology.ttl\"\n\n\
         [templates]\ndir = \"templates\"\n\n[packs.{PACK_NAME}]\npath = \"../widget-pack\"\n"
    );
    if passing_law_gate {
        std::fs::write(project.join("law-gate.rq"), "ASK { FILTER(false) }")
            .expect("write passing law gate");
        ggen_toml.push_str("\n[law]\ngates = [\"law-gate.rq\"]\n");
    }
    std::fs::write(project.join("ggen.toml"), ggen_toml).expect("write ggen.toml");

    Fixture {
        _dir: dir,
        project,
        pack,
    }
}

fn envelope_path(project: &Path) -> PathBuf {
    project.join(PORTABLE_RECEIPT_REL_PATH)
}

fn read_envelope(project: &Path) -> serde_json::Value {
    serde_json::from_str(
        &std::fs::read_to_string(envelope_path(project)).expect("read portable envelope"),
    )
    .expect("envelope parses as JSON")
}

/// Independent RFC §38 reference implementation (walks the pack root, skips
/// `.git`, sorts by path bytes, frames each entry u64be-length-prefixed
/// under the `ggen-pack-v1\0` domain separator). Deliberately NOT calling
/// `pack::pack_digest_sha256` — the witness only means something if the
/// test computes its own value.
fn independent_rfc38_digest(pack_root: &Path) -> String {
    fn walk(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
        let mut entries: Vec<std::fs::DirEntry> = std::fs::read_dir(dir)
            .expect("read_dir")
            .map(|e| e.expect("entry"))
            .collect();
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries {
            let path = entry.path();
            if path.is_dir() {
                if path.file_name().and_then(|n| n.to_str()) == Some(".git") {
                    continue;
                }
                walk(&path, root, out);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .expect("relative")
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy().into_owned())
                    .collect::<Vec<_>>()
                    .join("/");
                out.push((rel, path));
            }
        }
    }
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    walk(pack_root, pack_root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut hasher = sha2::Sha256::new();
    hasher.update(b"ggen-pack-v1\0");
    for (rel, path) in &entries {
        let bytes = std::fs::read(path).expect("read pack file");
        hasher.update((rel.len() as u64).to_be_bytes());
        hasher.update(rel.as_bytes());
        hasher.update((bytes.len() as u64).to_be_bytes());
        hasher.update(&bytes);
    }
    hex::encode(hasher.finalize())
}

/// Witness 1 — happy-path sync: the envelope parses as JSON and its full
/// §54 field set is present with the exact §55 identity strings, correct
/// standing, real consequence digests, and UNKNOWN replay. The legacy
/// BLAKE3 chain receipt continues to exist unchanged (§56).
#[test]
fn happy_path_sync_emits_complete_portable_envelope() {
    let fx = write_fixture(false, true);
    let report = sync(
        &fx.project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("happy-path sync");

    let env = read_envelope(&fx.project);

    // Identity strings (§55).
    assert_eq!(env["schema"].as_str(), Some(PORTABLE_RECEIPT_SCHEMA));
    assert_eq!(env["spec"].as_str(), Some(PORTABLE_RECEIPT_SPEC));

    // Engine identity (§54).
    assert_eq!(env["engine"]["name"].as_str(), Some("ggen"));
    assert_eq!(
        env["engine"]["version"].as_str(),
        Some(env!("CARGO_PKG_VERSION"))
    );

    // Subject identity (§54): the resolved pack's resolution name + version,
    // pack_digest carrying the sha256: prefix and 64 hex chars.
    assert_eq!(env["subject"]["pack"].as_str(), Some(PACK_NAME));
    assert_eq!(env["subject"]["version"].as_str(), Some(PACK_VERSION));
    let pack_digest = env["subject"]["pack_digest"]
        .as_str()
        .expect("pack_digest str");
    let digest_hex = pack_digest
        .strip_prefix("sha256:")
        .expect("pack_digest is sha256:-prefixed");
    assert_eq!(digest_hex.len(), 64, "sha256 hex: {pack_digest}");
    assert!(digest_hex.chars().all(|c| c.is_ascii_hexdigit()));

    // Dependency closure (§54): present, and honestly empty — Rust packs
    // have no declared pack-to-pack dependency surface yet.
    assert!(env["dependencies"].is_array());
    assert_eq!(env["dependencies"].as_array().expect("array").len(), 0);

    // Graph identity (§54): the same post-Enrich state hash the legacy
    // receipt chains over.
    assert_eq!(
        env["graph"]["canonical_digest"].as_str(),
        Some(report.graph_hash_hex.as_str())
    );

    // Admission (§14/§15): the law gate was attempted (attempt observed),
    // no refusals.
    assert_eq!(
        env["admission"]["gates_attempted"]
            .as_array()
            .expect("gates_attempted array"),
        &vec![serde_json::Value::String("law-gate.rq".to_string())]
    );
    assert_eq!(
        env["admission"]["refusals"]
            .as_array()
            .expect("refusals array")
            .len(),
        0
    );

    // Consequences (§54): exactly the landed write, bound by the real
    // SHA-256 of the bytes on disk.
    let consequences = env["consequences"].as_array().expect("consequences array");
    assert_eq!(consequences.len(), 1, "consequences: {consequences:?}");
    assert_eq!(consequences[0]["target"].as_str(), Some("src/widget.rs"));
    assert_eq!(consequences[0]["operation"].as_str(), Some("MANAGED_WRITE"));
    let on_disk = std::fs::read(fx.project.join("src/widget.rs")).expect("widget on disk");
    let expected_sha = hex::encode(sha2::Sha256::digest(&on_disk));
    assert_eq!(
        consequences[0]["sha256"].as_str(),
        Some(expected_sha.as_str())
    );

    // Replay relation (§54) + standing (§82): never executed by this
    // engine => UNKNOWN, honestly; the completed run => ALIVE.
    assert_eq!(env["replay"]["status"].as_str(), Some("UNKNOWN"));
    assert_eq!(env["standing"].as_str(), Some("ALIVE"));

    // §56 witness: the legacy BLAKE3 chain receipt still exists, still
    // parses, and is a DIFFERENT artifact from the envelope.
    let legacy: SyncReceipt = serde_json::from_str(
        &std::fs::read_to_string(fx.project.join(RECEIPT_REL_PATH)).expect("legacy receipt"),
    )
    .expect("legacy receipt parses");
    assert!(legacy.record.signature_hex.is_some());
}

/// Witness 2 — the §57 falsifier: a gate-refused sync produces an envelope
/// that exists AND reports the typed refusal with standing
/// `REFUSED:GATE_VIOLATION`, while nothing was written (refusal precedes
/// projection) and the legacy receipt was not chained (existing behavior).
#[test]
fn gate_refused_sync_emits_envelope_reporting_typed_refusal() {
    let fx = write_fixture(true, true);

    let err = sync(
        &fx.project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect_err("violating pack gate must refuse the sync");
    let msg = err.to_string();
    assert!(msg.contains("FM-PACK-013"), "typed refusal expected: {msg}");

    let env = read_envelope(&fx.project);

    // §57: the envelope REPORTS standing — refused, with the typed code.
    assert_eq!(env["standing"].as_str(), Some("REFUSED:GATE_VIOLATION"));
    assert_eq!(
        env["admission"]["refusals"]
            .as_array()
            .expect("refusals array"),
        &vec![serde_json::Value::String(
            "REFUSED:GATE_VIOLATION".to_string()
        )]
    );

    // Both gates were actually attempted, in order: the passing law gate,
    // then the refusing pack gate (attempt observed, §15).
    let attempted = env["admission"]["gates_attempted"]
        .as_array()
        .expect("gates_attempted array");
    assert_eq!(attempted.len(), 2, "attempted: {attempted:?}");
    assert_eq!(attempted[0].as_str(), Some("law-gate.rq"));
    let last = attempted[1].as_str().expect("gate identity str");
    assert!(
        last.ends_with("010_refuse.rq"),
        "pack gate identity: {last}"
    );

    // The subject is still identified even though the run was refused.
    assert_eq!(env["subject"]["pack"].as_str(), Some(PACK_NAME));

    // Refusal precedes every write: zero consequences, and the target the
    // pack template would have produced is absent.
    assert_eq!(
        env["consequences"]
            .as_array()
            .expect("consequences array")
            .len(),
        0
    );
    assert!(!fx.project.join("src/widget.rs").exists());

    // Legacy behavior preserved: no BLAKE3 chain receipt either (refusal
    // happens before Stage 5, exactly as before this change).
    assert!(!fx.project.join(RECEIPT_REL_PATH).exists());
}

/// Witness 3 — cross-field identity: the envelope's `subject.pack_digest`
/// equals an independent in-test computation of the §38 digest for the same
/// pack, and is NOT the legacy BLAKE3 content hash (§56: not byte-equivalent).
#[test]
fn envelope_pack_digest_matches_independent_rfc38_computation() {
    let fx = write_fixture(false, false);
    sync(
        &fx.project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("happy-path sync");

    let env = read_envelope(&fx.project);
    let pack_digest = env["subject"]["pack_digest"].as_str().expect("pack_digest");

    assert_eq!(
        pack_digest,
        format!("sha256:{}", independent_rfc38_digest(&fx.pack)),
        "envelope pack_digest must equal the independent §38 computation"
    );

    // §56: the portable digest is not the legacy BLAKE3 pack hash.
    let legacy: SyncReceipt = serde_json::from_str(
        &std::fs::read_to_string(fx.project.join(RECEIPT_REL_PATH)).expect("legacy receipt"),
    )
    .expect("legacy receipt parses");
    let blake3_hex = legacy
        .payload
        .packs
        .get(PACK_NAME)
        .expect("legacy pack hash");
    assert_ne!(
        pack_digest.strip_prefix("sha256:").expect("prefix"),
        blake3_hex,
        "portable SHA-256 identity must not collapse into the BLAKE3 chain hash"
    );
}

/// Companion witness: a LAW-gate refusal on a packless project emits the
/// envelope with standing `REFUSED:GATE_VIOLATION` and an all-UNKNOWN subject
/// (§54: present, never invented).
#[test]
fn law_gate_refusal_on_packless_project_emits_unknown_subject_refusal_envelope() {
    let dir = TempDir::new().expect("tempdir");
    let project = dir.path().join("project");
    std::fs::create_dir_all(project.join("templates")).expect("templates dir");
    std::fs::write(
        project.join("ontology.ttl"),
        "@prefix ex: <http://example.com/t10#> .\nex:A a ex:B .\n",
    )
    .expect("ontology");
    std::fs::write(project.join("law-gate.rq"), "SELECT ?s WHERE { ?s ?p ?o }")
        .expect("violating law gate");
    std::fs::write(
        project.join("ggen.toml"),
        "[project]\nname = \"t10-packless\"\n\n[ontology]\nsource = \"ontology.ttl\"\n\n\
         [templates]\ndir = \"templates\"\n\n[law]\ngates = [\"law-gate.rq\"]\n",
    )
    .expect("ggen.toml");

    let err = sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect_err("violating law gate must refuse");
    assert!(err.to_string().contains("FM-LAW-013"), "{err}");

    let env = read_envelope(&project);
    assert_eq!(env["standing"].as_str(), Some("REFUSED:GATE_VIOLATION"));
    assert_eq!(env["subject"]["pack"].as_str(), Some("UNKNOWN"));
    assert_eq!(env["subject"]["version"].as_str(), Some("UNKNOWN"));
    assert_eq!(env["subject"]["pack_digest"].as_str(), Some("UNKNOWN"));
    assert_eq!(
        env["admission"]["gates_attempted"]
            .as_array()
            .expect("array"),
        &vec![serde_json::Value::String("law-gate.rq".to_string())]
    );
    assert_eq!(env["consequences"].as_array().expect("array").len(), 0);
}

/// Zero-side-effect contract preserved: a dry run writes no envelope (and
/// no legacy receipt), even on a gate refusal.
#[test]
fn dry_run_writes_no_portable_envelope_even_on_refusal() {
    let fx = write_fixture(true, false);
    let err = sync(
        &fx.project,
        SyncOptions {
            dry_run: true,
            ..Default::default()
        },
    )
    .expect_err("dry run still refuses on the gate");
    assert!(err.to_string().contains("FM-PACK-013"), "{err}");
    assert!(
        !envelope_path(&fx.project).exists(),
        "dry run must not write a portable envelope"
    );
    assert!(!fx.project.join(RECEIPT_REL_PATH).exists());
}
