//! Reasoner-independence proof for the SPARQL sync gates: the SAME
//! synthetic pack (ontology + one SPARQL-driven template + one `gates/*.rq`
//! SPARQL gate) syncs to byte-identical outputs under BOTH graph engines
//! (`EngineKind::GraphLaw` and `EngineKind::Oxigraph`), and the SAME
//! violating fixture is refused with `FM-PACK-013` under both.
//!
//! This is the property the SHACL→SPARQL gate migration exists to buy:
//! SHACL gates only ran on the GraphLaw engine (`validate_shacl` is a typed
//! `[FM-LAW-002]` refusal on oxigraph), so a gated pack silently could not
//! be A/B-tested across engines. Gates are plain ASK/SELECT queries through
//! `GraphEngine::query`, which both backends answer identically — proven
//! here with real syncs via the Rust API (like `graphlaw_e2e.rs`), real
//! TempDir filesystems, no mocks.
//!
//! Scaffold conventions copied from `framework_packs_e2e.rs`'s
//! `write_synthetic_pack`/`scaffold_synthetic_consumer` helpers.

#![allow(clippy::expect_used)]

use std::path::{Path, PathBuf};

use ggen_engine::sync::{sync, EngineKind, SyncOptions};
use tempfile::TempDir;

/// Write a minimal synthetic pack (pack.toml + ontology.ttl + templates +
/// one `gates/gate.rq`) into `dir/<name>/`. Mirrors
/// `framework_packs_e2e.rs::write_synthetic_pack`.
fn write_synthetic_pack(dir: &Path, name: &str, ontology_ttl: &str, gate_rq: &str) {
    let pack = dir.join(name);
    std::fs::create_dir_all(pack.join("templates")).expect("mkdir pack templates");
    std::fs::create_dir_all(pack.join("gates")).expect("mkdir pack gates");
    std::fs::write(
        pack.join("pack.toml"),
        format!(
            "[pack]\nname = \"{name}\"\nversion = \"0.0.1\"\ndescription = \"synthetic test pack\"\n"
        ),
    )
    .expect("write pack.toml");
    std::fs::write(pack.join("ontology.ttl"), ontology_ttl).expect("write pack ontology");
    std::fs::write(pack.join("gates/gate.rq"), gate_rq).expect("write pack gate");
    // A trivial static marker template plus one SPARQL-driven template, so
    // the byte-identity assertion below covers real query-driven rendering,
    // not just static content.
    std::fs::write(
        pack.join("templates/marker.txt.tmpl"),
        format!("---\nto: {name}_marker.txt\nforce: true\n---\npack {name} ran\n"),
    )
    .expect("write marker template");
    std::fs::write(
        pack.join("templates/things.txt.tmpl"),
        "---\n\
         to: things.txt\n\
         force: true\n\
         sparql:\n\
         \x20 rows: |\n\
         \x20   PREFIX ex: <http://example.org/ri#>\n\
         \x20   SELECT ?s ?val WHERE { ?s a ex:Thing ; ex:val ?val } ORDER BY ?s ?val\n\
         ---\n\
         {% for row in rows %}{{ row.s }} = {{ row.val }}\n{% endfor %}",
    )
    .expect("write things template");
}

/// Minimal consumer wired to the named synthetic pack, with a
/// caller-supplied project ontology (the union-drift lever).
fn scaffold_consumer(dir: &Path, pack_name: &str, consumer_ontology_ttl: &str) -> PathBuf {
    let project = dir.join("consumer");
    std::fs::create_dir_all(project.join("templates")).expect("mkdir templates");
    std::fs::write(project.join("ontology.ttl"), consumer_ontology_ttl)
        .expect("write ontology.ttl");
    std::fs::write(
        project.join("ggen.toml"),
        format!(
            "[project]\nname = \"consumer\"\n\n\
             [ontology]\nsource = \"ontology.ttl\"\n\n\
             [packs]\n{pack_name} = {{ path = \"../{pack_name}\" }}\n\n\
             [templates]\ndir = \"templates\"\n"
        ),
    )
    .expect("write ggen.toml");
    project
}

const PACK_ONTOLOGY: &str = r#"
@prefix ex: <http://example.org/ri#> .
ex:t1 a ex:Thing ; ex:val "alpha" .
ex:t2 a ex:Thing ; ex:val "beta" .
"#;

/// The maxCount-1-equivalent gate: any ex:Thing with two distinct ex:val
/// values in the union graph is a violation row.
const GATE_MAX_ONE_VAL: &str = r#"# MESSAGE: a Thing must carry exactly one ex:val (mirror-drift guard)
PREFIX ex: <http://example.org/ri#>
SELECT ?thing ?v1 ?v2 WHERE {
  ?thing a ex:Thing ; ex:val ?v1 , ?v2 .
  FILTER(STR(?v1) < STR(?v2))
}
ORDER BY ?thing
"#;

/// A consumer ontology that puts a SECOND ex:val on the pack's ex:t1 —
/// the violation exists only in the union, exactly the cross-source drift
/// shape the pack gate exists to refuse.
const VIOLATING_CONSUMER_ONTOLOGY: &str = r#"
@prefix ex: <http://example.org/ri#> .
ex:t1 ex:val "diverged-in-consumer" .
"#;

/// Scaffold a fresh conforming fixture and sync it under `engine`,
/// returning the generated bytes of both outputs plus the graph hash.
fn sync_conforming_under(engine: EngineKind) -> (Vec<u8>, Vec<u8>, String) {
    let dir = TempDir::new().expect("tempdir");
    write_synthetic_pack(dir.path(), "ri-pack", PACK_ONTOLOGY, GATE_MAX_ONE_VAL);
    let project = scaffold_consumer(dir.path(), "ri-pack", "");
    let report = sync(
        &project,
        SyncOptions {
            dry_run: false,
            engine,
        },
    )
    .expect("conforming fixture must sync");
    let things = std::fs::read(project.join("things.txt")).expect("things.txt");
    let marker = std::fs::read(project.join("ri-pack_marker.txt")).expect("marker");
    (things, marker, report.graph_hash_hex)
}

/// Both engines accept the conforming fixture and produce byte-identical
/// generated files (and the same canonical graph hash).
#[test]
fn both_engines_sync_a_gated_pack_to_identical_outputs() {
    let (things_law, marker_law, hash_law) = sync_conforming_under(EngineKind::GraphLaw);
    let (things_oxi, marker_oxi, hash_oxi) = sync_conforming_under(EngineKind::Oxigraph);

    // The SPARQL-driven output really rendered rows (not empty/static).
    let rendered = String::from_utf8(things_law.clone()).expect("utf8");
    assert!(
        rendered.contains("http://example.org/ri#t1 = alpha"),
        "query-driven content must have rendered: {rendered}"
    );
    assert!(
        rendered.contains("http://example.org/ri#t2 = beta"),
        "query-driven content must have rendered: {rendered}"
    );

    assert_eq!(
        things_law, things_oxi,
        "generated things.txt must be byte-identical across engines"
    );
    assert_eq!(
        marker_law, marker_oxi,
        "generated marker must be byte-identical across engines"
    );
    assert_eq!(
        hash_law, hash_oxi,
        "canonical graph hash must be engine-independent"
    );
}

/// The identical violating fixture is refused with FM-PACK-013 under BOTH
/// engines, before anything is written — the property SHACL gates could
/// not provide (validate_shacl is a typed refusal on oxigraph, so a
/// SHACL-gated pack could never even run there).
#[test]
fn violating_fixture_is_refused_under_both_engines() {
    for engine in [EngineKind::GraphLaw, EngineKind::Oxigraph] {
        let dir = TempDir::new().expect("tempdir");
        write_synthetic_pack(dir.path(), "ri-pack", PACK_ONTOLOGY, GATE_MAX_ONE_VAL);
        let project = scaffold_consumer(dir.path(), "ri-pack", VIOLATING_CONSUMER_ONTOLOGY);

        let err = sync(
            &project,
            SyncOptions {
                dry_run: false,
                engine,
            },
        )
        .expect_err("violating union graph must refuse under both engines");
        let msg = err.to_string();
        assert!(msg.contains("FM-PACK-013"), "engine {engine:?}: {msg}");
        assert!(msg.contains("ri-pack"), "engine {engine:?}: {msg}");
        assert!(
            msg.contains("a Thing must carry exactly one ex:val"),
            "engine {engine:?}: refusal must carry the gate MESSAGE: {msg}"
        );
        assert!(
            msg.contains("t1"),
            "engine {engine:?}: refusal must name the offending subject: {msg}"
        );
        assert!(
            !project.join("things.txt").exists() && !project.join("ri-pack_marker.txt").exists(),
            "engine {engine:?}: a refused sync must not have written any template output"
        );
    }
}
