//! Chicago-TDD end-to-end proof for `packs/typer-pack`: real filesystem
//! (`TempDir`), real graph engine, real Tera, the real `ggen_engine::sync`
//! pipeline — no hand-rolled reimplementation of SPARQL/template rendering.
//!
//! This supersedes `scripts/verify_python_framework_packs.py`'s coverage of
//! this pack: that script ran its own bespoke rdflib+Jinja2 pipeline
//! (defining its own `json_encode` filter, its own frontmatter parser) to
//! *simulate* what `ggen sync` does, which never actually proves the real
//! engine renders this pack's templates correctly — a divergence between the
//! script's hand-rolled renderer and the real one would go undetected. This
//! file drives the real `ggen_engine::sync::sync()` instead.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod support;

use std::path::{Path, PathBuf};
use std::process::Command;

use ggen_engine::sync::{sync, SyncOptions};
use support::{assert_gate_refuses, assert_idempotent, read, scaffold_pack};

fn packs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packs")
}

/// Real sync, real generated content, real Python syntax validity, real
/// idempotency — all against the actual ggen engine, not a simulation of it.
#[test]
fn typer_pack_generates_valid_python_and_is_idempotent() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("typer-pack"));

    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("first sync");

    let generated = read(&project, "src/typer_app.py");
    assert!(
        generated.contains("# GENERATED by ggen from typer-pack/ontology.ttl"),
        "missing generated marker: {generated}"
    );
    assert!(
        generated.contains(r#"name="ggen-typer""#),
        "app name must be real, interpolated content, not a literal template tag: {generated}"
    );
    assert!(
        generated.contains(r#"help="Ontology-generated Typer commands.""#),
        "{generated}"
    );
    assert!(
        generated.contains(r#"@app.command("greet")"#) && generated.contains("def greet("),
        "command function name derived from the ontology's typer:function: {generated}"
    );
    assert!(
        generated.contains(r#"help="Subject to greet.""#),
        "argument help must be real content: {generated}"
    );
    assert!(
        generated.contains(r#"typer.echo("Hello, {name}!".format(name=name))"#),
        "message template must render with the real format-string idiom: {generated}"
    );

    // Real Python syntax validity via a real subprocess, not a Rust-side
    // heuristic — matches the exact proof the superseded script made.
    let generated_path = project.join("src/typer_app.py");
    let parse = Command::new("python3")
        .args(["-c", "import ast,sys; ast.parse(open(sys.argv[1]).read())"])
        .arg(&generated_path)
        .output()
        .expect("spawn python3 -c ast.parse");
    assert!(
        parse.status.success(),
        "generated typer_app.py is not valid Python: {}",
        String::from_utf8_lossy(&parse.stderr)
    );

    assert_idempotent(&project);
}

/// Strongest proof of real value: the generated CLI is not just
/// syntactically valid Python, it is actually executed as a real
/// subprocess against the real `typer` package and produces the exact
/// deterministic output the ontology declares — matching the superseded
/// Python script's own `typer_exact_runtime` check, now against a
/// genuinely ggen-rendered file rather than the script's own simulated
/// rendering. SKIPs (never silently passes) if `typer` is not importable
/// in this environment, the same `BLOCKED:<TOKEN>` discipline this
/// repo's other e2e tests use for optional runtime dependencies.
#[test]
fn typer_pack_generated_cli_actually_runs_and_greets() {
    let python_has_typer = Command::new("python3")
        .args(["-c", "import typer"])
        .output()
        .is_ok_and(|o| o.status.success());
    if !python_has_typer {
        eprintln!("=== SKIP: BLOCKED:TYPER_ABSENT: `python3 -c \"import typer\"` failed ===");
        return;
    }

    let (_dir, project) = scaffold_pack(&packs_dir().join("typer-pack"));
    sync(
        &project,
        SyncOptions {
            dry_run: false,
            ..Default::default()
        },
    )
    .expect("sync");

    let generated_path = project.join("src/typer_app.py");
    let run = Command::new("python3")
        .arg(&generated_path)
        .args(["greet", "Sean"])
        .output()
        .expect("spawn generated typer CLI");
    assert!(
        run.status.success(),
        "generated CLI exited {:?}\nstdout: {}\nstderr: {}",
        run.status.code(),
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    let stdout = String::from_utf8_lossy(&run.stdout);
    assert_eq!(
        stdout.trim(),
        "Hello, Sean!",
        "generated CLI must produce the exact deterministic greeting the ontology declares"
    );
}

/// Sabotage: a `typer:Command` missing `typer:argumentHelp` (and every other
/// required property, since the sabotage individual only declares `a
/// typer:Command`) must be refused by the pack's own admission gate — the
/// same negative falsifier the superseded Python script exercised
/// (`typer_missing_argument_help`), now proven against the real engine.
#[test]
fn typer_pack_gate_refuses_command_missing_required_properties() {
    let (_dir, project) = scaffold_pack(&packs_dir().join("typer-pack"));

    assert_gate_refuses(
        &project,
        "@prefix typer: <http://seanchatmangpt.github.io/packs/typer#> .\n\
         typer:SabotageCommand a typer:Command .\n",
        "010_admission",
    );
}
