//! Generated Aggregates - DO NOT EDIT
//!
//! This file is automatically generated by ggen from ontology/entities.ttl
//! To make changes, edit the ontology and run: ggen sync

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub active_subs:i64,/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub mrr:Decimal,/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub publisher_id:Uuid,/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub this_month_commission:Decimal,/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub total_commissions:Decimal,/// Per-publisher revenue tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PublisherRevenueAggregate {pub updated_at:DateTime,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub active_subscriptions:i64,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub canceled_subscriptions:i64,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub id:Uuid,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub lifetime_commissions:Decimal,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub projected_arr:Decimal,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub total_mrr:Decimal,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub total_subscriptions:i64,/// Revenue tracking aggregate with subscription lifecycle
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RevenueAggregate {pub updated_at:DateTime,/// Manages affiliate link routes and click tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RouteAggregate {
}

impl  {
    /// Create new aggregate instance
    pub fn new(id: Uuid) -> Self {
        Self {
            id,
            ..Default::default()
        }
    }
}

impl Default for  {
    fn default() -> Self {
        Self {
        }
    }
}
