//! Generated HTTP Routes - DO NOT EDIT
//!
//! This file is automatically generated by ggen from ontology/commands.ttl
//! To make changes, edit the ontology and run: ggen sync

use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::post,
    Json, Router,
};
use serde_json::json;

use crate::commands::*;
use crate::handlers::*;

/// Build the complete router with all command endpoints
pub fn build_router() -> Router {
    Router::new()
        .route("/health", axum::routing::get(health_check))
.route("/cancelsubscription", post(handle_cancelsubscription_route))
.route("/computeattribution", post(handle_computeattribution_route))
.route("/processpayout", post(handle_processpayout_route))
.route("/recordclick", post(handle_recordclick_route))
.route("/recordrecurringcommission", post(handle_recordrecurringcommission_route))
.route("/r/{slug}", post(handle_resolveroute_route))
.route("/track/click", post(handle_trackclick_route))
.route("/tracksubscription", post(handle_tracksubscription_route))

}

/// Health check endpoint
async fn health_check() -> impl IntoResponse {
    Json(json!({
        "status": "healthy",
        "service": "Attribution",
        "version": env!("CARGO_PKG_VERSION")
    }))
}

/// Route handler for CancelSubscription
async fn handle_cancelsubscription_route(
    Json(command): Json<CancelSubscription>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "CancelSubscription"
        }))
    ))
}

/// Route handler for ComputeAttribution
async fn handle_computeattribution_route(
    Json(command): Json<ComputeAttribution>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "ComputeAttribution"
        }))
    ))
}

/// Route handler for ProcessPayout
async fn handle_processpayout_route(
    Json(command): Json<ProcessPayout>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "ProcessPayout"
        }))
    ))
}

/// Route handler for RecordClick
async fn handle_recordclick_route(
    Json(command): Json<RecordClick>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "RecordClick"
        }))
    ))
}

/// Route handler for RecordRecurringCommission
async fn handle_recordrecurringcommission_route(
    Json(command): Json<RecordRecurringCommission>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "RecordRecurringCommission"
        }))
    ))
}

/// Route handler for ResolveRoute
async fn handle_resolveroute_route(
    Json(command): Json<ResolveRoute>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "ResolveRoute"
        }))
    ))
}

/// Route handler for TrackClick
async fn handle_trackclick_route(
    Json(command): Json<TrackClick>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "TrackClick"
        }))
    ))
}

/// Route handler for TrackSubscription
async fn handle_tracksubscription_route(
    Json(command): Json<TrackSubscription>,
) -> Result<impl IntoResponse, StatusCode> {
    // TODO: Load aggregate from event store
    // TODO: Execute command handler
    // TODO: Persist event

    Ok((
        StatusCode::OK,
        Json(json!({
            "status": "accepted",
            "command": "TrackSubscription"
        }))
    ))
}


