PREFIX pcp: <urn:portable-consequence:>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?protocol ?ambient_authority ?receiptability_precedes_do WHERE {
  pcp:profile dcterms:identifier ?protocol ;
              pcp:ambientAuthority ?ambient_authority ;
              pcp:receiptabilityPrecedesDo ?receiptability_precedes_do .
}
