#!/usr/bin/env bash
# =============================================================================
# MCP+ Evidence Bundle Verification Script
#
# Text-blind verification of .mcpb evidence bundles.
# Verifies integrity without accessing payload content.
#
# Core axiom: A = μ(O), μ ∘ μ = μ, hash(A) = hash(μ(O)), O ⊨ Σ
#
# Generated by ggen - DO NOT EDIT MANUALLY
# =============================================================================

set -euo pipefail

# Configuration
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly LOG_DIR="${SCRIPT_DIR}/../logs"
readonly EVIDENCE_DIR="${SCRIPT_DIR}/../evidence"

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

# Ensure directories exist
mkdir -p "${LOG_DIR}" "${EVIDENCE_DIR}"

# Logging
log() {
    local level="$1"
    shift
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
    echo -e "${timestamp} [${level}] $*" | tee -a "${LOG_DIR}/verify-bundle.log"
}

# Verify bundle hash
verify_hash() {
    local bundle_file="$1"

    local version bundle_id created_at period_start period_end contract_family receipt_chain_root total_ops stored_hash

    version=$(jq -r '.version' "${bundle_file}")
    bundle_id=$(jq -r '.bundle_id' "${bundle_file}")
    created_at=$(jq -r '.created_at' "${bundle_file}")
    period_start=$(jq -r '.period_start' "${bundle_file}")
    period_end=$(jq -r '.period_end' "${bundle_file}")
    contract_family=$(jq -r '.contract_family' "${bundle_file}")
    receipt_chain_root=$(jq -r '.receipt_chain_root' "${bundle_file}")
    total_ops=$(jq -r '.metrics.total_operations' "${bundle_file}")
    stored_hash=$(jq -r '.bundle_hash' "${bundle_file}")

    local hash_input="${version}|${bundle_id}|${created_at}|${period_start}|${period_end}|${contract_family}|${receipt_chain_root}|${total_ops}"
    local computed_hash
    computed_hash=$(echo -n "${hash_input}" | sha256sum | cut -d' ' -f1)

    if [[ "${computed_hash}" == "${stored_hash}" ]]; then
        echo -e "  ${GREEN}✓${NC} Bundle hash verified"
        return 0
    else
        echo -e "  ${RED}✗${NC} Bundle hash mismatch"
        echo "    Expected: ${stored_hash}"
        echo "    Computed: ${computed_hash}"
        return 1
    fi
}

# Verify version format
verify_version() {
    local bundle_file="$1"

    local version
    version=$(jq -r '.version' "${bundle_file}")

    if [[ "${version}" =~ ^1\. ]]; then
        echo -e "  ${GREEN}✓${NC} Version format valid (${version})"
        return 0
    else
        echo -e "  ${RED}✗${NC} Invalid version format: ${version}"
        return 1
    fi
}

# Verify period validity
verify_period() {
    local bundle_file="$1"

    local period_start period_end
    period_start=$(jq -r '.period_start' "${bundle_file}")
    period_end=$(jq -r '.period_end' "${bundle_file}")

    # Convert to timestamps for comparison
    local start_ts end_ts
    start_ts=$(date -d "${period_start}" +%s 2>/dev/null || echo "0")
    end_ts=$(date -d "${period_end}" +%s 2>/dev/null || echo "0")

    if [[ "${start_ts}" -le "${end_ts}" ]]; then
        echo -e "  ${GREEN}✓${NC} Period validity confirmed"
        return 0
    else
        echo -e "  ${RED}✗${NC} Invalid period: start (${period_start}) > end (${period_end})"
        return 1
    fi
}

# Verify metrics consistency
verify_metrics() {
    local bundle_file="$1"

    local total_ops receipt_count refused_ops refusal_count
    total_ops=$(jq -r '.metrics.total_operations' "${bundle_file}")
    receipt_count=$(jq -r '.receipts | length' "${bundle_file}")
    refused_ops=$(jq -r '.metrics.refused_operations' "${bundle_file}")
    refusal_count=$(jq -r '.refusals | length' "${bundle_file}")

    local result=0

    if [[ "${total_ops}" == "${receipt_count}" ]]; then
        echo -e "  ${GREEN}✓${NC} Operation count matches receipts (${total_ops})"
    else
        echo -e "  ${RED}✗${NC} Operation count mismatch: metrics=${total_ops}, receipts=${receipt_count}"
        result=1
    fi

    if [[ "${refused_ops}" == "${refusal_count}" ]]; then
        echo -e "  ${GREEN}✓${NC} Refusal count matches (${refused_ops})"
    else
        echo -e "  ${RED}✗${NC} Refusal count mismatch: metrics=${refused_ops}, refusals=${refusal_count}"
        result=1
    fi

    return ${result}
}

# Verify refusal code format
verify_refusals() {
    local bundle_file="$1"

    local refusal_count
    refusal_count=$(jq -r '.refusals | length' "${bundle_file}")

    if [[ "${refusal_count}" -eq 0 ]]; then
        echo -e "  ${GREEN}✓${NC} No refusals to verify"
        return 0
    fi

    # Check each refusal has valid format
    local valid=true
    for i in $(seq 0 $((refusal_count - 1))); do
        local category code
        category=$(jq -r ".refusals[${i}].code.category" "${bundle_file}")
        code=$(jq -r ".refusals[${i}].code.code" "${bundle_file}")

        if [[ -z "${category}" ]] || [[ "${category}" == "null" ]]; then
            echo -e "  ${RED}✗${NC} Refusal ${i}: missing category"
            valid=false
        fi
    done

    if [[ "${valid}" == "true" ]]; then
        echo -e "  ${GREEN}✓${NC} All ${refusal_count} refusals have valid format"
        return 0
    else
        return 1
    fi
}

# Generate verification report
generate_report() {
    local bundle_file="$1"
    local passed="$2"

    local bundle_id
    bundle_id=$(jq -r '.bundle_id' "${bundle_file}")

    local report_file="${EVIDENCE_DIR}/verification-${bundle_id}-$(date +%s).json"

    local result
    if [[ "${passed}" == "true" ]]; then
        result="PASS"
    else
        result="FAIL"
    fi

    cat > "${report_file}" << EOF
{
    "verification_id": "verify-$(date +%s)-$$",
    "bundle_id": "${bundle_id}",
    "bundle_file": "${bundle_file}",
    "result": "${result}",
    "verified_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
    "verifier": "$(hostname)",
    "checks": {
        "version_format": true,
        "bundle_hash": true,
        "period_validity": true,
        "metrics_consistency": true,
        "refusal_format": true
    },
    "text_blind": true
}
EOF

    echo "${report_file}"
}

# Main verification
verify_bundle() {
    local bundle_file="$1"

    if [[ ! -f "${bundle_file}" ]]; then
        echo -e "${RED}Error: Bundle file not found: ${bundle_file}${NC}"
        exit 1
    fi

    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║         MCP+ Evidence Bundle Verification                    ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  Bundle: ${bundle_file}"
    echo ""

    log "INFO" "Starting verification of: ${bundle_file}"

    local all_passed=true

    echo -e "${YELLOW}Running verification checks...${NC}"
    echo ""

    # Run all checks
    if ! verify_version "${bundle_file}"; then all_passed=false; fi
    if ! verify_hash "${bundle_file}"; then all_passed=false; fi
    if ! verify_period "${bundle_file}"; then all_passed=false; fi
    if ! verify_metrics "${bundle_file}"; then all_passed=false; fi
    if ! verify_refusals "${bundle_file}"; then all_passed=false; fi

    echo ""

    # Generate report
    local report
    report=$(generate_report "${bundle_file}" "${all_passed}")

    if [[ "${all_passed}" == "true" ]]; then
        echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║                    VERIFICATION: PASS                        ║${NC}"
        echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
        log "INFO" "Verification PASSED for: ${bundle_file}"
    else
        echo -e "${RED}╔══════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${RED}║                    VERIFICATION: FAIL                        ║${NC}"
        echo -e "${RED}╚══════════════════════════════════════════════════════════════╝${NC}"
        log "ERROR" "Verification FAILED for: ${bundle_file}"
    fi

    echo ""
    echo -e "  Report: ${report}"

    if [[ "${all_passed}" == "true" ]]; then
        return 0
    else
        return 1
    fi
}

# Help
cmd_help() {
    cat << EOF
MCP+ Evidence Bundle Verification

USAGE:
    $(basename "$0") <bundle_file>
    $(basename "$0") --create-test-bundle

OPTIONS:
    --create-test-bundle    Create a test bundle for verification demo

DESCRIPTION:
    Performs text-blind verification of .mcpb evidence bundles.
    Verifies integrity without accessing payload content.

CHECKS PERFORMED:
    1. Version format (must be 1.x)
    2. Bundle hash integrity (SHA-256)
    3. Period validity (start <= end)
    4. Metrics consistency (counts match arrays)
    5. Refusal code format validation

EXAMPLES:
    $(basename "$0") evidence/bundle-2027-01.json
    $(basename "$0") --create-test-bundle
EOF
}

# Create test bundle for demo
create_test_bundle() {
    local bundle_file="${EVIDENCE_DIR}/test-bundle-$(date +%s).json"

    local bundle_id="bundle-test-$(date +%s)"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local yesterday
    yesterday=$(date -u -d "-1 day" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

    local receipt_chain_root
    receipt_chain_root=$(echo -n "test-genesis" | sha256sum | cut -d' ' -f1)

    local hash_input="1.0.0|${bundle_id}|${now}|${yesterday}|${now}|test-family|${receipt_chain_root}|0"
    local bundle_hash
    bundle_hash=$(echo -n "${hash_input}" | sha256sum | cut -d' ' -f1)

    cat > "${bundle_file}" << EOF
{
    "version": "1.0.0",
    "bundle_id": "${bundle_id}",
    "created_at": "${now}",
    "period_start": "${yesterday}",
    "period_end": "${now}",
    "contract_family": "test-family",
    "receipt_chain_root": "${receipt_chain_root}",
    "receipts": [],
    "refusals": [],
    "metrics": {
        "total_operations": 0,
        "successful_operations": 0,
        "refused_operations": 0,
        "total_duration_us": 0,
        "peak_memory_bytes": 0
    },
    "attestations": [],
    "bundle_hash": "${bundle_hash}"
}
EOF

    echo -e "${GREEN}Created test bundle: ${bundle_file}${NC}"
    echo ""

    # Verify it
    verify_bundle "${bundle_file}"
}

# Main
main() {
    if [[ $# -lt 1 ]]; then
        cmd_help
        exit 1
    fi

    case "$1" in
        --create-test-bundle)
            create_test_bundle
            ;;
        --help|-h|help)
            cmd_help
            ;;
        *)
            verify_bundle "$1"
            ;;
    esac
}

main "$@"
