//! Typed catalog of ~/cargo-cicd's real `cargo cicd <noun> <verb>` command
//! surface, transcribed from `packs/cargo-cicd-pack/ontology.ttl`.
//!
//! Generated by `cargo-cicd-pack`. Source-audited 2026-07-18 against
//! `~/cargo-cicd` v26.7.6 (`src/nouns/*.rs`, see each row's `source_file`
//! field) -- not merely README-derived. `arg_count`/`args` are re-read
//! directly from each real `#[verb(...)]`-annotated `pub fn cmd_*` signature
//! (round-3 addition). Reference only -- this crate does not invoke
//! `cargo-cicd`.

/// One `cargo cicd <noun> <verb>` command row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CargoCicdCommand {
    pub noun: &'static str,
    pub verb: &'static str,
    pub doc: &'static str,
    /// Path (relative to `~/cargo-cicd`) of the source file this row was
    /// audited against, e.g. `"src/nouns/git.rs"`. Empty string only for
    /// the deprecated `doctor`/`""` compatibility row.
    pub source_file: &'static str,
    /// Number of real CLI-facing arguments the underlying `cmd_*` function
    /// takes, source-verified against `~/cargo-cicd`.
    pub arg_count: u8,
    /// `"name:Type;name:Type;..."` for commands with `arg_count > 0`, else
    /// `""`. Source-verified, not invented.
    pub args: &'static str,
}

/// The full catalog, ordered by (noun, verb).
pub const CARGO_CICD_COMMANDS: &[CargoCicdCommand] = &[
    CargoCicdCommand { noun: "certification", verb: "show", doc: "IEC 61508 / ISO 26262 compliance summary for cargo-cicd certification.", source_file: "src/nouns/certification.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "claude_context", verb: "show", doc: "Shows the Claude agent context snapshot for the current repository.", source_file: "src/nouns/claude_context.rs", arg_count: 1, args: "repo:Option<String>" },
    CargoCicdCommand { noun: "doctor", verb: "", doc: "DEPRECATED 2026-07-18: superseded by cc:doctor-repo/cc:doctor-evidence/cc:doctor-diff -- source audit found doctor is not actually a bare noun with an empty verb; retained only so previously-generated literal shapes do not silently vanish.", source_file: "", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "doctor", verb: "diff", doc: "Diffs current repository health against a previously written baseline.", source_file: "src/nouns/doctor.rs", arg_count: 2, args: "repo:Option<String>;baseline:Option<String>" },
    CargoCicdCommand { noun: "doctor", verb: "evidence", doc: "", source_file: "src/nouns/doctor.rs", arg_count: 1, args: "json:bool" },
    CargoCicdCommand { noun: "doctor", verb: "repo", doc: "Diagnoses repository health against a recorded baseline and reports evidence drift.", source_file: "src/nouns/doctor.rs", arg_count: 5, args: "repo:Option<String>;json:bool;write_baseline:Option<String>;baseline:Option<String>;diff:bool" },
    CargoCicdCommand { noun: "evidence", verb: "audit", doc: "", source_file: "src/nouns/evidence.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "evidence", verb: "doctor", doc: "Adjudicates and inspects recorded process evidence (XES/OCEL logs).", source_file: "src/nouns/evidence.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "evidence", verb: "list", doc: "", source_file: "src/nouns/evidence.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "evidence", verb: "reset", doc: "", source_file: "src/nouns/evidence.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "evidence", verb: "show", doc: "", source_file: "src/nouns/evidence.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "gate", verb: "repo", doc: "Evaluates repository-level release gate conditions.", source_file: "src/nouns/gate.rs", arg_count: 3, args: "repo:Option<String>;json:bool;sarif:bool" },
    CargoCicdCommand { noun: "git", verb: "close", doc: "Lawful branch-close sequence.", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "git", verb: "commit", doc: "", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "git", verb: "diff", doc: "", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "git", verb: "fetch", doc: "", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "git", verb: "stage", doc: "", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "git", verb: "status", doc: "", source_file: "src/nouns/git.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "hooks", verb: "install", doc: "Installs git hooks that integrate cargo-cicd with an external CI provider.", source_file: "src/nouns/hooks.rs", arg_count: 3, args: "repo:Option<String>;provider:Option<String>;json:bool" },
    CargoCicdCommand { noun: "hooks", verb: "pre-tool-use", doc: "", source_file: "src/nouns/hooks.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "hooks", verb: "uninstall", doc: "", source_file: "src/nouns/hooks.rs", arg_count: 3, args: "repo:Option<String>;provider:Option<String>;json:bool" },
    CargoCicdCommand { noun: "ocel", verb: "replay", doc: "Replays recorded OCEL process-evidence events.", source_file: "src/nouns/ocel.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "pipeline", verb: "run", doc: "Runs the workspace's CI/CD pipeline definition.", source_file: "src/nouns/pipeline.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "pipeline", verb: "status", doc: "", source_file: "src/nouns/pipeline.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "pipeline", verb: "validate", doc: "", source_file: "src/nouns/pipeline.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "publish", verb: "check", doc: "", source_file: "src/nouns/publish.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "publish", verb: "run", doc: "Publishes eligible workspace crates to crates.io after verifying release readiness.", source_file: "src/nouns/publish.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "publish", verb: "validate", doc: "", source_file: "src/nouns/publish.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "receipt", verb: "audit", doc: "", source_file: "src/nouns/receipt.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "receipt", verb: "verify", doc: "Verifies a recorded receipt's integrity.", source_file: "src/nouns/receipt.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "release_gate", verb: "check", doc: "Checks whether release-gate conditions are currently satisfied.", source_file: "src/nouns/release_gate.rs", arg_count: 3, args: "repo:Option<String>;release_id:Option<String>;json:bool" },
    CargoCicdCommand { noun: "sbom", verb: "generate", doc: "Generates a Software Bill of Materials (SBOM) via CycloneDX.", source_file: "src/nouns/sbom.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "sbom", verb: "show", doc: "", source_file: "src/nouns/sbom.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "standing", verb: "refresh", doc: "Refreshes generated standing documents from current repository state.", source_file: "src/nouns/standing.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "standing", verb: "report", doc: "", source_file: "src/nouns/standing.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "standing", verb: "verify", doc: "", source_file: "src/nouns/standing.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "status", verb: "audit", doc: "", source_file: "src/nouns/status.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "status", verb: "show", doc: "Workspace status: dirty files, pending tests, trybuild result, publish readiness.", source_file: "src/nouns/status.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "target", verb: "prune", doc: "", source_file: "src/nouns/target.rs", arg_count: 1, args: "apply:bool" },
    CargoCicdCommand { noun: "target", verb: "show", doc: "Reports target/ directory size.", source_file: "src/nouns/target.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "test", verb: "bench", doc: "", source_file: "src/nouns/test.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "test", verb: "changed", doc: "Runs only tests for crates whose source changed since the last green commit.", source_file: "src/nouns/test.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "test", verb: "run", doc: "", source_file: "src/nouns/test.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "trace", verb: "profile", doc: "Profiles and reports timing traces for cargo-cicd operations.", source_file: "src/nouns/trace.rs", arg_count: 3, args: "repo:Option<String>;profile:String;json:bool" },
    CargoCicdCommand { noun: "trybuild", verb: "changed", doc: "Runs trybuild compile-fail/compile-pass fixtures for crates changed since the last green commit.", source_file: "src/nouns/trybuild.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "trybuild", verb: "review", doc: "", source_file: "src/nouns/trybuild.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "trybuild", verb: "update", doc: "", source_file: "src/nouns/trybuild.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "verify", verb: "repo", doc: "Verifies a repository against configured checks, including semver compatibility.", source_file: "src/nouns/verify.rs", arg_count: 2, args: "repo:Option<String>;json:bool" },
    CargoCicdCommand { noun: "workspace", verb: "doctor", doc: "Diagnoses Cargo.toml, toolchain, git repo, cicd.toml.", source_file: "src/nouns/workspace.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "workspace", verb: "list", doc: "", source_file: "src/nouns/workspace.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "workspace", verb: "sync", doc: "", source_file: "src/nouns/workspace.rs", arg_count: 0, args: "" },
    CargoCicdCommand { noun: "workspace", verb: "validate", doc: "", source_file: "src/nouns/workspace.rs", arg_count: 0, args: "" },
];

/// Look up one command row by exact (noun, verb). Real, callable behavior
/// over the generated catalog -- not merely a static table.
pub fn find_command(noun: &str, verb: &str) -> Option<&'static CargoCicdCommand> {
    CARGO_CICD_COMMANDS
        .iter()
        .find(|c| c.noun == noun && c.verb == verb)
}

/// All command rows for a given noun, in catalog order.
pub fn commands_for_noun(noun: &str) -> impl Iterator<Item = &'static CargoCicdCommand> + '_ {
    CARGO_CICD_COMMANDS.iter().filter(move |c| c.noun == noun)
}

/// True iff `(noun, verb)` is a known `cargo cicd` command in this catalog.
pub fn is_valid_command(noun: &str, verb: &str) -> bool {
    find_command(noun, verb).is_some()
}

/// The distinct set of nouns in the catalog, in first-seen (sorted) order.
pub fn distinct_nouns() -> Vec<&'static str> {
    let mut nouns: Vec<&'static str> = CARGO_CICD_COMMANDS.iter().map(|c| c.noun).collect();
    nouns.sort_unstable();
    nouns.dedup();
    nouns
}

/// Parses one command's `args` field into `(name, type)` pairs. Real parsing
/// logic over ontology-sourced data (`cc:args`), not a hand-copied literal --
/// returns an empty `Vec` for `arg_count == 0` commands.
pub fn parse_args(cmd: &CargoCicdCommand) -> Vec<(&'static str, &'static str)> {
    if cmd.args.is_empty() {
        return Vec::new();
    }
    cmd.args
        .split(';')
        .filter_map(|pair| pair.split_once(':'))
        .collect()
}

/// True iff `parse_args` yields exactly `arg_count` entries for every row in
/// the catalog -- a structural consistency check between the two
/// independently-sourced `cc:argCount`/`cc:args` facts.
pub fn args_are_consistent() -> bool {
    CARGO_CICD_COMMANDS
        .iter()
        .all(|c| parse_args(c).len() as u8 == c.arg_count)
}

/// Round 4: the real return type shared by every `cmd_*` function backing
/// every command in `CARGO_CICD_COMMANDS`, source-verified against
/// `~/cargo-cicd/src/nouns/*.rs` (all 21 files).
pub const CARGO_CICD_RETURN_TYPE: &str = "clap_noun_verb::Result<()>";

/// Real error enum name every command's return type is parameterized over
/// (`~/clap-noun-verb/src/error.rs`).
pub const CARGO_CICD_ERROR_ENUM: &str = "NounVerbError";

/// The `#[non_exhaustive]` `NounVerbError` variant names, transcribed
/// verbatim from `~/clap-noun-verb/src/error.rs` (lines 11-51), sorted.
pub const CARGO_CICD_ERROR_VARIANTS: &[&str] = &[
    "ArgumentError",
    "CommandNotFound",
    "ExecutionError",
    "Generic",
    "InvalidStructure",
    "MiddlewareError",
    "PluginError",
    "TelemetryError",
    "ValidationFailed",
    "VerbNotFound",
];

/// True iff every command in the catalog shares the single documented
/// return type (a real, source-verified uniform relation, not a per-row
/// duplicate fact) -- checked by construction here since `arg_count`/`args`
/// are per-row but the return type/error enum are catalog-wide facts.
pub fn all_commands_share_return_contract() -> bool {
    !CARGO_CICD_COMMANDS.is_empty()
        && !CARGO_CICD_RETURN_TYPE.is_empty()
        && !CARGO_CICD_ERROR_ENUM.is_empty()
}
