package com.example.entity;

import jakarta.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Generated JPA Entity: YWorkItem
 * Represents a work item in YAWL workflow.
 *
 * Generated by ggen Rule 3: JPA Entities
 * Source: YAWL ontology
 */
@Entity
@Table(name = "y_work_item", schema = "yawl")
public class YWorkItem implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "work_item_id", length = 36, updatable = false)
    private String workItemId;

    @Column(name = "task_id", length = 255, nullable = false)
    private String taskId;

    @Column(name = "case_id", length = 255, nullable = false)
    private String caseId;

    @Column(name = "work_item_status", length = 50, nullable = false)
    private String status;

    @Column(name = "enablement_time", nullable = true)
    private LocalDateTime enablementTime;

    @Column(name = "firing_time", nullable = true)
    private LocalDateTime firingTime;

    @Column(name = "start_time", nullable = true)
    private LocalDateTime startTime;

    @Column(name = "completion_time", nullable = true)
    private LocalDateTime completionTime;

    @Column(name = "resource_assigned", length = 255, nullable = true)
    private String resourceAssigned;

    @Column(name = "version", nullable = false)
    @Version
    private Integer version;

    // Constructors
    public YWorkItem() {
    }

    public YWorkItem(String workItemId, String taskId, String caseId, String status) {
        this.workItemId = workItemId;
        this.taskId = taskId;
        this.caseId = caseId;
        this.status = status;
    }

    // Getters and Setters
    public String getWorkItemId() {
        return workItemId;
    }

    public void setWorkItemId(String workItemId) {
        this.workItemId = workItemId;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getCaseId() {
        return caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getEnablementTime() {
        return enablementTime;
    }

    public void setEnablementTime(LocalDateTime enablementTime) {
        this.enablementTime = enablementTime;
    }

    public LocalDateTime getFiringTime() {
        return firingTime;
    }

    public void setFiringTime(LocalDateTime firingTime) {
        this.firingTime = firingTime;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getCompletionTime() {
        return completionTime;
    }

    public void setCompletionTime(LocalDateTime completionTime) {
        this.completionTime = completionTime;
    }

    public String getResourceAssigned() {
        return resourceAssigned;
    }

    public void setResourceAssigned(String resourceAssigned) {
        this.resourceAssigned = resourceAssigned;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Override
    public String toString() {
        return "YWorkItem{" +
                "workItemId='" + workItemId + '\'' +
                ", taskId='" + taskId + '\'' +
                ", caseId='" + caseId + '\'' +
                ", status='" + status + '\'' +
                ", version=" + version +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof YWorkItem)) return false;
        YWorkItem that = (YWorkItem) o;
        return workItemId != null && workItemId.equals(that.workItemId);
    }

    @Override
    public int hashCode() {
        return workItemId != null ? workItemId.hashCode() : 0;
    }
}
