//! Living-loop integration tests for GGEN-SRC-001, GGEN-SRC-002, GGEN-SRC-003.
//!
//! GGEN-SRC-001: output_file targets a source-caste directory (generated/, output/, gen/).
//! GGEN-SRC-002: rendered .rs file contains "DO NOT EDIT" / "auto-generated" banner.
//! GGEN-SRC-003: rendered .rs file contains source-caste comment (e.g. "// do not reason about").
//!
//! These tests verify that check_files_in_root() surfaces the correct diagnostics
//! and that clean fixtures produce no false positives.

use ggen_lsp::check::{check_files_in_root, discover_law_surfaces};
use lsp_max::lsp_types;
use std::fs;
use tempfile::TempDir;

fn minimal_ontology(dir: &std::path::Path) {
    fs::write(
        dir.join("onto.ttl"),
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .\n<urn:test> a owl:Ontology .\n",
    )
    .expect("write onto.ttl");
}

fn write_ggen_toml(dir: &std::path::Path, output_file: &str) {
    fs::write(
        dir.join("ggen.toml"),
        format!(
            r#"[project]
name = "fixture-src"
version = "0.1.0"

[ontology]
source = "onto.ttl"

[[generation.rules]]
name = "rule-src"
query = {{ inline = "SELECT ?name WHERE {{ ?name a <urn:test:Thing> }}" }}
template = {{ inline = "{{{{ name }}}}" }}
output_file = "{output_file}"
"#
        ),
    )
    .expect("write ggen.toml");
}

// ---------------------------------------------------------------------------
// GGEN-SRC-001 tests
// ---------------------------------------------------------------------------

#[test]
fn src_001_fires_for_generated_dir_output() {
    let tmp = TempDir::new().expect("tempdir");
    let root = tmp.path();
    minimal_ontology(root);
    write_ggen_toml(root, "generated/foo.rs");

    let surfaces = discover_law_surfaces(root);
    let report = check_files_in_root(root, &surfaces, false);

    let src_001_errors: Vec<_> = report
        .files
        .iter()
        .flat_map(|f| &f.diagnostics)
        .filter(|d| {
            d.code.as_ref().and_then(|c| match c {
                lsp_types::NumberOrString::String(s) => Some(s.as_str()),
                _ => None,
            }) == Some("GGEN-SRC-001")
                && d.severity == Some(lsp_types::DiagnosticSeverity::ERROR)
        })
        .collect();

    assert!(
        !src_001_errors.is_empty(),
        "Expected GGEN-SRC-001 ERROR for output_file = 'generated/foo.rs', got none.\nReport: {report:?}"
    );
}

#[test]
fn src_001_not_raised_for_normal_output() {
    let tmp = TempDir::new().expect("tempdir");
    let root = tmp.path();
    minimal_ontology(root);
    write_ggen_toml(root, "out/foo.rs");

    let surfaces = discover_law_surfaces(root);
    let report = check_files_in_root(root, &surfaces, false);

    let src_001_errors: Vec<_> = report
        .files
        .iter()
        .flat_map(|f| &f.diagnostics)
        .filter(|d| {
            d.code.as_ref().and_then(|c| match c {
                lsp_types::NumberOrString::String(s) => Some(s.as_str()),
                _ => None,
            }) == Some("GGEN-SRC-001")
        })
        .collect();

    assert!(
        src_001_errors.is_empty(),
        "Expected no GGEN-SRC-001 for output_file = 'out/foo.rs', but got: {src_001_errors:?}"
    );
}

// ---------------------------------------------------------------------------
// GGEN-SRC-002 tests
// ---------------------------------------------------------------------------

#[test]
fn src_002_fires_for_do_not_edit_banner() {
    let tmp = TempDir::new().expect("tempdir");
    let root = tmp.path();
    minimal_ontology(root);
    // output_file targets "src/foo.rs" — fold_src_002_003 will scan root and src/ dir
    write_ggen_toml(root, "src/foo.rs");

    // Create a .rs file in root with a DO NOT EDIT banner
    fs::write(
        root.join("banned.rs"),
        "// DO NOT EDIT — generated by ggen from onto.ttl\npub struct Foo;\n",
    )
    .expect("write banned.rs");

    let surfaces = discover_law_surfaces(root);
    let report = check_files_in_root(root, &surfaces, false);

    let src_002_errors: Vec<_> = report
        .files
        .iter()
        .flat_map(|f| &f.diagnostics)
        .filter(|d| {
            d.code.as_ref().and_then(|c| match c {
                lsp_types::NumberOrString::String(s) => Some(s.as_str()),
                _ => None,
            }) == Some("GGEN-SRC-002")
                && d.severity == Some(lsp_types::DiagnosticSeverity::ERROR)
        })
        .collect();

    assert!(
        !src_002_errors.is_empty(),
        "Expected GGEN-SRC-002 ERROR for 'banned.rs' with DO NOT EDIT banner, got none.\nReport: {report:?}"
    );
}

#[test]
fn src_002_not_raised_for_clean_rs_file() {
    let tmp = TempDir::new().expect("tempdir");
    let root = tmp.path();
    minimal_ontology(root);
    write_ggen_toml(root, "src/foo.rs");

    // Create a clean .rs file in root with no banned banners
    fs::write(
        root.join("clean.rs"),
        "//! Clean module — authored by hand.\npub struct Bar;\n",
    )
    .expect("write clean.rs");

    let surfaces = discover_law_surfaces(root);
    let report = check_files_in_root(root, &surfaces, false);

    let src_002_errors: Vec<_> = report
        .files
        .iter()
        .flat_map(|f| &f.diagnostics)
        .filter(|d| {
            d.code.as_ref().and_then(|c| match c {
                lsp_types::NumberOrString::String(s) => Some(s.as_str()),
                _ => None,
            }) == Some("GGEN-SRC-002")
        })
        .collect();

    assert!(
        src_002_errors.is_empty(),
        "Expected no GGEN-SRC-002 for clean.rs, but got: {src_002_errors:?}"
    );
}

// ---------------------------------------------------------------------------
// GGEN-SRC-003 tests
// ---------------------------------------------------------------------------

#[test]
fn src_003_fires_for_source_caste_comment() {
    let tmp = TempDir::new().expect("tempdir");
    let root = tmp.path();
    minimal_ontology(root);
    write_ggen_toml(root, "src/foo.rs");

    // Create a .rs file in root with a source-caste comment
    fs::write(
        root.join("caste.rs"),
        "// do not reason about this file\npub struct Baz;\n",
    )
    .expect("write caste.rs");

    let surfaces = discover_law_surfaces(root);
    let report = check_files_in_root(root, &surfaces, false);

    let src_003_errors: Vec<_> = report
        .files
        .iter()
        .flat_map(|f| &f.diagnostics)
        .filter(|d| {
            d.code.as_ref().and_then(|c| match c {
                lsp_types::NumberOrString::String(s) => Some(s.as_str()),
                _ => None,
            }) == Some("GGEN-SRC-003")
                && d.severity == Some(lsp_types::DiagnosticSeverity::ERROR)
        })
        .collect();

    assert!(
        !src_003_errors.is_empty(),
        "Expected GGEN-SRC-003 ERROR for 'caste.rs' with source-caste comment, got none.\nReport: {report:?}"
    );
}
