%% ============================================================================
%% hello_server - Generated from RDF specification
%% ============================================================================
%% Minimal gen_server that demonstrates RDF-driven code generation
%%
%% This module was generated by ggen from an RDF ontology.
%% The 20% that matters: module + behavior + state + callbacks.

-module(hello_server).
-behaviour(gen_server).

%% API
-export([start_link/0]).
-export([increment/0]).
-export([get_count/0]).
-export([reset/0]).

%% gen_server callbacks
-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).

-record(state, {
    counter :: integer()
}).

%% ============================================================================
%% API
%% ============================================================================

start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

increment() ->
    gen_server:call(?MODULE, increment).

get_count() ->
    gen_server:call(?MODULE, get_count).

reset() ->
    gen_server:cast(?MODULE, reset).

%% ============================================================================
%% gen_server callbacks
%% ============================================================================

init([]) ->
    {ok, #state{counter = 0}}.

handle_call(increment, _From, #state{counter = Count} = State) ->
    NewCount = Count + 1,
    {reply, {ok, NewCount}, State#state{counter = NewCount}};

handle_call(get_count, _From, #state{counter = Count} = State) ->
    {reply, {ok, Count}, State};

handle_call(_Request, _From, State) ->
    {reply, {error, unknown_call}, State}.

handle_cast(reset, State) ->
    {noreply, State#state{counter = 0}};

handle_cast(_Msg, State) ->
    {noreply, State}.

handle_info(_Info, State) ->
    {noreply, State}.

terminate(_Reason, _State) ->
    ok.

code_change(_OldVsn, State, _Extra) ->
    {ok, State}.
