// GENERATED by `ggen sync` (`[templates] aggregate_modules = true`).
// One mount per generated `src/*.rs` output this run produced. Do not
// edit by hand — regenerated every sync. Consumer wiring: exactly one
// permanent line in your own lib.rs:
//     include!("ggen_pack_mods.rs");

#[path = "全体.rs"]
pub mod __;
#[path = "原点.rs"]
pub mod __;
#[path = "品質.rs"]
pub mod __;
#[path = "安全.rs"]
pub mod __;
#[path = "改善.rs"]
pub mod __;
#[path = "系譜.rs"]
pub mod __;
#[path = "語彙.rs"]
pub mod __;
#[path = "タクト.rs"]
pub mod ___;
#[path = "価値流.rs"]
pub mod ___;
#[path = "受領証.rs"]
pub mod ___;
#[path = "平準化.rs"]
pub mod ___;
#[path = "自働化.rs"]
pub mod ___;
#[path = "かんばん.rs"]
pub mod ____;
#[path = "アンドン.rs"]
pub mod ____;
#[path = "ポカヨケ.rs"]
pub mod ____;
#[path = "五回なぜ.rs"]
pub mod ____;
#[path = "人間中心.rs"]
pub mod ____;
#[path = "工程能力.rs"]
pub mod ____;
#[path = "標準作業.rs"]
pub mod ____;
#[path = "現地現物.rs"]
pub mod ____;
#[path = "自動選択.rs"]
pub mod ____;
#[path = "必要時生産.rs"]
pub mod _____;
#[path = "ムリムラムダ.rs"]
pub mod ______;
#[path = "青い川のダム.rs"]
pub mod ______;
#[path = "lib.rs"]
pub mod lib;
