#!/usr/bin/env bash
# produce-l5-template-derivation-evidence -- the l5p:TemplateDerivationRecord
# producer for the L5 pack-closure promotion campaign's cap05 ("Generated
# verification") truthfulness gate.
#
# WHY THIS EXISTS (real, concrete gap, not a hypothetical): a pack's
# `l5p:missingCap` list in .specify/pack-l5-promotion.ttl is free text --
# nothing checks whether removing `l5p:cap05` from that list (i.e. claiming
# "the proof suite is itself generated from the ontology, expected values
# SPARQL-derived, not hardcoded") is actually true. A template with no
# `sparql:` frontmatter key is, by reading the graph alone, structurally
# indistinguishable from one that correctly has no ontology dependency.
# praxis-core-pack's and star-toml-pack's real cap05 closures both existed
# specifically BECAUSE a value was hand-transcribed instead of SPARQL-
# derived, until a real `sparql:`-frontmatter proof template was added
# (packs/praxis-core-pack/templates/refusal_taxonomy_sparql_derived_proof.rs.tmpl,
# packs/star-toml-pack/templates/star_toml_config_sparql_derived_proof.rs.tmpl)
# -- that is the ONLY shape of evidence this producer looks for.
#
# PATTERN: mirrors packs/ggen-verify-pack/ontology.ttl's own Producer/Check
# split exactly: this script runs a REAL check (walks the filesystem,
# inspects real template frontmatter) and emits admitted facts. It NEVER
# judges whether a pack's L5 claim is truthful -- that adjudication is
# .specify/gates/l5-cap05-template-derivation-claim.rq's job, run at
# `ggen sync run` time against the union graph. This script only records
# reality and ALWAYS exits 0, exactly like
# packs/ggen-verify-pack/bootstrap/verify-evidence-bootstrap.sh's own
# documented contract ("This script ALWAYS exits 0: it records reality, it
# does not judge it.").
#
# NAMESPACE CHOICE (disclosed, not silent): this producer emits l5p: facts,
# not ver: facts, even though the Producer/Check *shape* is borrowed from
# ggen-verify-pack. ver: models a downstream CONSUMER's own build/test/
# clippy verification evidence (a reusable contract any consumer wires in).
# What this script records is specific to the L5 promotion campaign's own
# bookkeeping over THIS repo's packs/ directory -- a claim-vs-evidence link
# for one specific rubric item (l5p:cap05) in .specify/pack-l5-promotion.ttl.
# It is not a reusable per-consumer check; it is this campaign's own
# governance fact. l5p: (already imported at root ggen.toml, already the
# home of l5p:Pack/l5p:Capability/l5p:missingCap) is the correct home.
#
# SCOPE, MECHANICAL (not semantic): a template counts as cap05 evidence for
# its pack iff (a) it renders into `tests/...` (its `to:` frontmatter value
# starts with "tests/") AND (b) its frontmatter block contains a real
# `sparql:` key. Templates with `sparql:` rendering to `src/`/`docs/` (e.g.
# wasm4pm-facts-pack's registry_catalog.rs.tmpl, a data catalog, not a
# proof) do NOT count -- confirmed by hand before this producer was written
# that treating "any sparql: template exists anywhere in the pack" as
# sufficient would be a false-negative-prone gate (see this script's sibling
# gate file's own header for the worked example).
#
# STALENESS, DISCLOSED: this producer is NOT re-run automatically by
# `ggen sync run` (unlike ggen-verify-pack's templates/produce_*.tmpl, which
# ARE ggen-generated). It must be re-run by hand (`just l5-template-evidence`)
# whenever a pack's templates/ directory changes, exactly like
# ggen-verify-pack's own documented "run the emitter before syncing"
# requirement. A stale evidence file fails CLOSED for the truthfulness gate
# (an added real proof template not yet re-scanned still shows as missing,
# so the gate still refuses until re-run -- annoying, never a false pass)
# but can fail OPEN in the opposite direction: a real proof template that is
# later DELETED without a `just l5-template-evidence` re-run leaves stale
# "evidence exists" facts on disk that no longer reflect reality until the
# next re-run. This is the same class of staleness gap ggen-verify-pack's
# own gates/030_evidence_fresh.rq names and cannot close at root scope
# either (it requires `[law] reflexive = true`, a field this repo's own
# declarative-rules manifest schema does not have -- see ggen.toml's
# `[validation]` comment). Disclosed here rather than silently assumed away.
set -uo pipefail

cd "$(dirname "$0")/../.." || exit 2   # scripts/ci/ -> repo root

if [ ! -d packs ]; then
  echo "produce-l5-template-derivation-evidence.sh: no packs/ directory found -- run from repo root" >&2
  exit 2
fi

OUT_DIR="evidence"
OUT="$OUT_DIR/l5-template-derivation.ttl"
mkdir -p "$OUT_DIR"

RECORDED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

TMP_OUT="$(mktemp "${TMPDIR:-/tmp}/l5-template-derivation.XXXXXX")"
trap 'rm -f "$TMP_OUT"' EXIT

{
  echo "# GENERATED by scripts/ci/produce-l5-template-derivation-evidence.sh at $RECORDED_AT -- do not edit."
  echo "# Real, mechanically-recorded facts about packs/*/templates/*.tmpl frontmatter."
  echo "# Consumed (never authored) by .specify/gates/l5-cap05-template-derivation-claim.rq."
  echo "# Re-run this script after any packs/*/templates/ change -- see this script's own"
  echo "# header comment for the staleness contract."
  echo "@prefix l5p: <http://ggen.org/l5-promotion#> ."
  echo
} > "$TMP_OUT"

i=0
while IFS= read -r tmpl; do
  # Line-based frontmatter state machine (mirrors
  # packs/ggen-verify-pack/bootstrap/verify-evidence-bootstrap.sh's own
  # grep/awk-not-full-YAML-parse style) -- robust to blank lines inside the
  # frontmatter block (real multi-line `sparql:` query bodies have them).
  in_fm=false
  dashes=0
  to_val=""
  has_sparql=false
  while IFS= read -r line; do
    if [ "$line" = "---" ]; then
      dashes=$((dashes + 1))
      if [ "$dashes" -eq 1 ]; then in_fm=true; continue; fi
      if [ "$dashes" -eq 2 ]; then break; fi
    fi
    if [ "$in_fm" = true ]; then
      case "$line" in
        to:*)
          to_val="${line#to:}"
          to_val="${to_val# }"
          to_val="${to_val%\"}"
          to_val="${to_val#\"}"
          ;;
        sparql:*) has_sparql=true ;;
      esac
    fi
  done < "$tmpl"

  pack_id="$(echo "$tmpl" | cut -d/ -f2)"   # packs/<pack>/templates/<file>.tmpl -> <pack>
  i=$((i + 1))
  {
    echo "l5p:tdr-$i a l5p:TemplateDerivationRecord ;"
    echo "    l5p:packId \"$pack_id\" ;"
    echo "    l5p:templatePath \"$tmpl\" ;"
    echo "    l5p:renderTo \"$to_val\" ;"
    echo "    l5p:hasSparqlFrontmatter $has_sparql ."
    echo
  } >> "$TMP_OUT"
done < <(find packs -name '*.tmpl' | LC_ALL=C sort)

mv "$TMP_OUT" "$OUT"
trap - EXIT

echo "produce-l5-template-derivation-evidence.sh: recorded $i template records -> $OUT"
exit 0
