//! Typed catalog of the real `#[proc_macro_attribute]` fns exported by the
//! `rmcp-macros` sibling crate (7 total): `tool`, `tool_router`,
//! `tool_handler`, `prompt`, `prompt_router`, `prompt_handler`,
//! `task_handler`.
//!
//! Generated by `rmcp-pack` from `packs/rmcp-pack/ontology.ttl`. Reference
//! only -- see `rmcp_stub_handler.rs` (same pack) for a real, compiling
//! invocation of `tool_router`/`tool`/`tool_handler`.

/// One real `rmcp-macros` `#[proc_macro_attribute]` fn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RmcpMacro {
    pub macro_name: &'static str,
    /// "attribute" for all 7 -- every one is `#[proc_macro_attribute]`.
    pub macro_kind: &'static str,
    /// The real `syn` AST node the macro's implementation parses its
    /// `input` `TokenStream` into: "fn" (`syn::ImplItemFn`) or "impl"
    /// (`syn::ItemImpl`).
    pub applies_to: &'static str,
    /// `field|type|usage` groups, `@@`-joined, transcribed verbatim from
    /// the macro's own real doc table (3 columns -- no "required" column
    /// exists in the real source; see ontology.ttl's rmcp:macroFields
    /// comment for why this differs from clap-noun-verb-pack's 4-column
    /// cnv:args grammar).
    pub macro_fields: &'static str,
    /// file:line citation into the real vendored `rmcp-macros-2.2.0`
    /// source.
    pub source_file: &'static str,
}

/// All 7 real `rmcp-macros` attribute macros, ordered by name.
pub const RMCP_MACROS: &[RmcpMacro] = &[
    RmcpMacro { macro_name: "prompt", macro_kind: "attribute", applies_to: "fn", macro_fields: "name|String|The name of the prompt. If not provided, it defaults to the function name.@@description|String|A description of the prompt. The document of this function will be used if not provided.@@arguments|Expr|An expression that evaluates to `Option<Vec<PromptArgument>>` defining the prompt's arguments. If not provided, it will automatically generate arguments from the `Parameters<T>` type found in the function signature.", source_file: "rmcp-macros-2.2.0/src/lib.rs:223-228 (doc 201-222); target AST confirmed via src/prompt.rs:82 syn::parse2::<ImplItemFn>" },
    RmcpMacro { macro_name: "prompt_handler", macro_kind: "attribute", applies_to: "impl", macro_fields: "router|Expr|The expression to access the `PromptRouter` instance. Defaults to `Self::prompt_router()`.@@meta|Expr|Optional metadata for `ListPromptsResult`.", source_file: "rmcp-macros-2.2.0/src/lib.rs:296-301 (doc 268-295); target AST confirmed via src/prompt_handler.rs:26 syn::parse2::<ItemImpl>; also auto-generates get_info() with prompts capability if not already provided" },
    RmcpMacro { macro_name: "prompt_router", macro_kind: "attribute", applies_to: "impl", macro_fields: "router|Ident|The name of the router function to be generated. Defaults to `prompt_router`.@@vis|Visibility|The visibility of the generated router function. Defaults to empty.", source_file: "rmcp-macros-2.2.0/src/lib.rs:261-266 (doc 230-260); target AST confirmed via src/prompt_router.rs:21 syn::parse2::<ItemImpl>" },
    RmcpMacro { macro_name: "task_handler", macro_kind: "attribute", applies_to: "impl", macro_fields: "processor|Expr|Custom accessor expression for a shared OperationProcessor; the real darling default (rmcp-macros/src/task_handler.rs:14-19) is `self.processor`, i.e. a field of type `Arc<Mutex<OperationProcessor>>`. Unlike the other 6 macros, this field is stated in prose (not a markdown table) in the macro's own doc comment.", source_file: "rmcp-macros-2.2.0/src/lib.rs:310-315 (doc 303-309); target AST confirmed via src/task_handler.rs:24 syn::parse2::<ItemImpl>; generates enqueue_task/list_tasks; requires the handler type to implement Clone (captured inside spawned futures, per the macro's own doc)" },
    RmcpMacro { macro_name: "tool", macro_kind: "attribute", applies_to: "fn", macro_fields: "name|String|The name of the tool. If not provided, it defaults to the function name.@@description|String|A description of the tool. The document of this function will be used.@@input_schema|Expr|A JSON Schema object defining the expected parameters for the tool. If not provide, if will use the json schema of its argument with type `Parameters<T>`@@annotations|ToolAnnotationsAttribute|Additional tool information. Defaults to `None`.", source_file: "rmcp-macros-2.2.0/src/lib.rs:37-42 (doc 14-36); target AST confirmed via src/tool.rs:222 syn::parse2::<ImplItemFn>" },
    RmcpMacro { macro_name: "tool_handler", macro_kind: "attribute", applies_to: "impl", macro_fields: "router|Expr|The expression to access the `ToolRouter` instance. Defaults to `Self::tool_router()`.@@meta|Expr|Optional metadata for `ListToolsResult`.@@name|String|Custom server name. Defaults to `CARGO_CRATE_NAME`.@@version|String|Custom server version. Defaults to `CARGO_PKG_VERSION`.@@instructions|String|Optional human-readable instructions about using this server.", source_file: "rmcp-macros-2.2.0/src/lib.rs:194-199 (doc 133-193); target AST confirmed via src/tool_handler.rs:42 syn::parse2::<ItemImpl>; generates call_tool/list_tools/get_tool/get_info" },
    RmcpMacro { macro_name: "tool_router", macro_kind: "attribute", applies_to: "impl", macro_fields: "router|Ident|The name of the router function to be generated. Defaults to `tool_router`.@@vis|Visibility|The visibility of the generated router function. Defaults to empty.@@server_handler|flag|When set, also emits `#[::rmcp::tool_handler]` on `impl ServerHandler for Self` so you can omit a separate `#[tool_handler]` block.", source_file: "rmcp-macros-2.2.0/src/lib.rs:126-131 (doc 44-125); target AST confirmed via src/tool_router.rs:39 syn::parse2::<ItemImpl>" },
];
