#!/usr/bin/env python3
"""Verify and bootstrap the ontology-owned cross-repository LSP projections."""
from __future__ import annotations
import argparse, hashlib, json, pathlib, re, sys
from typing import Any
try:
    from rdflib import Graph, Namespace, RDF
except ImportError as error:
    raise SystemExit(f"BLOCKED:RDFLIB_UNAVAILABLE:{error}")
L = Namespace("https://ggen.dev/ontology/lsp-contract#")
D = Namespace("http://purl.org/dc/terms/")

def value(graph: Graph, subject: Any, predicate: Any) -> str:
    result = graph.value(subject, predicate)
    if result is None:
        raise ValueError(f"missing {predicate} on {subject}")
    return str(result)

def ordered(graph: Graph, class_name: str) -> list[Any]:
    return sorted(graph.subjects(RDF.type, L[class_name]), key=lambda subject: int(value(graph, subject, L.order)))

def load(path: pathlib.Path) -> dict[str, Any]:
    graph = Graph().parse(path, format="turtle")
    root = L.ContractV1
    methods = []
    for subject in ordered(graph, "Method"):
        capability = value(graph, subject, L.capabilityKey)
        methods.append({
            "order": int(value(graph, subject, L.order)), "method": value(graph, subject, L.method),
            "rust_handler": value(graph, subject, L.rustHandler), "legacy_handler": value(graph, subject, L.legacyHandler),
            "kind": value(graph, subject, L.kind), "family": value(graph, subject, L.family),
            "capability": None if capability == "none" else capability,
            "description": value(graph, subject, D.description),
            "required_by": sorted(str(item) for item in graph.objects(subject, L.requiredBy)),
        })
    def rows(class_name: str, fields: list[tuple[str, Any]]) -> list[dict[str, Any]]:
        return [{"order": int(value(graph, subject, L.order)), **{name: value(graph, subject, predicate) for name, predicate in fields}}
                for subject in ordered(graph, class_name)]
    capabilities = {
        "textDocumentSync": {"openClose": True, "change": 1, "save": {"includeText": False}},
        "completionProvider": {"triggerCharacters": [":", "@", ".", "{", "[", '"', "|"]},
        "hoverProvider": True, "definitionProvider": True, "referencesProvider": True,
        "renameProvider": {"prepareProvider": True}, "documentSymbolProvider": True,
        "workspaceSymbolProvider": True, "documentFormattingProvider": True,
        "documentRangeFormattingProvider": True,
        "codeActionProvider": {"codeActionKinds": ["quickfix"], "resolveProvider": False},
        "foldingRangeProvider": True,
        "semanticTokensProvider": {"legend": {"tokenTypes": ["namespace", "class", "property", "variable", "keyword", "string", "number", "comment", "function"], "tokenModifiers": []}, "full": True},
        "inlayHintProvider": True, "codeLensProvider": {"resolveProvider": False},
        "callHierarchyProvider": True, "typeHierarchyProvider": True,
    }
    surfaces = rows("Surface", [("extension", L.extension), ("analyzer", L.analyzer), ("description", D.description)])
    for row, subject in zip(surfaces, ordered(graph, "Surface")):
        row["required_by"] = sorted(str(item) for item in graph.objects(subject, L.requiredBy))
    return {
        "schema": value(graph, root, L.schema), "version": value(graph, root, L.contractVersion),
        "authority": value(graph, root, L.authorityPath), "generator": value(graph, root, L.generatorConfig),
        "legacy": {"repository": value(graph, root, L.legacyRepository), "branch": value(graph, root, L.legacyBranch)},
        "methods": methods, "surfaces": surfaces,
        "diagnostics": rows("Diagnostic", [("code", L.code), ("severity", L.severity), ("description", D.description), ("owner", L.owner)]),
        "invariants": rows("Invariant", [("code", L.code), ("description", D.description)]),
        "representations": rows("Representation", [("id", L.identifier), ("repository", L.repository), ("path", L.path), ("role", L.role), ("state", L.state)]),
        "capabilities": capabilities,
    }

def render_json(contract: dict[str, Any]) -> str:
    return json.dumps(contract, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"

def render_rust(contract: dict[str, Any]) -> str:
    lines = ["//! GENERATED by ggen from `self-host/lsp-contract/ontology.ttl`.", "//! Edit the ontology and rerun the self-host contract projection.", "", f'pub const CONTRACT_VERSION: &str = {json.dumps(contract["version"])};', f'pub const CONTRACT_SCHEMA: &str = {json.dumps(contract["schema"])};', 'pub const GGEN_SRC_004: &str = "GGEN-SRC-004";', "", "pub const REQUIRED_METHODS: &[&str] = &["]
    lines += [f'    {json.dumps(row["method"])},' for row in contract["methods"]]
    lines += ["];", "", "pub const REQUIRED_SURFACES: &[&str] = &["] + [f'    {json.dumps(row["extension"])},' for row in contract["surfaces"]]
    lines += ["];", "", "pub const DECLARED_DIAGNOSTICS: &[&str] = &["] + [f'    {json.dumps(row["code"])},' for row in contract["diagnostics"]]
    lines += ["];", "", "#[must_use]", "pub fn has_method(method: &str) -> bool {", "    REQUIRED_METHODS.contains(&method)", "}", "", "#[cfg(test)]", "mod tests {", "    use super::*;", "", "    #[test]", "    fn generated_contract_is_sorted_and_unique() {", "        let mut methods = REQUIRED_METHODS.to_vec();", "        methods.sort_unstable();", "        methods.dedup();", "        assert_eq!(methods.len(), REQUIRED_METHODS.len());", "        assert_eq!(REQUIRED_METHODS.len(), 29);", "        assert_eq!(REQUIRED_SURFACES.len(), 8);", "        assert_eq!(DECLARED_DIAGNOSTICS.len(), 11);", "    }", "}", ""]
    return "\n".join(lines)

def render_markdown(contract: dict[str, Any]) -> str:
    lines = ["# ggen LSP Contract", "", "> GENERATED by `ggen sync` from `self-host/lsp-contract/ontology.ttl`. Edit the ontology, not this projection.", "", f"- Contract: `{contract['schema']}`", f"- Version: `{contract['version']}`", "- Kernel runtime: `seanchatmangpt/ggen:crates/ggen-lsp`", f"- Independent receiver: `{contract['legacy']['repository']}:{contract['legacy']['branch']}`", "", "## Required protocol methods", "", "| # | Method | Rust handler | Capability | Family |", "|---:|---|---|---|---|"]
    lines += [f"| {row['order']} | `{row['method']}` | `{row['rust_handler']}` | `{row['capability'] or 'lifecycle'}` | {row['family']} |" for row in contract["methods"]]
    lines += ["", "## Required source surfaces", "", "| Extension | Analyzer | Description |", "|---|---|---|"] + [f"| `.{row['extension']}` | `{row['analyzer']}` | {row['description']} |" for row in contract["surfaces"]]
    lines += ["", "## Diagnostic ownership", "", "| Code | Severity | Owner | Meaning |", "|---|---|---|---|"] + [f"| `{row['code']}` | {row['severity']} | {row['owner']} | {row['description']} |" for row in contract["diagnostics"]]
    lines += ["", "## Invariants", ""] + [f"{row['order']}. **`{row['code']}`** — {row['description']}" for row in contract["invariants"]]
    lines += ["", "## Representation graph", "", "| Representation | Repository | Path | Role |", "|---|---|---|---|"] + [f"| `{row['id']}` | `{row['repository']}` | `{row['path']}` | {row['role']} |" for row in contract["representations"]] + [""]
    return "\n".join(lines)

def outputs(root: pathlib.Path, contract: dict[str, Any]) -> dict[pathlib.Path, str]:
    return {root / "crates/ggen-lsp/generated/lsp-contract.json": render_json(contract), root / "crates/ggen-lsp/src/generated_contract.rs": render_rust(contract), root / "docs/generated/LSP_CONTRACT.md": render_markdown(contract)}

def runtime_findings(root: pathlib.Path, legacy: pathlib.Path | None, contract: dict[str, Any], skip_kernel: bool) -> list[str]:
    findings: list[str] = []
    if not skip_kernel:
        server = (root / "crates/ggen-lsp/src/server.rs").read_text()
        state = (root / "crates/ggen-lsp/src/state.rs").read_text()
        source = (root / "crates/ggen-lsp/src/source_contract.rs").read_text()
        findings += [f"RUST_HANDLER_ABSENT:{row['method']}:{row['rust_handler']}" for row in contract["methods"] if row["rust_handler"] != "framework" and not re.search(rf"\b(?:async\s+)?fn\s+{re.escape(row['rust_handler'])}\b", server)]
        findings += [f"RUST_SURFACE_UNOBSERVED:{ext}" for ext in ("ttl", "nt", "nq", "rq", "sparql", "tera", "toml") if f'"{ext}"' not in state and f'ends_with(".{ext}")' not in state]
        if "GGEN-SRC-004" not in source: findings.append("RUST_DIAGNOSTIC_ABSENT:GGEN-SRC-004")
    if legacy:
        expected_json, expected_rust = render_json(contract), render_rust(contract)
        if (legacy / "authority/lsp-contract.json").read_text() != expected_json: findings.append("LEGACY_CONTRACT_DRIFT")
        if (legacy / "src/generated_contract.rs").read_text() != expected_rust: findings.append("LEGACY_RUST_PROJECTION_DRIFT")
        backend, capabilities, analysis = [(legacy / path).read_text() for path in ("src/backend.rs", "src/capabilities.rs", "src/analysis.rs")]
        findings += [f"LEGACY_HANDLER_ABSENT:{row['method']}:{row['legacy_handler']}" for row in contract["methods"] if row["legacy_handler"] != "framework" and not re.search(rf"\b(?:async\s+)?fn\s+{re.escape(row['legacy_handler'])}\b", backend)]
        for capability in sorted({row["capability"] for row in contract["methods"] if row["capability"]}):
            dynamic = capability == "typeHierarchyProvider" and "textDocument/prepareTypeHierarchy" in backend and "register_capability" in backend
            if capability not in capabilities + backend and re.sub(r"(?<!^)(?=[A-Z])", "_", capability).lower() not in capabilities + backend and not dynamic: findings.append(f"LEGACY_CAPABILITY_ABSENT:{capability}")
        findings += [f"LEGACY_SURFACE_ABSENT:{row['extension']}" for row in contract["surfaces"] if f'"{row["extension"]}"' not in analysis + backend]
        generated = (legacy / "src/generated_contract.rs").read_text()
        findings += [f"LEGACY_DIAGNOSTIC_ABSENT:{row['code']}" for row in contract["diagnostics"] if row["owner"] in {"legacy", "both"} and row["code"] not in analysis + generated]
    return findings

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ggen-root", type=pathlib.Path)
    parser.add_argument("--legacy-root", type=pathlib.Path)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--skip-runtime", action="store_true")
    parser.add_argument("--skip-kernel-runtime", action="store_true")
    parser.add_argument("--report", type=pathlib.Path)
    args = parser.parse_args()
    root = (args.ggen_root or pathlib.Path(__file__).resolve().parents[2]).resolve()
    ontology = root / "self-host/lsp-contract/ontology.ttl"
    contract = load(ontology)
    expected = outputs(root, contract)
    if args.write:
        for path, content in expected.items(): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)
    findings = [f"PROJECTION_DRIFT:{path.relative_to(root)}" for path, content in expected.items() if not path.is_file() or path.read_text() != content]
    if not args.skip_runtime: findings += runtime_findings(root, args.legacy_root.resolve() if args.legacy_root else None, contract, args.skip_kernel_runtime)
    report = {"schema": "ggen.lsp.representation-sync-report/1", "contract_schema": contract["schema"], "contract_version": contract["version"], "ontology_sha256": hashlib.sha256(ontology.read_bytes()).hexdigest(), "projection_sha256": {str(path.relative_to(root)): hashlib.sha256(content.encode()).hexdigest() for path, content in expected.items()}, "method_count": len(contract["methods"]), "surface_count": len(contract["surfaces"]), "diagnostic_count": len(contract["diagnostics"]), "representation_count": len(contract["representations"]), "legacy_checked": args.legacy_root is not None, "kernel_runtime_checked": not args.skip_runtime and not args.skip_kernel_runtime, "findings": sorted(set(findings)), "standing": "ALIVE" if not findings else "BUILD_BROKEN", "claim_ceiling": "REPRESENTATION_SYNC_ONLY", "ggen_execution": "BLOCKED_TOOLCHAIN_UNAVAILABLE"}
    encoded = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.report: args.report.parent.mkdir(parents=True, exist_ok=True); args.report.write_text(encoded)
    sys.stdout.write(encoded)
    return 0 if not findings else 1
if __name__ == "__main__":
    raise SystemExit(main())
