//! Proof tests for `wasm4pm-sandbox-pack`'s generated catalog
//! (`src/sandbox_catalog.rs`) and dispatch trait
//! (`src/sandbox_actuator_trait.rs`).
//!
//! Cardinality and full-field assertions are rendered from the same
//! `capabilities` SPARQL binding that produced `CAPABILITY_CATALOG` itself
//! (same convention as `wasm4pm-algorithms-pack`'s proof template) --
//! editing `ontology.ttl` changes both the catalog and this proof on the
//! next `ggen sync` together, not just one of them.
//!
//! Generated by `wasm4pm-sandbox-pack`.

#[path = "../src/sandbox_catalog.rs"]
mod sandbox_catalog;
#[path = "../src/sandbox_actuator_trait.rs"]
mod sandbox_actuator_trait;

use sandbox_catalog::{from_capability_id, CapabilityId, Operation, CAPABILITY_CATALOG};
use sandbox_actuator_trait::{check_preconditions, CapabilityRefusal, CapabilityRequest};
use std::collections::HashSet;

fn find(capability_id: &str) -> &'static sandbox_catalog::CapabilityInfo {
    CAPABILITY_CATALOG
        .iter()
        .find(|row| row.id.as_str() == capability_id)
        .unwrap_or_else(|| panic!("no CAPABILITY_CATALOG row for capability_id={capability_id:?}"))
}

// ---------------------------------------------------------------------------
// Cardinality -- SPARQL-derived, not hand-counted.
// ---------------------------------------------------------------------------

const EXPECTED_TOTAL: usize = 6;

#[test]
fn catalog_len_matches_sparql_derived_total() {
    assert_eq!(CAPABILITY_CATALOG.len(), EXPECTED_TOTAL);
}

#[test]
fn capability_id_values_are_unique_across_the_catalog() {
    let mut seen: HashSet<&str> = HashSet::new();
    for row in CAPABILITY_CATALOG {
        assert!(seen.insert(row.id.as_str()), "duplicate capability_id {:?}", row.id.as_str());
    }
    assert_eq!(seen.len(), EXPECTED_TOTAL);
}

// ---------------------------------------------------------------------------
// Full-field assertions -- generated per-row from the SAME `capabilities`
// binding that produced CAPABILITY_CATALOG, over EVERY row.
// ---------------------------------------------------------------------------

#[test]
fn generated_full_field_assertions_over_every_catalog_row() {
    {
        let row = find("compile_python");
        assert_eq!(row.id, CapabilityId::CompilePython, "id mismatch for compile_python");
        assert_eq!(row.language, "python");
        assert_eq!(row.operation, Operation::Compile);
        assert_eq!(row.doc, "Syntax-checks a candidate Python source file via `python -m py_compile` -- Python has no separate build artifact, so this is the compile-equivalent admission gate.");
        assert_eq!(row.timeout_ms, 5000);
        assert_eq!(row.authority_scope, "sandbox.compile");
    }
    {
        let row = find("compile_rust");
        assert_eq!(row.id, CapabilityId::CompileRust, "id mismatch for compile_rust");
        assert_eq!(row.language, "rust");
        assert_eq!(row.operation, Operation::Compile);
        assert_eq!(row.doc, "Builds a candidate Rust crate via `cargo build` in an isolated subprocess.");
        assert_eq!(row.timeout_ms, 60000);
        assert_eq!(row.authority_scope, "sandbox.compile");
    }
    {
        let row = find("execute_python");
        assert_eq!(row.id, CapabilityId::ExecutePython, "id mismatch for execute_python");
        assert_eq!(row.language, "python");
        assert_eq!(row.operation, Operation::Execute);
        assert_eq!(row.doc, "Runs a compiled-clean Python source file in an isolated subprocess and captures stdout/stderr/exit status.");
        assert_eq!(row.timeout_ms, 10000);
        assert_eq!(row.authority_scope, "sandbox.execute");
    }
    {
        let row = find("execute_rust");
        assert_eq!(row.id, CapabilityId::ExecuteRust, "id mismatch for execute_rust");
        assert_eq!(row.language, "rust");
        assert_eq!(row.operation, Operation::Execute);
        assert_eq!(row.doc, "Runs the binary produced by compile_rust in an isolated subprocess and captures stdout/stderr/exit status.");
        assert_eq!(row.timeout_ms, 10000);
        assert_eq!(row.authority_scope, "sandbox.execute");
    }
    {
        let row = find("run_cargo_test");
        assert_eq!(row.id, CapabilityId::RunCargoTest, "id mismatch for run_cargo_test");
        assert_eq!(row.language, "rust");
        assert_eq!(row.operation, Operation::Test);
        assert_eq!(row.doc, "Runs `cargo test` against a candidate crate in an isolated subprocess (compiles internally, so it has no separate compile precondition).");
        assert_eq!(row.timeout_ms, 60000);
        assert_eq!(row.authority_scope, "sandbox.execute");
    }
    {
        let row = find("run_pytest");
        assert_eq!(row.id, CapabilityId::RunPytest, "id mismatch for run_pytest");
        assert_eq!(row.language, "python");
        assert_eq!(row.operation, Operation::Test);
        assert_eq!(row.doc, "Runs `pytest` against a candidate solution plus its test file in an isolated subprocess.");
        assert_eq!(row.timeout_ms, 20000);
        assert_eq!(row.authority_scope, "sandbox.execute");
    }
}

// ---------------------------------------------------------------------------
// from_capability_id / as_str round trip -- real calls, literal inputs.
// ---------------------------------------------------------------------------

#[test]
fn every_row_as_str_round_trips_through_from_capability_id() {
    for row in CAPABILITY_CATALOG {
        assert_eq!(from_capability_id(row.id.as_str()), Some(row.id));
    }
}

#[test]
fn from_capability_id_rejects_an_unrelated_string() {
    assert_eq!(from_capability_id("totally_unrelated_string"), None);
}

#[test]
fn from_capability_id_rejects_empty_string() {
    assert_eq!(from_capability_id(""), None);
}

// ---------------------------------------------------------------------------
// check_preconditions -- real behavior, not mocked. This is the one piece
// of actual dispatch logic this ggen-generated crate contains (everything
// else is static catalog data), so it gets a real behavioral proof.
// ---------------------------------------------------------------------------

#[test]
fn execute_python_is_refused_without_compile_python_having_passed() {
    let request = CapabilityRequest {
        capability: CapabilityId::ExecutePython,
        files: vec![("solution.py".to_string(), "print('hi')".to_string())],
        already_passed: vec![],
    };
    assert_eq!(
        check_preconditions(&request),
        Err(CapabilityRefusal::PreconditionNotMet { missing: CapabilityId::CompilePython }),
    );
}

#[test]
fn execute_python_is_admitted_once_compile_python_has_passed() {
    let request = CapabilityRequest {
        capability: CapabilityId::ExecutePython,
        files: vec![("solution.py".to_string(), "print('hi')".to_string())],
        already_passed: vec![CapabilityId::CompilePython],
    };
    assert_eq!(check_preconditions(&request), Ok(()));
}

#[test]
fn execute_python_is_refused_when_a_different_capability_passed_instead() {
    // Proves the check matches on the specific required capability, not
    // merely "something passed."
    let request = CapabilityRequest {
        capability: CapabilityId::ExecutePython,
        files: vec![("solution.py".to_string(), "print('hi')".to_string())],
        already_passed: vec![CapabilityId::CompileRust],
    };
    assert_eq!(
        check_preconditions(&request),
        Err(CapabilityRefusal::PreconditionNotMet { missing: CapabilityId::CompilePython }),
    );
}

#[test]
fn run_cargo_test_has_no_precondition_and_is_admitted_with_nothing_passed_yet() {
    // run_cargo_test compiles internally (no separate compile_rust
    // precondition in the ontology) -- confirms a capability with an empty
    // `requires` list is admitted from a cold start.
    let request = CapabilityRequest {
        capability: CapabilityId::RunCargoTest,
        files: vec![("Cargo.toml".to_string(), "".to_string())],
        already_passed: vec![],
    };
    assert_eq!(check_preconditions(&request), Ok(()));
}

#[test]
fn compile_rust_has_no_precondition_and_is_admitted_from_a_cold_start() {
    let request = CapabilityRequest {
        capability: CapabilityId::CompileRust,
        files: vec![("src/main.rs".to_string(), "fn main() {}".to_string())],
        already_passed: vec![],
    };
    assert_eq!(check_preconditions(&request), Ok(()));
}
