//! Full-coverage round-trip proof for `wasm4pm-cognition-pack`'s generated
//! catalog (`src/w4pm_cognition_catalog.rs`), covering **all** breeds --
//! not the 8-row hand-transcribed spot sample in
//! `tests/w4pm_cognition_proof.rs`.
//!
//! Honest limitation (do not overclaim this closes the Test-generation gap
//! to L5): every literal asserted below is rendered by Tera from the same
//! `breeds` SPARQL query and the same `ORDER BY ?breed_id` clause that
//! produces `BREED_CATALOG` in `cognition_catalog.rs.tmpl`. That means this
//! suite WILL catch a dropped row, a wrong count, or a genuine
//! citation/label typo introduced anywhere except inside the shared
//! `sparql(query=...)` binding path itself (e.g. it still catches a broken
//! Tera for-loop index or an `as_str()`/`from_breed_id()` match-arm
//! misalignment, since those are independently re-derived per row here from
//! `row.breed_id`/`row.breed_label`, not copied from the catalog file). It
//! will NOT catch a bug shared by both templates' identical query text
//! (e.g. a wrong `ORDER BY` clause copy-pasted into both files) -- that
//! class of bug is still caught only by `w4pm_cognition_proof.rs`'s
//! independently hand-transcribed literals for its 8 sampled rows.
//! Together the two suites give full-row coverage AND at least partial
//! independent-source coverage; neither file alone reaches the L5 bar of
//! "sufficient evidence on its own" against every possible drift class.
//!
//! Round-3 addition: `independent_aggregate_count_matches_catalog` below
//! binds a SECOND, structurally-independent SPARQL query --
//! `SELECT (COUNT(DISTINCT ?b) AS ?n) WHERE { ?b a compat:CognitionBreed }`
//! -- that shares only the class IRI with the enumeration query above and
//! joins on NONE of `breedId`/`breedLabel`/`breedDoc`/`citation`/
//! `breedFamily`. This closes one real, previously-undocumented blind spot:
//! if the enumeration query's property-join silently dropped a breed
//! missing (or misnamed) one of those properties -- which would shrink
//! `55` and `BREED_CATALOG.len()` together, so the
//! existing `full_catalog_row_count_matches_ontology` test above would
//! still pass, both numbers having shrunk in lockstep -- this aggregate,
//! join-free count would not shrink, exposing the divergence. Attempted a
//! stronger fix first: a SHACL total-count constraint (`shapes.ttl` +
//! `ggen graph validate`, entirely outside the Tera/SPARQL rendering path)
//! would have been fully independent of both queries. Confirmed
//! engine-blocked, not merely unattempted: `crates/praxis-graphlaw/src/
//! shacl/model.rs`'s `SHACL_SPARQL_BOUNDARY` is hardcoded `"CORE_ONLY"`,
//! which rejects every `sh:sparql` constraint at load time (the same
//! engine fact `self-monitoring-pack/shapes.ttl` documents finding in round
//! 2) -- SHACL Core alone has no aggregate "N individuals of class X" node
//! shape, so that route is closed to a pack-level pass. This SPARQL
//! aggregate cross-check is the strongest available substitute; it still
//! does not reach the L5 bar of "sufficient evidence on its own," since a
//! bug in the shared class IRI `compat:CognitionBreed` itself (e.g. a typo
//! present in both queries) would still go uncaught by every check in this
//! file.
//!
//! Generated by `wasm4pm-cognition-pack`.

#[path = "../src/w4pm_cognition_catalog.rs"]
mod w4pm_cognition_catalog;
#[path = "../src/w4pm_cognition_dispatch_handler.rs"]
mod w4pm_cognition_dispatch_handler;
#[path = "../src/w4pm_cognition_dispatch.rs"]
mod w4pm_cognition_dispatch;

use w4pm_cognition_catalog::{from_breed_id, CognitionBreedId, BREED_CATALOG};

#[test]
fn full_catalog_row_count_matches_ontology() {
    assert_eq!(BREED_CATALOG.len(), 55);
}

#[test]
fn independent_aggregate_count_matches_catalog() {
    // See the module-level doc comment: this query is join-free (no
    // breedId/breedLabel/breedDoc/citation/breedFamily), so it cannot fail
    // for the same reason the enumeration query above could.
    assert_eq!(BREED_CATALOG.len(), 55);
}

#[test]
fn full_row_abductive_ibe_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AbductiveIbe)
        .expect("AbductiveIbe must be in BREED_CATALOG");
    assert_eq!(entry.label, "AbductiveIbe");
    assert_eq!(entry.citation, "Harman, G. H. (1965). The Inference to the Best Explanation. The Philosophical Review, 74(1), 88–95. Thagard, P. R. (1978). The Best Explanation: Criteria for Theory Choice. The Journal of Philosophy, 75(2), 76–92.");
    assert_eq!(CognitionBreedId::AbductiveIbe.as_str(), "abductive_ibe");
    assert_eq!(from_breed_id("abductive_ibe"), Some(CognitionBreedId::AbductiveIbe));
}

#[test]
fn full_row_abductive_lp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AbductiveLp)
        .expect("AbductiveLp must be in BREED_CATALOG");
    assert_eq!(entry.label, "AbductiveLp");
    assert_eq!(entry.citation, "Kakas, A. C., Kowalski, R. A., & Toni, F. (1992). Abductive Logic Programming. Journal of Logic and Computation, 2(6), 719–770.");
    assert_eq!(CognitionBreedId::AbductiveLp.as_str(), "abductive_lp");
    assert_eq!(from_breed_id("abductive_lp"), Some(CognitionBreedId::AbductiveLp));
}

#[test]
fn full_row_act_r_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::ActR)
        .expect("ActR must be in BREED_CATALOG");
    assert_eq!(entry.label, "ActR");
    assert_eq!(entry.citation, "Anderson, J. R., & Lebiere, C. (1998). Lawrence Erlbaum Associates. Chapter 3 (the activation equation A_i = B_i + Σ_j W_j·S_ji) and Chapter 9 (cognitive arithmetic: retrieval of addition facts).");
    assert_eq!(CognitionBreedId::ActR.as_str(), "act_r");
    assert_eq!(from_breed_id("act_r"), Some(CognitionBreedId::ActR));
}

#[test]
fn full_row_allen_temporal_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AllenTemporal)
        .expect("AllenTemporal must be in BREED_CATALOG");
    assert_eq!(entry.label, "AllenTemporal");
    assert_eq!(entry.citation, "Allen, J. F. (1983). Maintaining Knowledge about Temporal Intervals. Communications of the ACM, 26(11), 832-843.");
    assert_eq!(CognitionBreedId::AllenTemporal.as_str(), "allen_temporal");
    assert_eq!(from_breed_id("allen_temporal"), Some(CognitionBreedId::AllenTemporal));
}

#[test]
fn full_row_analogy_sme_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AnalogySme)
        .expect("AnalogySme must be in BREED_CATALOG");
    assert_eq!(entry.label, "AnalogySme");
    assert_eq!(entry.citation, "Falkenhainer, B., Forbus, K. D., & Gentner, D. (1989). Artificial Intelligence, 41(1), 1-63.");
    assert_eq!(CognitionBreedId::AnalogySme.as_str(), "analogy_sme");
    assert_eq!(from_breed_id("analogy_sme"), Some(CognitionBreedId::AnalogySme));
}

#[test]
fn full_row_asp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Asp)
        .expect("Asp must be in BREED_CATALOG");
    assert_eq!(entry.label, "Asp");
    assert_eq!(entry.citation, "Gelfond, M., & Lifschitz, V. (1988). The Stable Model Semantics for Logic Programming. In: Proceedings of the Fifth International Conference and Symposium on Logic Programming (ICLP/SLP 1988), MIT Press, pp. 1070–1080.");
    assert_eq!(CognitionBreedId::Asp.as_str(), "asp");
    assert_eq!(from_breed_id("asp"), Some(CognitionBreedId::Asp));
}

#[test]
fn full_row_autoinstinct_learning_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AutoinstinctLearning)
        .expect("AutoinstinctLearning must be in BREED_CATALOG");
    assert_eq!(entry.label, "AutoinstinctLearning");
    assert_eq!(entry.citation, "Sussman, Gerald Jay. \"A Computational Model of Skill Acquisition.\" MIT Artificial Intelligence Laboratory Technical Report AI TR-297, August 1973. Thesis Supervisor: Seymour A. Papert.");
    assert_eq!(CognitionBreedId::AutoinstinctLearning.as_str(), "autoinstinct_learning");
    assert_eq!(from_breed_id("autoinstinct_learning"), Some(CognitionBreedId::AutoinstinctLearning));
}

#[test]
fn full_row_autoinstinct_neurosis_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AutoinstinctNeurosis)
        .expect("AutoinstinctNeurosis must be in BREED_CATALOG");
    assert_eq!(entry.label, "AutoinstinctNeurosis");
    assert_eq!(entry.citation, "Boden, M. A. (1977). Artificial Intelligence and Natural Man. New York: Basic Books. Chapter 6: \"Programs That Model the Mind.\" [Conflict detection framework: neurosis as simultaneous maintenance of mutually incompatible beliefs, pp. 198–212.]");
    assert_eq!(CognitionBreedId::AutoinstinctNeurosis.as_str(), "autoinstinct_neurosis");
    assert_eq!(from_breed_id("autoinstinct_neurosis"), Some(CognitionBreedId::AutoinstinctNeurosis));
}

#[test]
fn full_row_autoinstinct_semantics_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AutoinstinctSemantics)
        .expect("AutoinstinctSemantics must be in BREED_CATALOG");
    assert_eq!(entry.label, "AutoinstinctSemantics");
    assert_eq!(entry.citation, "Schank, R. C. (1972). Conceptual dependency: A theory of natural language understanding. Cognitive Psychology, 3(4), 552–631. https://doi.org/10.1016/0010-0285(72)90022-9");
    assert_eq!(CognitionBreedId::AutoinstinctSemantics.as_str(), "autoinstinct_semantics");
    assert_eq!(from_breed_id("autoinstinct_semantics"), Some(CognitionBreedId::AutoinstinctSemantics));
}

#[test]
fn full_row_autoinstinct_vision_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::AutoinstinctVision)
        .expect("AutoinstinctVision must be in BREED_CATALOG");
    assert_eq!(entry.label, "AutoinstinctVision");
    assert_eq!(entry.citation, "Marr, D., & Poggio, T. (1976). Cooperative computation of stereo disparity. Science, 194(4262), 283–287. https://doi.org/10.1126/science.968816");
    assert_eq!(CognitionBreedId::AutoinstinctVision.as_str(), "autoinstinct_vision");
    assert_eq!(from_breed_id("autoinstinct_vision"), Some(CognitionBreedId::AutoinstinctVision));
}

#[test]
fn full_row_bayesian_network_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::BayesianNetwork)
        .expect("BayesianNetwork must be in BREED_CATALOG");
    assert_eq!(entry.label, "BayesianNetwork");
    assert_eq!(entry.citation, "Pearl, J. (1988). Probabilistic Reasoning in Intelligent Systems: Networks of Plausible Inference. Morgan Kaufmann.");
    assert_eq!(CognitionBreedId::BayesianNetwork.as_str(), "bayesian_network");
    assert_eq!(from_breed_id("bayesian_network"), Some(CognitionBreedId::BayesianNetwork));
}

#[test]
fn full_row_belief_merging_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::BeliefMerging)
        .expect("BeliefMerging must be in BREED_CATALOG");
    assert_eq!(entry.label, "BeliefMerging");
    assert_eq!(entry.citation, "Konieczny, S., & Pino Pérez, R. (2002). Merging Information Under Constraints: A Logical Framework. Journal of Logic and Computation, 12(5), 773–808.");
    assert_eq!(CognitionBreedId::BeliefMerging.as_str(), "belief_merging");
    assert_eq!(from_breed_id("belief_merging"), Some(CognitionBreedId::BeliefMerging));
}

#[test]
fn full_row_cbr_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Cbr)
        .expect("Cbr must be in BREED_CATALOG");
    assert_eq!(entry.label, "Cbr");
    assert_eq!(entry.citation, "A. Aamodt, E. Plaza (1994). Case-Based Reasoning: Foundational Issues, Methodological Variations, and System Approaches. AI Communications, IOS Press, Vol. 7, No. 1, pp. 39–59.");
    assert_eq!(CognitionBreedId::Cbr.as_str(), "cbr");
    assert_eq!(from_breed_id("cbr"), Some(CognitionBreedId::Cbr));
}

#[test]
fn full_row_circumscription_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Circumscription)
        .expect("Circumscription must be in BREED_CATALOG");
    assert_eq!(entry.label, "Circumscription");
    assert_eq!(entry.citation, "McCarthy, J. (1980). Artificial Intelligence, 13(1-2), 27-39.");
    assert_eq!(CognitionBreedId::Circumscription.as_str(), "circumscription");
    assert_eq!(from_breed_id("circumscription"), Some(CognitionBreedId::Circumscription));
}

#[test]
fn full_row_clp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Clp)
        .expect("Clp must be in BREED_CATALOG");
    assert_eq!(entry.label, "Clp");
    assert_eq!(entry.citation, "Jaffar, J., & Lassez, J.-L. (1987). Constraint Logic Programming. In: Proceedings of the 14th ACM SIGACT-SIGPLAN Symposium on Principles of Programming Languages (POPL 1987), pp. 111–119.");
    assert_eq!(CognitionBreedId::Clp.as_str(), "clp");
    assert_eq!(from_breed_id("clp"), Some(CognitionBreedId::Clp));
}

#[test]
fn full_row_construction_grammar_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::ConstructionGrammar)
        .expect("ConstructionGrammar must be in BREED_CATALOG");
    assert_eq!(entry.label, "ConstructionGrammar");
    assert_eq!(entry.citation, "Adele E. Goldberg (1995). Constructions: A Construction Grammar Approach to Argument Structure. University of Chicago Press.");
    assert_eq!(CognitionBreedId::ConstructionGrammar.as_str(), "construction_grammar");
    assert_eq!(from_breed_id("construction_grammar"), Some(CognitionBreedId::ConstructionGrammar));
}

#[test]
fn full_row_contingent_plan_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::ContingentPlan)
        .expect("ContingentPlan must be in BREED_CATALOG");
    assert_eq!(entry.label, "ContingentPlan");
    assert_eq!(entry.citation, "Stuart Russell and Peter Norvig (2010). Artificial Intelligence: A Modern Approach (3rd ed.). Pearson.");
    assert_eq!(CognitionBreedId::ContingentPlan.as_str(), "contingent_plan");
    assert_eq!(from_breed_id("contingent_plan"), Some(CognitionBreedId::ContingentPlan));
}

#[test]
fn full_row_csp_ac3_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::CspAc3)
        .expect("CspAc3 must be in BREED_CATALOG");
    assert_eq!(entry.label, "CspAc3");
    assert_eq!(entry.citation, "Mackworth, A. K. (1977). Consistency in Networks of Relations. Artificial Intelligence, 8(1), 99-118.");
    assert_eq!(CognitionBreedId::CspAc3.as_str(), "csp_ac3");
    assert_eq!(from_breed_id("csp_ac3"), Some(CognitionBreedId::CspAc3));
}

#[test]
fn full_row_ctl_check_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::CtlCheck)
        .expect("CtlCheck must be in BREED_CATALOG");
    assert_eq!(entry.label, "CtlCheck");
    assert_eq!(entry.citation, "Clarke, E. M., Emerson, E. A., & Sistla, A. P. (1986). ACM Transactions on Programming Languages and Systems, 8(2), 244-263.");
    assert_eq!(CognitionBreedId::CtlCheck.as_str(), "ctl_check");
    assert_eq!(from_breed_id("ctl_check"), Some(CognitionBreedId::CtlCheck));
}

#[test]
fn full_row_default_logic_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::DefaultLogic)
        .expect("DefaultLogic must be in BREED_CATALOG");
    assert_eq!(entry.label, "DefaultLogic");
    assert_eq!(entry.citation, "Reiter, R. (1980). A Logic for Default Reasoning. Artificial Intelligence, 13(1-2), 81-132.");
    assert_eq!(CognitionBreedId::DefaultLogic.as_str(), "default_logic");
    assert_eq!(from_breed_id("default_logic"), Some(CognitionBreedId::DefaultLogic));
}

#[test]
fn full_row_dempster_shafer_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::DempsterShafer)
        .expect("DempsterShafer must be in BREED_CATALOG");
    assert_eq!(entry.label, "DempsterShafer");
    assert_eq!(entry.citation, "Shafer, G. (1976). A Mathematical Theory of Evidence. Princeton University Press.");
    assert_eq!(CognitionBreedId::DempsterShafer.as_str(), "dempster_shafer");
    assert_eq!(from_breed_id("dempster_shafer"), Some(CognitionBreedId::DempsterShafer));
}

#[test]
fn full_row_dendral_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Dendral)
        .expect("Dendral must be in BREED_CATALOG");
    assert_eq!(entry.label, "Dendral");
    assert_eq!(entry.citation, "Feigenbaum, E. A., Buchanan, B. G., & Lederberg, J. (1971). On generality and problem solving: A case study using the DENDRAL program. Stanford Artificial Intelligence Project Memo AIM-131, Computer Science Department Report CS176. Stanford University.");
    assert_eq!(CognitionBreedId::Dendral.as_str(), "dendral");
    assert_eq!(from_breed_id("dendral"), Some(CognitionBreedId::Dendral));
}

#[test]
fn full_row_description_logic_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::DescriptionLogic)
        .expect("DescriptionLogic must be in BREED_CATALOG");
    assert_eq!(entry.label, "DescriptionLogic");
    assert_eq!(entry.citation, "Baader, F., Brandt, S., & Lutz, C. (2005). Pushing the EL Envelope. In: Proceedings of the 19th International Joint Conference on Artificial Intelligence (IJCAI 2005), pp. 364–369.");
    assert_eq!(CognitionBreedId::DescriptionLogic.as_str(), "description_logic");
    assert_eq!(from_breed_id("description_logic"), Some(CognitionBreedId::DescriptionLogic));
}

#[test]
fn full_row_ebl_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Ebl)
        .expect("Ebl must be in BREED_CATALOG");
    assert_eq!(entry.label, "Ebl");
    assert_eq!(entry.citation, "Mitchell, T. M., Keller, R. M., & Kedar-Cabelli, S. T. (1986). Explanation-Based Generalization: A Unifying View. Machine Learning, 1(1), 47-80.");
    assert_eq!(CognitionBreedId::Ebl.as_str(), "ebl");
    assert_eq!(from_breed_id("ebl"), Some(CognitionBreedId::Ebl));
}

#[test]
fn full_row_eliza_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Eliza)
        .expect("Eliza must be in BREED_CATALOG");
    assert_eq!(entry.label, "Eliza");
    assert_eq!(entry.citation, "Weizenbaum, J. (1966). ELIZA—A computer program for the study of natural language communication between man and machine. Communications of the ACM, 9(1), 36–45. https://doi.org/10.1145/365153.365168");
    assert_eq!(CognitionBreedId::Eliza.as_str(), "eliza");
    assert_eq!(from_breed_id("eliza"), Some(CognitionBreedId::Eliza));
}

#[test]
fn full_row_episodic_memory_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::EpisodicMemory)
        .expect("EpisodicMemory must be in BREED_CATALOG");
    assert_eq!(entry.label, "EpisodicMemory");
    assert_eq!(entry.citation, "Tulving, E. (1983). Oxford University Press (Ch. 7: encoding specificity and temporal organisation). Nuxoll, A. M., & Laird, J. E. (2007). Proceedings of AAAI 2007, 1560-1565 (cue-based retrieval of the best partially-matching episode).");
    assert_eq!(CognitionBreedId::EpisodicMemory.as_str(), "episodic_memory");
    assert_eq!(from_breed_id("episodic_memory"), Some(CognitionBreedId::EpisodicMemory));
}

#[test]
fn full_row_event_calculus_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::EventCalculus)
        .expect("EventCalculus must be in BREED_CATALOG");
    assert_eq!(entry.label, "EventCalculus");
    assert_eq!(entry.citation, "Kowalski, R., & Sergot, M. (1986). A Logic-based Calculus of Events. New Generation Computing, 4(1), 67–95.");
    assert_eq!(CognitionBreedId::EventCalculus.as_str(), "event_calculus");
    assert_eq!(from_breed_id("event_calculus"), Some(CognitionBreedId::EventCalculus));
}

#[test]
fn full_row_frames_inheritance_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::FramesInheritance)
        .expect("FramesInheritance must be in BREED_CATALOG");
    assert_eq!(entry.label, "FramesInheritance");
    assert_eq!(entry.citation, "Minsky, M. (1974). A Framework for Representing Knowledge. MIT AI Laboratory Memo 306. Reprinted in Winston (Ed.), The Psychology of Computer Vision, 1975.");
    assert_eq!(CognitionBreedId::FramesInheritance.as_str(), "frames_inheritance");
    assert_eq!(from_breed_id("frames_inheritance"), Some(CognitionBreedId::FramesInheritance));
}

#[test]
fn full_row_fuzzy_logic_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::FuzzyLogic)
        .expect("FuzzyLogic must be in BREED_CATALOG");
    assert_eq!(entry.label, "FuzzyLogic");
    assert_eq!(entry.citation, "Mamdani, E. H., & Assilian, S. (1975). An Experiment in Linguistic Synthesis with a Fuzzy Logic Controller. International Journal of Man-Machine Studies, 7(1), 1-13.");
    assert_eq!(CognitionBreedId::FuzzyLogic.as_str(), "fuzzy_logic");
    assert_eq!(from_breed_id("fuzzy_logic"), Some(CognitionBreedId::FuzzyLogic));
}

#[test]
fn full_row_gps_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Gps)
        .expect("Gps must be in BREED_CATALOG");
    assert_eq!(entry.label, "Gps");
    assert_eq!(entry.citation, "A. Newell and H. A. Simon, \"GPS, A Program That Simulates Human Thought,\" RAND Corporation, P-2257, March 30, 1961 (Revised April 10, 1961). Presented at the Conference on Learning Automata, Karlsruhe, Germany, April 11–14, 1961.");
    assert_eq!(CognitionBreedId::Gps.as_str(), "gps");
    assert_eq!(from_breed_id("gps"), Some(CognitionBreedId::Gps));
}

#[test]
fn full_row_hearsay_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Hearsay)
        .expect("Hearsay must be in BREED_CATALOG");
    assert_eq!(entry.label, "Hearsay");
    assert_eq!(entry.citation, "Erman, L. D., Hayes-Roth, F., Lesser, V. R., and Reddy, D. R. (1980). The Hearsay-II speech-understanding system: Integrating knowledge to resolve uncertainty. ACM Computing Surveys, 12(2), 213–253.");
    assert_eq!(CognitionBreedId::Hearsay.as_str(), "hearsay");
    assert_eq!(from_breed_id("hearsay"), Some(CognitionBreedId::Hearsay));
}

#[test]
fn full_row_htn_planning_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::HtnPlanning)
        .expect("HtnPlanning must be in BREED_CATALOG");
    assert_eq!(entry.label, "HtnPlanning");
    assert_eq!(entry.citation, "Nau, D., Au, T.-C., Ilghami, O., Kuter, U., Murdock, J. W., Wu, D., & Yaman, F. (2003). SHOP2: An HTN Planning System. Journal of Artificial Intelligence Research, 20, 379-404.");
    assert_eq!(CognitionBreedId::HtnPlanning.as_str(), "htn_planning");
    assert_eq!(from_breed_id("htn_planning"), Some(CognitionBreedId::HtnPlanning));
}

#[test]
fn full_row_ilp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Ilp)
        .expect("Ilp must be in BREED_CATALOG");
    assert_eq!(entry.label, "Ilp");
    assert_eq!(entry.citation, "Quinlan, J. R. (1990). Machine Learning, 5(3), 239-266.");
    assert_eq!(CognitionBreedId::Ilp.as_str(), "ilp");
    assert_eq!(from_breed_id("ilp"), Some(CognitionBreedId::Ilp));
}

#[test]
fn full_row_ltl_monitor_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::LtlMonitor)
        .expect("LtlMonitor must be in BREED_CATALOG");
    assert_eq!(entry.label, "LtlMonitor");
    assert_eq!(entry.citation, "Havelund, K., & Rosu, G. (2001). Monitoring Programs Using Rewriting. Proceedings of ASE 2001 (16th IEEE International Conference on Automated Software Engineering), 135-143.");
    assert_eq!(CognitionBreedId::LtlMonitor.as_str(), "ltl_monitor");
    assert_eq!(from_breed_id("ltl_monitor"), Some(CognitionBreedId::LtlMonitor));
}

#[test]
fn full_row_markov_logic_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::MarkovLogic)
        .expect("MarkovLogic must be in BREED_CATALOG");
    assert_eq!(entry.label, "MarkovLogic");
    assert_eq!(entry.citation, "Matthew Richardson and Pedro Domingos (2006). Markov logic networks. Machine Learning 62(1-2):107-136.");
    assert_eq!(CognitionBreedId::MarkovLogic.as_str(), "markov_logic");
    assert_eq!(from_breed_id("markov_logic"), Some(CognitionBreedId::MarkovLogic));
}

#[test]
fn full_row_mdp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Mdp)
        .expect("Mdp must be in BREED_CATALOG");
    assert_eq!(entry.label, "Mdp");
    assert_eq!(entry.citation, "Bellman, R. (1957). Dynamic Programming. Princeton University Press. (Functional equation / principle of optimality, Chapter III; successive-approximation solution, Chapter IV.)");
    assert_eq!(CognitionBreedId::Mdp.as_str(), "mdp");
    assert_eq!(from_breed_id("mdp"), Some(CognitionBreedId::Mdp));
}

#[test]
fn full_row_meta_reasoning_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::MetaReasoning)
        .expect("MetaReasoning must be in BREED_CATALOG");
    assert_eq!(entry.label, "MetaReasoning");
    assert_eq!(entry.citation, "Michael T. Cox and Anita Raja (eds.) (2011). Metareasoning: Thinking about Thinking. MIT Press.");
    assert_eq!(CognitionBreedId::MetaReasoning.as_str(), "meta_reasoning");
    assert_eq!(from_breed_id("meta_reasoning"), Some(CognitionBreedId::MetaReasoning));
}

#[test]
fn full_row_morphological_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Morphological)
        .expect("Morphological must be in BREED_CATALOG");
    assert_eq!(entry.label, "Morphological");
    assert_eq!(entry.citation, "Zwicky, F. (1969). Discovery, Invention, Research Through the Morphological Approach. Macmillan.");
    assert_eq!(CognitionBreedId::Morphological.as_str(), "morphological");
    assert_eq!(from_breed_id("morphological"), Some(CognitionBreedId::Morphological));
}

#[test]
fn full_row_mycin_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Mycin)
        .expect("Mycin must be in BREED_CATALOG");
    assert_eq!(entry.label, "Mycin");
    assert_eq!(entry.citation, "Shortliffe, E. H., & Buchanan, B. G. (1975). A model of inexact reasoning in medicine. Mathematical Biosciences, 23(3–4), 351–379. Reprinted as Chapter 11 in: Buchanan, B. G., & Shortliffe, E. H. (Eds.), Rule-Based Expert Systems. Addison-Wesley, 1984.");
    assert_eq!(CognitionBreedId::Mycin.as_str(), "mycin");
    assert_eq!(from_breed_id("mycin"), Some(CognitionBreedId::Mycin));
}

#[test]
fn full_row_naive_physics_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::NaivePhysics)
        .expect("NaivePhysics must be in BREED_CATALOG");
    assert_eq!(entry.label, "NaivePhysics");
    assert_eq!(entry.citation, "Hayes, P. J. (1979). In D. Michie (Ed.), Expert Systems in the Micro-Electronic Age. Edinburgh University Press. Hayes, P. J. (1985). In J. R. Hobbs & R. C. Moore (Eds.), Formal Theories of the Commonsense World (pp. 71-107). Ablex.");
    assert_eq!(CognitionBreedId::NaivePhysics.as_str(), "naive_physics");
    assert_eq!(from_breed_id("naive_physics"), Some(CognitionBreedId::NaivePhysics));
}

#[test]
fn full_row_ocpm_route_discoverer_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::OcpmRouteDiscoverer)
        .expect("OcpmRouteDiscoverer must be in BREED_CATALOG");
    assert_eq!(entry.label, "OcpmRouteDiscoverer");
    assert_eq!(entry.citation, "van der Aalst, W.M.P. (2019). Object-Centric Process Mining: Dealing with Divergence and Convergence.");
    assert_eq!(CognitionBreedId::OcpmRouteDiscoverer.as_str(), "ocpm_route_discoverer");
    assert_eq!(from_breed_id("ocpm_route_discoverer"), Some(CognitionBreedId::OcpmRouteDiscoverer));
}

#[test]
fn full_row_partial_order_plan_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::PartialOrderPlan)
        .expect("PartialOrderPlan must be in BREED_CATALOG");
    assert_eq!(entry.label, "PartialOrderPlan");
    assert_eq!(entry.citation, "McAllester, D., & Rosenblitt, D. (1991). Systematic Nonlinear Planning. In: Proceedings of the Ninth National Conference on Artificial Intelligence (AAAI-91), pp. 634–639.");
    assert_eq!(CognitionBreedId::PartialOrderPlan.as_str(), "partial_order_plan");
    assert_eq!(from_breed_id("partial_order_plan"), Some(CognitionBreedId::PartialOrderPlan));
}

#[test]
fn full_row_pomdp_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Pomdp)
        .expect("Pomdp must be in BREED_CATALOG");
    assert_eq!(entry.label, "Pomdp");
    assert_eq!(entry.citation, "Leslie Pack Kaelbling, Michael L. Littman and Anthony R. Cassandra (1998). Planning and acting in partially observable stochastic domains. Artificial Intelligence 101(1-2):99-134.");
    assert_eq!(CognitionBreedId::Pomdp.as_str(), "pomdp");
    assert_eq!(from_breed_id("pomdp"), Some(CognitionBreedId::Pomdp));
}

#[test]
fn full_row_problog_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Problog)
        .expect("Problog must be in BREED_CATALOG");
    assert_eq!(entry.label, "Problog");
    assert_eq!(entry.citation, "De Raedt, L., Kimmig, A., & Toivonen, H. (2007). Proceedings of IJCAI 2007, 2468-2473.");
    assert_eq!(CognitionBreedId::Problog.as_str(), "problog");
    assert_eq!(from_breed_id("problog"), Some(CognitionBreedId::Problog));
}

#[test]
fn full_row_prolog_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Prolog)
        .expect("Prolog must be in BREED_CATALOG");
    assert_eq!(entry.label, "Prolog");
    assert_eq!(entry.citation, "Kowalski, R. A. (1974). Predicate logic as programming language. IFIP Congress 74, Stockholm, pp. 569–574.");
    assert_eq!(CognitionBreedId::Prolog.as_str(), "prolog");
    assert_eq!(from_breed_id("prolog"), Some(CognitionBreedId::Prolog));
}

#[test]
fn full_row_qualitative_reason_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::QualitativeReason)
        .expect("QualitativeReason must be in BREED_CATALOG");
    assert_eq!(entry.label, "QualitativeReason");
    assert_eq!(entry.citation, "de Kleer, J., & Brown, J. S. (1984). A Qualitative Physics Based on Confluences. Artificial Intelligence, 24(1–3), 7–83.");
    assert_eq!(CognitionBreedId::QualitativeReason.as_str(), "qualitative_reason");
    assert_eq!(from_breed_id("qualitative_reason"), Some(CognitionBreedId::QualitativeReason));
}

#[test]
fn full_row_rl_symbolic_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::RlSymbolic)
        .expect("RlSymbolic must be in BREED_CATALOG");
    assert_eq!(entry.label, "RlSymbolic");
    assert_eq!(entry.citation, "Watkins, C. J. C. H., & Dayan, P. (1992). Machine Learning, 8(3-4), 279-292.");
    assert_eq!(CognitionBreedId::RlSymbolic.as_str(), "rl_symbolic");
    assert_eq!(from_breed_id("rl_symbolic"), Some(CognitionBreedId::RlSymbolic));
}

#[test]
fn full_row_sat_cdcl_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::SatCdcl)
        .expect("SatCdcl must be in BREED_CATALOG");
    assert_eq!(entry.label, "SatCdcl");
    assert_eq!(entry.citation, "Marques-Silva, J. P., & Sakallah, K. A. (1999). IEEE Transactions on Computers, 48(5), 506-521.");
    assert_eq!(CognitionBreedId::SatCdcl.as_str(), "sat_cdcl");
    assert_eq!(from_breed_id("sat_cdcl"), Some(CognitionBreedId::SatCdcl));
}

#[test]
fn full_row_script_sam_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::ScriptSam)
        .expect("ScriptSam must be in BREED_CATALOG");
    assert_eq!(entry.label, "ScriptSam");
    assert_eq!(entry.citation, "Schank, R. C., & Abelson, R. P. (1977). Scripts, Plans, Goals and Understanding: An Inquiry into Human Knowledge Structures. Lawrence Erlbaum Associates.");
    assert_eq!(CognitionBreedId::ScriptSam.as_str(), "script_sam");
    assert_eq!(from_breed_id("script_sam"), Some(CognitionBreedId::ScriptSam));
}

#[test]
fn full_row_situation_calculus_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::SituationCalculus)
        .expect("SituationCalculus must be in BREED_CATALOG");
    assert_eq!(entry.label, "SituationCalculus");
    assert_eq!(entry.citation, "Reiter, R. (1991). In V. Lifschitz (Ed.), Artificial Intelligence and Mathematical Theory of Computation: Papers in Honor of John McCarthy (pp. 359-380). Academic Press.");
    assert_eq!(CognitionBreedId::SituationCalculus.as_str(), "situation_calculus");
    assert_eq!(from_breed_id("situation_calculus"), Some(CognitionBreedId::SituationCalculus));
}

#[test]
fn full_row_soar_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Soar)
        .expect("Soar must be in BREED_CATALOG");
    assert_eq!(entry.label, "Soar");
    assert_eq!(entry.citation, "Laird, J. E., Newell, A., & Rosenbloom, P. S. (1987). Soar: An architecture for general intelligence. Artificial Intelligence, 33(1), 1–64. https://doi.org/10.1016/0004-3702(87)90050-6");
    assert_eq!(CognitionBreedId::Soar.as_str(), "soar");
    assert_eq!(from_breed_id("soar"), Some(CognitionBreedId::Soar));
}

#[test]
fn full_row_strips_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Strips)
        .expect("Strips must be in BREED_CATALOG");
    assert_eq!(entry.label, "Strips");
    assert_eq!(entry.citation, "Fikes, R. E., & Nilsson, N. J. (1971). STRIPS: A new approach to the application of theorem proving to problem solving. Artificial Intelligence, 2(3–4), 189–208.");
    assert_eq!(CognitionBreedId::Strips.as_str(), "strips");
    assert_eq!(from_breed_id("strips"), Some(CognitionBreedId::Strips));
}

#[test]
fn full_row_tableaux_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Tableaux)
        .expect("Tableaux must be in BREED_CATALOG");
    assert_eq!(entry.label, "Tableaux");
    assert_eq!(entry.citation, "Raymond M. Smullyan (1968). First-Order Logic. Springer-Verlag, Ergebnisse der Mathematik und ihrer Grenzgebiete 43.");
    assert_eq!(CognitionBreedId::Tableaux.as_str(), "tableaux");
    assert_eq!(from_breed_id("tableaux"), Some(CognitionBreedId::Tableaux));
}

#[test]
fn full_row_triz_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::Triz)
        .expect("Triz must be in BREED_CATALOG");
    assert_eq!(entry.label, "Triz");
    assert_eq!(entry.citation, "Altshuller, G. (1984). Creativity as an Exact Science. Gordon and Breach Science Publishers.");
    assert_eq!(CognitionBreedId::Triz.as_str(), "triz");
    assert_eq!(from_breed_id("triz"), Some(CognitionBreedId::Triz));
}

#[test]
fn full_row_version_space_matches_ontology() {
    let entry = BREED_CATALOG
        .iter()
        .find(|b| b.id == CognitionBreedId::VersionSpace)
        .expect("VersionSpace must be in BREED_CATALOG");
    assert_eq!(entry.label, "VersionSpace");
    assert_eq!(entry.citation, "Mitchell, T. M. (1982). Generalization as Search. Artificial Intelligence, 18(2), 203–226.");
    assert_eq!(CognitionBreedId::VersionSpace.as_str(), "version_space");
    assert_eq!(from_breed_id("version_space"), Some(CognitionBreedId::VersionSpace));
}


