//! Compile-time and behavioral proof for `wasm4pm-compat-pack`'s generated
//! OCEL emission surface (`src/wasm4pm_compat_events.rs`).
//!
//! GENERATED by `wasm4pm-compat-pack` -- but unlike `events.rs.tmpl`/
//! `emission_boundary.md.tmpl`, this file carries NO `sparql:` frontmatter
//! and loops over NO ontology query. Every expected literal below was
//! hand-transcribed directly from `packs/wasm4pm-compat-pack/ontology.ttl`'s
//! three `w4pm:EventType` individuals, independently of the SPARQL
//! `event_types` query that generated the enum/emit-fns under test. Looping
//! that same query into this test's "expected" values too would make a
//! wrong `eventName`/`objectType` literal, or a broken `pascal_case`/
//! `snake_case` filter, corrupt the generated code and this test's
//! expectations identically -- the test could never catch it. Hardcoding
//! breaks that coupling.

#[path = "../src/wasm4pm_compat_events.rs"]
mod wasm4pm_compat_events;

use chrono::DateTime;
use wasm4pm_compat::ocel::{OCELEvent, OCELRelationship};
use wasm4pm_compat_events::EmittedEventType;

fn literal_time() -> chrono::DateTime<chrono::FixedOffset> {
    DateTime::parse_from_rfc3339("2026-07-17T00:00:00+00:00")
        .expect("literal RFC 3339 timestamp must parse")
}

/// Structural proof: an exhaustive match with NO wildcard arm. If a future
/// ontology edit adds, removes, or renames a `w4pm:EventType` individual,
/// `events.rs.tmpl` regenerates a differently-shaped `EmittedEventType` enum
/// and this `match` fails to compile until this test is updated to match --
/// an independent (non-SPARQL) proof of exact cardinality: exactly the 3
/// individuals currently in the ontology (`GraphUnionHashed`,
/// `PackLockVerified`, `ReceiptChained`), no more, no fewer.
#[test]
fn emitted_event_type_has_exactly_the_three_ontology_variants() {
    let all = [
        EmittedEventType::GraphUnionHashed,
        EmittedEventType::PackLockVerified,
        EmittedEventType::ReceiptChained,
    ];
    for variant in all {
        let expected_name = match variant {
            EmittedEventType::GraphUnionHashed => "graph_union_hashed",
            EmittedEventType::PackLockVerified => "pack_lock_verified",
            EmittedEventType::ReceiptChained => "receipt_chained",
        };
        assert_eq!(variant.name(), expected_name);
    }
}

/// Direct literal check of `EmittedEventType::name()` against the
/// `w4pm:eventName` values transcribed from `ontology.ttl`.
#[test]
fn emitted_event_type_name_matches_ontology_event_name_literals() {
    assert_eq!(
        EmittedEventType::GraphUnionHashed.name(),
        "graph_union_hashed"
    );
    assert_eq!(
        EmittedEventType::PackLockVerified.name(),
        "pack_lock_verified"
    );
    assert_eq!(EmittedEventType::ReceiptChained.name(), "receipt_chained");
}

/// Behavioral proof: call the real generated `emit_graph_union_hashed` with
/// concrete literal inputs and assert on the concrete literal fields of the
/// real `OCELEvent` it returns. `w4pm:GraphUnionHashed`'s `w4pm:objectType`
/// is the literal `"OntologyGraph"` per the ontology.
#[test]
fn emit_graph_union_hashed_binds_ontology_graph_relationship() {
    let event = wasm4pm_compat_events::emit_graph_union_hashed(
        "evt-1".to_string(),
        literal_time(),
        "graph-abc".to_string(),
    );

    assert_eq!(event.id, "evt-1");
    assert_eq!(event.event_type, "graph_union_hashed");
    assert!(event.attributes.is_empty());
    assert_eq!(event.relationships.len(), 1);
    assert_eq!(
        event.relationships[0],
        OCELRelationship {
            object_id: "graph-abc".to_string(),
            qualifier: "OntologyGraph".to_string(),
        }
    );
}

/// `w4pm:PackLockVerified`'s `w4pm:objectType` is the literal `"Pack"`.
#[test]
fn emit_pack_lock_verified_binds_pack_relationship() {
    let event = wasm4pm_compat_events::emit_pack_lock_verified(
        "evt-2".to_string(),
        literal_time(),
        "pack-99".to_string(),
    );

    assert_eq!(event.id, "evt-2");
    assert_eq!(event.event_type, "pack_lock_verified");
    assert!(event.attributes.is_empty());
    assert_eq!(event.relationships.len(), 1);
    assert_eq!(event.relationships[0].object_id, "pack-99");
    assert_eq!(event.relationships[0].qualifier, "Pack");
}

/// `w4pm:ReceiptChained`'s `w4pm:objectType` is the literal `"SyncReceipt"`.
#[test]
fn emit_receipt_chained_binds_sync_receipt_relationship() {
    let event = wasm4pm_compat_events::emit_receipt_chained(
        "evt-3".to_string(),
        literal_time(),
        "receipt-xyz".to_string(),
    );

    assert_eq!(event.id, "evt-3");
    assert_eq!(event.event_type, "receipt_chained");
    assert!(event.attributes.is_empty());
    assert_eq!(event.relationships.len(), 1);
    assert_eq!(event.relationships[0].object_id, "receipt-xyz");
    assert_eq!(event.relationships[0].qualifier, "SyncReceipt");
}

/// New coverage `events.rs.tmpl`'s own output never exercises: `OCELEvent`
/// is `Serialize`/`Deserialize` (`wasm4pm_compat::ocel`, pinned dependency
/// `=26.6.29` -- `event_type` renames to JSON key `"type"`,
/// `OCELRelationship::object_id` renames to JSON key `"objectId"`). Round-
/// trip one emitted event through JSON and assert on literal substrings
/// plus struct equality after deserialization.
#[test]
fn emitted_pack_lock_verified_event_round_trips_through_json() {
    let event = wasm4pm_compat_events::emit_pack_lock_verified(
        "evt-4".to_string(),
        literal_time(),
        "pack-99".to_string(),
    );

    let json = serde_json::to_string(&event).expect("OCELEvent must serialize");
    assert!(json.contains("\"type\":\"pack_lock_verified\""));
    assert!(json.contains("\"objectId\":\"pack-99\""));
    assert!(json.contains("\"qualifier\":\"Pack\""));

    let round_tripped: OCELEvent =
        serde_json::from_str(&json).expect("OCELEvent must deserialize");
    assert_eq!(round_tripped, event);
}
