//! GALL-001 clean replay verification for the RFC-GPACK portable receipt.
//!
//! Replay is explicit rather than part of ordinary sync. An operator/court
//! first manufactures a portable receipt, then asks this module to clear only
//! managed-write consequences, execute the real sync path again, and compare
//! the second observed semantic subject with the first. Generated bytes from
//! run 1 are never used as the replay oracle.

use std::path::{Component, Path};

use serde::Serialize;
use serde_json::{json, Value};
use sha2::Digest as _;

use crate::{
    error::{AppError, Result},
    portable_receipt::PORTABLE_RECEIPT_REL_PATH,
    sync::{sync, SyncOptions},
};

#[derive(Debug, Clone, Serialize)]
pub struct ReplayReport {
    pub source_receipt_sha256: String,
    pub replayed_receipt_sha256: String,
    pub cleared_consequences: usize,
    pub status: &'static str,
}

fn sha256_prefixed(bytes: &[u8]) -> String {
    format!("sha256:{}", hex::encode(sha2::Sha256::digest(bytes)))
}

fn portable_receipt_path(root: &Path) -> std::path::PathBuf {
    root.join(PORTABLE_RECEIPT_REL_PATH)
}

fn read_receipt(root: &Path) -> Result<(Vec<u8>, Value)> {
    let bytes = std::fs::read(portable_receipt_path(root)).map_err(|e| {
        AppError::fm_chain(
            16,
            format!(
                "GALL-001 replay requires an existing portable receipt: {e}. Remediation: execute a non-dry-run sync before replay."
            ),
        )
    })?;
    let value = serde_json::from_slice(&bytes)?;
    Ok((bytes, value))
}

fn identity_projection(value: &Value) -> Value {
    json!({
        "schema": value.get("schema"),
        "spec": value.get("spec"),
        "engine": value.get("engine"),
        "subject": value.get("subject"),
        "dependencies": value.get("dependencies"),
        "graph": value.get("graph"),
        "admission": value.get("admission"),
        "consequences": value.get("consequences"),
        "standing": value.get("standing"),
    })
}

fn safe_relative_target(target: &str) -> bool {
    let path = Path::new(target);
    !path.is_absolute()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_) | Component::CurDir))
}

fn clear_managed_writes(root: &Path, receipt: &Value) -> Result<usize> {
    let consequences = receipt
        .get("consequences")
        .and_then(Value::as_array)
        .ok_or_else(|| {
            AppError::fm_chain(
                16,
                "GALL-001 portable receipt has no consequences array; replay identity is invalid.",
            )
        })?;

    let mut cleared = 0usize;
    for consequence in consequences {
        let target = consequence
            .get("target")
            .and_then(Value::as_str)
            .ok_or_else(|| {
                AppError::fm_chain(16, "GALL-001 consequence is missing a string target.")
            })?;
        let operation = consequence
            .get("operation")
            .and_then(Value::as_str)
            .ok_or_else(|| {
                AppError::fm_chain(16, "GALL-001 consequence is missing a string operation.")
            })?;

        if !safe_relative_target(target) {
            return Err(AppError::fm_chain(
                16,
                format!("GALL-001 refuses unsafe replay target path {target}."),
            ));
        }

        if operation != "MANAGED_WRITE" {
            return Err(AppError::fm_chain(
                16,
                format!(
                    "GALL-001 clean replay currently supports MANAGED_WRITE only; {target} is {operation}. Refusing rather than destructively reconstructing an injected/manual file."
                ),
            ));
        }

        let path = root.join(target);
        match std::fs::remove_file(&path) {
            Ok(()) => cleared += 1,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(AppError::fm_chain(
                    16,
                    format!("GALL-001 cannot clear replay consequence {target}: {e}"),
                ));
            }
        }
    }
    Ok(cleared)
}

/// Execute the real sync path against a clean managed-output state and bind
/// replay PASS only after the second observed subject is identity-equivalent
/// to the original portable receipt.
///
/// The function refuses injected/manual-file consequences. A safe clean replay
/// for those requires an isolated workspace/copy primitive; deleting an
/// injected target would exceed this court's authority.
pub fn verify_project_replay(root: &Path, opts: SyncOptions) -> Result<ReplayReport> {
    if opts.dry_run {
        return Err(AppError::fm_chain(
            16,
            "GALL-001 replay cannot run with dry_run=true; dry-run has no durable consequence.",
        ));
    }

    let (source_bytes, source) = read_receipt(root)?;
    if source.get("standing").and_then(Value::as_str) != Some("ALIVE") {
        return Err(AppError::fm_chain(
            16,
            format!(
                "GALL-001 replay requires source standing ALIVE; observed {:?}.",
                source.get("standing")
            ),
        ));
    }

    let cleared = clear_managed_writes(root, &source)?;
    sync(root, opts)?;

    let (replayed_bytes, mut replayed) = read_receipt(root)?;
    if identity_projection(&source) != identity_projection(&replayed) {
        return Err(AppError::fm_chain(
            17,
            "GALL-001 replay identity diverged: pack/graph/dependency/admission/consequence subject after clean replay does not equal the source portable receipt.",
        ));
    }

    let source_digest = sha256_prefixed(&source_bytes);
    let replayed_digest = sha256_prefixed(&replayed_bytes);
    replayed["replay"] = json!({
        "status": "PASS",
        "source_receipt_sha256": source_digest,
        "replayed_receipt_sha256": replayed_digest,
        "court": "ggen-engine::replay::verify_project_replay"
    });
    std::fs::write(portable_receipt_path(root), serde_json::to_vec(&replayed)?)?;

    Ok(ReplayReport {
        source_receipt_sha256: source_digest,
        replayed_receipt_sha256: replayed_digest,
        cleared_consequences: cleared,
        status: "PASS",
    })
}
