import Mathlib

set_option autoImplicit false

/-!
# Mazurkiewicz traces

This module defines the independence alphabet, one adjacent commutation step,
and the generated equivalence relation. A derivation records the exact finite
chain of admitted commutations relating two serializations.
-/

namespace CrownFormal

universe u

/-- A symmetric, irreflexive independence relation on occurrences. -/
structure Independence (α : Type u) where
  independent : α → α → Prop
  symmetric : ∀ {a b}, independent a b → independent b a
  irreflexive : ∀ a, ¬ independent a a

namespace Independence

variable {α : Type u}

/-- Dependence is the constructive complement of admitted independence. -/
def dependent (I : Independence α) (a b : α) : Prop :=
  ¬ I.independent a b

end Independence

/-- Equivalence generated by swapping adjacent independent occurrences. -/
inductive TraceEq {α : Type u} (I : Independence α) : List α → List α → Prop
  | refl (word : List α) : TraceEq I word word
  | swap (pre : List α) (a b : α) (suf : List α)
      (independent : I.independent a b) :
      TraceEq I
        (pre ++ [a, b] ++ suf)
        (pre ++ [b, a] ++ suf)
  | symm {left right : List α} :
      TraceEq I left right → TraceEq I right left
  | trans {left middle right : List α} :
      TraceEq I left middle → TraceEq I middle right → TraceEq I left right

namespace TraceEq

variable {α : Type u} {I : Independence α}

/-- Left-context congruence for trace equivalence. -/
theorem prepend (head : List α) {left right : List α}
    (h : TraceEq I left right) :
    TraceEq I (head ++ left) (head ++ right) := by
  induction h with
  | refl word => exact .refl _
  | swap pre a b suf hab =>
      simpa [List.append_assoc] using
        (TraceEq.swap (I := I) (head ++ pre) a b suf hab)
  | symm h ih => exact .symm ih
  | trans h₁ h₂ ih₁ ih₂ => exact .trans ih₁ ih₂

/-- Right-context congruence for trace equivalence. -/
theorem appendTail (tail : List α) {left right : List α}
    (h : TraceEq I left right) :
    TraceEq I (left ++ tail) (right ++ tail) := by
  induction h with
  | refl word => exact .refl _
  | swap pre a b suf hab =>
      simpa [List.append_assoc] using
        (TraceEq.swap (I := I) pre a b (suf ++ tail) hab)
  | symm h ih => exact .symm ih
  | trans h₁ h₂ ih₁ ih₂ => exact .trans ih₁ ih₂

/-- Binary concatenation congruence. -/
theorem append {left₁ right₁ left₂ right₂ : List α}
    (h₁ : TraceEq I left₁ right₁) (h₂ : TraceEq I left₂ right₂) :
    TraceEq I (left₁ ++ left₂) (right₁ ++ right₂) :=
  .trans (h₁.appendTail left₂) (h₂.prepend right₁)

/-- Trace-equivalent words contain the same number of occurrences. -/
theorem length_eq {left right : List α} (h : TraceEq I left right) :
    left.length = right.length := by
  induction h with
  | refl word => rfl
  | swap pre a b suf independent => simp
  | symm h ih => exact ih.symm
  | trans h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Trace equivalence is an equivalence relation. -/
theorem equivalence (I : Independence α) : Equivalence (TraceEq I) :=
  ⟨TraceEq.refl, fun h => TraceEq.symm h, fun h₁ h₂ => TraceEq.trans h₁ h₂⟩

end TraceEq

/-- The complete Mazurkiewicz trace class of one word. -/
def traceLanguage {α : Type u} (I : Independence α) (word : List α) :
    Set (List α) :=
  {candidate | TraceEq I word candidate}

/-- Equality of complete trace languages characterizes trace equivalence. -/
theorem traceLanguage_eq_iff {α : Type u} (I : Independence α)
    (left right : List α) :
    traceLanguage I left = traceLanguage I right ↔ TraceEq I left right := by
  constructor
  · intro h
    have : right ∈ traceLanguage I left := by
      rw [h]
      exact TraceEq.refl right
    exact this
  · intro h
    ext candidate
    constructor
    · intro hc
      exact TraceEq.trans (TraceEq.symm h) hc
    · intro hc
      exact TraceEq.trans h hc

/-- The trace setoid used by the canonical quotient classifier. -/
def traceSetoid {α : Type u} (I : Independence α) : Setoid (List α) where
  r := TraceEq I
  iseqv := TraceEq.equivalence I

/-- Free partially commutative words over `I`. -/
abbrev TraceClass {α : Type u} (I : Independence α) :=
  Quotient (traceSetoid I)

/-- Canonical quotient classifier. -/
def classify {α : Type u} (I : Independence α) (word : List α) : TraceClass I :=
  Quotient.mk (traceSetoid I) word

/-- The quotient kernel is exactly trace equivalence. -/
theorem classify_eq_iff {α : Type u} (I : Independence α)
    (left right : List α) :
    classify I left = classify I right ↔ TraceEq I left right := by
  constructor
  · exact Quotient.exact
  · exact Quotient.sound

end CrownFormal
