//! Chicago-TDD behavioral tests over the ontology-generated command reference
//! (`ggen_cli_lib::generated_commands`, generated by root ggen.toml rule
//! `cli-commands-reference` from `.specify/cli-commands.ttl`).
//!
//! Real collaborator: the actual generated table compiled into the workspace
//! binary — no mocks, no fixtures.

use ggen_cli_lib::generated_commands::{describe_command, COMMANDS_REFERENCE};

#[test]
fn generated_reference_is_populated_from_ontology() {
    // The pre-bridge generated table was 8 rows of empty strings (template
    // row-key bug: row["?cmd"] vs row["cmd"]). This asserts real content.
    assert!(
        !COMMANDS_REFERENCE.is_empty(),
        "generated COMMANDS_REFERENCE must not be empty"
    );
    for (iri, label, _comment) in COMMANDS_REFERENCE {
        assert!(!iri.is_empty(), "row has empty IRI: {:?}", (iri, label));
        assert!(!label.is_empty(), "row has empty label: {:?}", (iri, label));
    }
}

#[test]
fn describe_command_resolves_sync_from_ontology() {
    let desc = describe_command("sync");
    assert!(
        desc.is_some(),
        "cli:SyncCommand (label \"sync\") must resolve via describe_command"
    );
    assert!(
        !desc.unwrap_or_default().is_empty(),
        "sync description must be non-empty"
    );
}

#[test]
fn describe_command_returns_none_for_undeclared_label() {
    assert_eq!(describe_command("no-such-command-label"), None);
}
