from __future__ import annotations

import importlib.util
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "observe_self_host.py"
SPEC = importlib.util.spec_from_file_location("ggen_self_observer", SCRIPT)
assert SPEC and SPEC.loader
OBSERVER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(OBSERVER)


def git(root: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(root), *args], check=True, stdout=subprocess.PIPE)


class ObserverFalsifiers(unittest.TestCase):
    def make_repo(self) -> Path:
        root = Path(tempfile.mkdtemp(prefix="ggen-self-observer-"))
        git(root, "init")
        git(root, "config", "user.name", "ggen self-host test")
        git(root, "config", "user.email", "ggen-self-host@example.invalid")
        (root / "Cargo.toml").write_text(
            '[package]\nname="root"\nversion="0.1.0"\n\n[workspace]\nmembers=[]\n',
            encoding="utf-8",
        )
        (root / "ggen.toml").write_text(
            '[project]\nname="x"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n',
            encoding="utf-8",
        )
        (root / "ontology.ttl").write_text("<urn:x> <urn:p> <urn:o> .\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "fixture")
        return root

    def categories(self, root: Path) -> set[str]:
        return {item["category"] for item in OBSERVER.observe(root)["findings"]}

    def test_unlisted_top_level_crate_is_observed_not_silently_ignored(self) -> None:
        root = self.make_repo()
        crate = root / "crates" / "orphan"
        crate.mkdir(parents=True)
        (crate / "Cargo.toml").write_text('[package]\nname="orphan"\nversion="0.1.0"\n', encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "add orphan")
        self.assertIn("workspace-closure", self.categories(root))

    def test_duplicate_root_output_writers_are_refused_as_competing_actuators(self) -> None:
        root = self.make_repo()
        (root / "ggen.toml").write_text(
            '''[project]\nname="x"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n\n[[generation.rules]]\nname="a"\nquery={inline="SELECT * WHERE { ?s ?p ?o }"}\ntemplate={inline="a"}\noutput_file="same.txt"\n\n[[generation.rules]]\nname="b"\nquery={inline="SELECT * WHERE { ?s ?p ?o }"}\ntemplate={inline="b"}\noutput_file="same.txt"\n''',
            encoding="utf-8",
        )
        git(root, "add", ".")
        git(root, "commit", "-m", "duplicate output")
        self.assertIn("output-ownership", self.categories(root))

    def test_generated_header_without_live_owner_is_a_blocking_finding(self) -> None:
        root = self.make_repo()
        crate = root / "crates" / "orphan"
        crate.mkdir(parents=True)
        (crate / "Cargo.toml").write_text('[package]\nname="orphan"\nversion="0.1.0"\n', encoding="utf-8")
        (crate / "lib.rs").write_text("// GENERATED by absent machinery\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "orphan generated")
        observation = OBSERVER.observe(root)
        findings = [item for item in observation["findings"] if item["category"] == "generated-ownership"]
        self.assertTrue(findings)
        self.assertTrue(all(item["severity"] == "Blocking" for item in findings))

    def test_authored_reference_to_generated_child_does_not_claim_file_authority(self) -> None:
        root = self.make_repo()
        authored = root / "authored.rs"
        authored.write_text(
            "pub mod generated_commands; // GENERATED by root ggen.toml rule\n",
            encoding="utf-8",
        )
        git(root, "add", ".")
        git(root, "commit", "-m", "authored reference")
        observation = OBSERVER.observe(root)
        record = next(item for item in observation["files"] if item["path"] == "authored.rs")
        self.assertFalse(record["generated_marker"])
        self.assertEqual(record["authority_class"], "ExecutableSource")

    def test_generated_text_inside_template_is_not_misclassified_as_output(self) -> None:
        root = self.make_repo()
        template = root / "packs" / "example-pack" / "templates" / "source.rs.tmpl"
        template.parent.mkdir(parents=True)
        template.write_text("---\nto: out.rs\n---\n// GENERATED by ggen\n", encoding="utf-8")
        (template.parents[1] / "pack.toml").write_text('[pack]\nname="example-pack"\nversion="0.1.0"\n', encoding="utf-8")
        (template.parents[1] / "ontology.ttl").write_text("<urn:x> <urn:p> <urn:o> .\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "template")
        observation = OBSERVER.observe(root)
        record = next(item for item in observation["files"] if item["path"].endswith("source.rs.tmpl"))
        self.assertEqual(record["authority_class"], "Template")
        self.assertFalse(any(item["evidence_path"] == record["path"] for item in observation["findings"]))

    def test_dormant_archive_manifest_does_not_create_root_output_obligation(self) -> None:
        root = self.make_repo()
        archive = root / "examples" / "archive" / "demo"
        archive.mkdir(parents=True)
        (archive / "ggen.toml").write_text(
            '''[project]\nname="archived"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n\n[[generation.rules]]\nname="missing"\nquery={inline="SELECT * WHERE { ?s ?p ?o }"}\ntemplate={inline="x"}\noutput_file="missing.txt"\n''',
            encoding="utf-8",
        )
        (archive / "ontology.ttl").write_text("<urn:x> <urn:p> <urn:o> .\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "archived consumer")
        observation = OBSERVER.observe(root)
        self.assertFalse(
            any(
                item["category"] == "generated-output" and "missing.txt" in item["summary"]
                for item in observation["findings"]
            )
        )

    def test_symlink_is_hashed_as_tracked_link_not_ambient_target(self) -> None:
        root = self.make_repo()
        outside = Path(tempfile.mkdtemp(prefix="ggen-self-outside-")) / "secret.txt"
        outside.write_text("ambient secret bytes\n", encoding="utf-8")
        link = root / "tracked-link"
        os.symlink(str(outside), link)
        git(root, "add", "tracked-link")
        git(root, "commit", "-m", "track symlink")
        observation = OBSERVER.observe(root)
        record = next(item for item in observation["files"] if item["path"] == "tracked-link")
        self.assertEqual(record["size_bytes"], len(str(outside).encode("utf-8")))
        self.assertEqual(record["digest"], OBSERVER.MODEL.sha256(str(outside).encode("utf-8")))
        self.assertNotEqual(record["digest"], OBSERVER.MODEL.sha256(outside.read_bytes()))

    def test_second_observation_is_byte_identical_at_one_revision(self) -> None:
        root = self.make_repo()
        first = OBSERVER.observe(root)
        second = OBSERVER.observe(root)
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
