from __future__ import annotations

import importlib.util
import subprocess
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "observe_self_host.py"
SPEC = importlib.util.spec_from_file_location("ggen_self_authority_observer", SCRIPT)
assert SPEC and SPEC.loader
OBSERVER = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(OBSERVER)


def git(root: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(root), *args], check=True, stdout=subprocess.PIPE)


def make_repo(manifest: str) -> Path:
    root = Path(tempfile.mkdtemp(prefix="ggen-self-authority-"))
    git(root, "init")
    git(root, "config", "user.name", "ggen self-host test")
    git(root, "config", "user.email", "ggen-self-host@example.invalid")
    (root / "Cargo.toml").write_text(
        '[package]\nname="root"\nversion="0.1.0"\n\n[workspace]\nmembers=[]\n',
        encoding="utf-8",
    )
    (root / "ggen.toml").write_text(manifest, encoding="utf-8")
    (root / "ontology.ttl").write_text("<urn:x> <urn:p> <urn:o> .\n", encoding="utf-8")
    return root


class AuthorityPrecedence(unittest.TestCase):
    def test_active_output_without_marker_is_generated_by_contract(self) -> None:
        root = make_repo(
            '''[project]\nname="x"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n\n[[generation.rules]]\nname="readme"\nquery={inline="SELECT * WHERE { ?s ?p ?o }"}\ntemplate={inline="body"}\noutput_file="README.md"\n'''
        )
        (root / "README.md").write_text("Authored-looking bytes without a marker.\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "active output")
        observation = OBSERVER.observe(root)
        record = next(item for item in observation["files"] if item["path"] == "README.md")
        self.assertEqual(record["authority_class"], "GeneratedConsequence")
        self.assertTrue(record["load_bearing"])
        self.assertFalse(record["generated_marker"])

    def test_generated_pack_ontology_cannot_inherit_authored_standing(self) -> None:
        root = make_repo(
            '[project]\nname="x"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n'
        )
        pack = root / "packs" / "derived-pack"
        pack.mkdir(parents=True)
        (pack / "pack.toml").write_text('[pack]\nname="derived-pack"\nversion="0.1.0"\n', encoding="utf-8")
        (pack / "ontology.ttl").write_text("# GENERATED by another projection\n<urn:x> <urn:p> <urn:o> .\n", encoding="utf-8")
        git(root, "add", ".")
        git(root, "commit", "-m", "generated constitutional output")
        observation = OBSERVER.observe(root)
        record = next(item for item in observation["files"] if item["path"] == "packs/derived-pack/ontology.ttl")
        self.assertEqual(record["authority_class"], "GeneratedConsequence")
        self.assertTrue(record["load_bearing"])
        self.assertTrue(
            any(
                item["category"] == "generated-ownership" and item["evidence_path"] == record["path"]
                for item in observation["findings"]
            )
        )

    def test_standalone_crate_with_exact_manifest_workflow_is_a_load_path_not_an_orphan(self) -> None:
        root = make_repo(
            '[project]\nname="x"\nversion="0.1.0"\n\n[ontology]\nsource="ontology.ttl"\n\n[generation]\noutput_dir="."\n'
        )
        crate = root / "crates" / "isolated"
        crate.mkdir(parents=True)
        (crate / "Cargo.toml").write_text('[package]\nname="isolated"\nversion="0.1.0"\n', encoding="utf-8")
        workflow = root / ".github" / "workflows" / "isolated.yml"
        workflow.parent.mkdir(parents=True)
        workflow.write_text(
            "name: isolated\non: workflow_dispatch\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: cargo test --manifest-path crates/isolated/Cargo.toml\n",
            encoding="utf-8",
        )
        git(root, "add", ".")
        git(root, "commit", "-m", "standalone product")
        observation = OBSERVER.observe(root)
        self.assertFalse(
            any(
                item["category"] == "workspace-closure"
                and item["evidence_path"] == "crates/isolated/Cargo.toml"
                for item in observation["findings"]
            )
        )
        load_path = next(item for item in observation["load_paths"] if item["id"] == "standalone-isolated")
        self.assertEqual(load_path["actuator"], ".github/workflows/isolated.yml")
        self.assertEqual(load_path["standing"], "PARTIAL_ALIVE")


if __name__ == "__main__":
    unittest.main()
