FROM erlang:26-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git build-base

# Copy project
COPY . .

# Build and run tests
RUN rebar3 compile
CMD ["rebar3", "ct", "--spec", "test/test.spec"]
