SELECT DISTINCT ?type ?variant_name ?variant_rename
WHERE {
    ?type a mcpp:Type .
    ?type mcpp:isEnum true .
    ?type mcpp:hasVariant ?variant .
    ?variant mcpp:name ?variant_name .
    OPTIONAL { ?variant mcpp:rename ?variant_rename }
} ORDER BY ?type ?variant_name