SELECT DISTINCT ?test ?test_name ?test_description ?test_code ?test_assertion
WHERE {
    ?test a mcpp:Test .
    ?test mcpp:name ?test_name .
    OPTIONAL { ?test mcpp:description ?test_description }
    OPTIONAL { ?test mcpp:code ?test_code }
    OPTIONAL { ?test mcpp:assertion ?test_assertion }
} ORDER BY ?test_name