SELECT DISTINCT ?type ?visibility ?name ?description ?derive ?struct
WHERE {
    ?type a mcpp:Type .
    ?type mcpp:name ?name .
    OPTIONAL { ?type mcpp:visibility ?visibility }
    OPTIONAL { ?type mcpp:description ?description }
    OPTIONAL { ?type mcpp:derive ?derive }
    OPTIONAL { ?type mcpp:isStruct ?struct }
} ORDER BY ?name