SELECT DISTINCT ?type ?field_name ?field_type
WHERE {
    ?type a mcpp:Type .
    ?type mcpp:isUnion true .
    ?type mcpp:hasField ?field .
    ?field mcpp:name ?field_name .
    ?field mcpp:type ?field_type .
} ORDER BY ?type ?field_name