//! Generated Library Root - DO NOT EDIT
//!
//! This file is automatically generated by ggen from ontology/
//! To make changes, edit the ontology and run: ggen sync

// Re-export all generated modules
pub mod entities;
pub mod commands;
pub mod events;
pub mod aggregates;
pub mod handlers;
pub mod routes;

// Re-export key types for convenience
pub use entities::*;
pub use commands::*;
pub use events::*;
pub use aggregates::*;
pub use handlers::*;
pub use routes::build_router;
