#!/usr/bin/env bash
# GENERATED by `ggen sync` from .specify/templates/verify/produce_docs_manifest_sh.sh.tera
# (ggen.toml's own declarative-rules mirror of packs/ggen-verify-pack's
# templates/produce_docs_manifest_sh.tmpl -- see that file's header for the
# schema note on why this repo needs its own copy). Docs-class producer:
# emits a normalized manifest (per generated doc: project-relative path +
# sha256, path-sorted) as ver:DocsManifestEntry facts. Sync derives the docs
# equivalence-class identity from these facts and compares it against the
# previous receipt's recorded one -> docs Equivalent/Divergent/Unknown. This
# script records reality and always exits 0; judgment happens at sync.
set -uo pipefail
cd "$(dirname "$0")/.."
mkdir -p evidence/producers
DOCS_DIR='docs'

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

OUT=evidence/producers/docs-manifest.ttl
{
  echo "# GENERATED by scripts/produce-docs-manifest.sh -- do not edit."
  echo "@prefix ver: <http://seanchatmangpt.github.io/packs/ggen-verify#> ."
  echo
  i=0
  if [ -d "$DOCS_DIR" ]; then
    find "$DOCS_DIR" -type f | LC_ALL=C sort | while IFS= read -r f; do
      echo "ver:docsman-$i a ver:DocsManifestEntry ;"
      echo "    ver:path \"$f\" ;"
      echo "    ver:sha256 \"$(sha256_of "$f")\" ."
      echo
      i=$((i + 1))
    done
  fi
} > "$OUT"
echo "produce-docs-manifest.sh: wrote $(grep -c DocsManifestEntry "$OUT") entries -> $OUT"
exit 0
