#!/bin/bash
# Regenerate all examples using ggen's own commands (DOGFOODING)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GGEN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
EXAMPLES_DIR="$GGEN_ROOT/examples"

echo "🐕 Dogfooding: Regenerating examples using ggen itself"
echo "=================================================="
echo ""

cd "$GGEN_ROOT"

# Ensure ggen is built
echo "📦 Building ggen CLI..."
cargo build --release --bin ggen
GGEN_BIN="$GGEN_ROOT/target/release/ggen"

if [ ! -f "$GGEN_BIN" ]; then
    echo "❌ Failed to build ggen"
    exit 1
fi

echo "✅ ggen built successfully"
echo ""

# Clean old examples
echo "🧹 Cleaning old manually-created examples..."
rm -rf "$EXAMPLES_DIR/advanced-cli-tool"
rm -rf "$EXAMPLES_DIR/perf-library"
rm -rf "$EXAMPLES_DIR/async-web-service"
rm -rf "$EXAMPLES_DIR/wasm-crypto"
rm -rf "$EXAMPLES_DIR/embedded-iot"
echo "✅ Cleaned"
echo ""

# Example 1: Advanced CLI Tool
echo "1️⃣  Generating Advanced CLI Tool using 'ggen ai project'..."
"$GGEN_BIN" ai project \
    --description "Advanced CLI tool for file processing with async I/O, multiple subcommands (process, analyze, convert, benchmark), comprehensive error handling with anyhow, structured logging with tracing, configuration via TOML files, and progress bars" \
    --name "advanced-cli-tool" \
    --language rust \
    --output "$EXAMPLES_DIR/advanced-cli-tool" \
    --tests \
    --docs \
    --mock || echo "⚠️  AI generation failed, continuing..."

# Add lifecycle configuration
if [ -d "$EXAMPLES_DIR/advanced-cli-tool" ]; then
    cat > "$EXAMPLES_DIR/advanced-cli-tool/make.toml" <<'EOF'
# Generated by ggen - Advanced CLI Tool Lifecycle

[lifecycle.format]
command = "cargo fmt -- --check"

[lifecycle.lint]
command = "cargo clippy --all-targets -- -D warnings"

[lifecycle.build]
command = "cargo build --release"

[lifecycle.test]
command = "cargo test --all-features"

[lifecycle.bench]
command = "cargo bench"

[lifecycle.audit]
command = "cargo audit"

[lifecycle.deploy]
commands = [
    "cargo build --release",
    "strip target/release/advanced-cli-tool || true",
    "mkdir -p dist",
    "cp target/release/advanced-cli-tool dist/"
]

[hooks]
before_build = ["format", "lint"]
after_build = ["test"]
before_deploy = ["audit", "test", "build"]

[env]
RUST_BACKTRACE = "1"
RUST_LOG = "info"
EOF
    echo "✅ CLI tool generated with lifecycle"
else
    echo "⚠️  CLI tool directory not created, skipping lifecycle"
fi
echo ""

# Example 2: Performance Library
echo "2️⃣  Generating Performance Library using 'ggen ai generate'..."
mkdir -p "$EXAMPLES_DIR/perf-library/src"
"$GGEN_BIN" ai generate \
    --description "High-performance Rust library with custom hash table using ahash, lock-free concurrent data structures with crossbeam, memory-efficient storage, and comprehensive criterion benchmarks" \
    --examples "ahash for fast hashing" "rayon for parallelism" "crossbeam for lock-free" "criterion for benchmarks" \
    --output "$EXAMPLES_DIR/perf-library/src/lib.rs" \
    --mock || echo "⚠️  AI generation failed, creating template..."

# Create Cargo.toml for library
cat > "$EXAMPLES_DIR/perf-library/Cargo.toml" <<'EOF'
[package]
name = "perf-library"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
rayon = "1.8"
crossbeam = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "performance"
harness = false

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
EOF

cat > "$EXAMPLES_DIR/perf-library/make.toml" <<'EOF'
# Generated by ggen - Performance Library Lifecycle

[lifecycle.bench-baseline]
command = "cargo bench -- --save-baseline baseline"

[lifecycle.bench]
command = "cargo bench"

[lifecycle.bench-compare]
command = "cargo bench -- --baseline baseline"

[lifecycle.profile]
command = "cargo flamegraph --bench performance -- --bench"

[lifecycle.optimize]
commands = [
    "RUSTFLAGS='-C target-cpu=native' cargo build --release",
    "cargo bench -- --baseline baseline"
]

[lifecycle.validate]
commands = [
    "cargo test",
    "cargo clippy -- -D warnings"
]

[env]
RUSTFLAGS = "-C target-cpu=native"
CARGO_PROFILE_RELEASE_LTO = "fat"
EOF

echo "✅ Library generated with benchmarks"
echo ""

# Example 3: Create placeholder for remaining examples
echo "3️⃣  Creating placeholders for remaining examples..."
for example in "async-web-service" "wasm-crypto" "embedded-iot"; do
    mkdir -p "$EXAMPLES_DIR/$example"
    cat > "$EXAMPLES_DIR/$example/README.md" <<EOF
# $example

This example will be generated using:

\`\`\`bash
ggen ai project \\
    --description "..." \\
    --name "$example" \\
    --output examples/$example \\
    --tests \\
    --docs
\`\`\`

**Status**: Placeholder - run regenerate-examples.sh with AI provider configured
EOF
    echo "  📝 Created placeholder: $example"
done

echo ""
echo "=================================================="
echo "✅ Example regeneration complete!"
echo ""
echo "Generated examples using ggen's own commands:"
echo "  • advanced-cli-tool - via 'ggen ai project'"
echo "  • perf-library - via 'ggen ai generate'"
echo "  • async-web-service - placeholder"
echo "  • wasm-crypto - placeholder"
echo "  • embedded-iot - placeholder"
echo ""
echo "To complete generation, configure AI provider:"
echo "  export ANTHROPIC_API_KEY=your-key"
echo "  # OR"
echo "  export OPENAI_API_KEY=your-key"
echo ""
echo "Then run: $0"
echo ""
echo "🐕 Dogfooding successful! ggen used itself to create examples."
