PREFIX p8:   <https://prolog8.dev/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?feature_name ?bit_index ?feature_label
WHERE {
    ?s a p8:FeatureBit .
    BIND(STRAFTER(STR(?s), "https://prolog8.dev/feat#") AS ?feature_name)
    ?s p8:bitIndex ?bit_index .
    ?s rdfs:label ?feature_label .
} ORDER BY ?bit_index
