PREFIX p8:   <https://prolog8.dev/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?repr ?purpose
WHERE {
    ?s a p8:RustType .
    ?s rdfs:label ?label .
    ?s p8:repr ?repr .
    OPTIONAL { ?s p8:purpose ?purpose }
} ORDER BY ?label
