//! clap-noun-verb routes — GENERATED by `ggen sync` from the
//! `clap-noun-verb-pack` ontology (`cnv:Command` individuals). Do not edit
//! by hand: routes are a pure projection of the ontology; there is NO logic
//! slot here — business logic lives behind the stable seam in
//! `crate::verbs::handlers::*` (hand-written; a missing impl is a compile
//! error). To freeze this file against regeneration, add a comment
//! containing the literal marker "ggen" + ":" + "local-override" (written
//! apart here so this instructional comment doesn't itself trigger the
//! freeze).
//!
//! Pattern aligned with ~/clap-noun-verb's own authoritative pack
//! conventions (templates/verb.rs.tera): thin wrapper, typed args,
//! Rust-reserved-word raw-identifier escaping.

use clap_noun_verb::Result;
use clap_noun_verb_macros::verb;
use serde_json::json;/// List every wasm4pm process-intelligence algorithm in the generated catalog.
#[verb("list", "algorithm")]
fn algorithm_list(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::algorithm_list_handler(
    )
}

/// List every wasm4pm cognition breed in the generated catalog.
#[verb("list", "cognition")]
fn cognition_list(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::cognition_list_handler(
    )
}

/// Emit a receipt_chained OCEL event for a given sync-receipt id.
#[verb("emit", "receipt")]
fn receipt_emit(
    sync_receipt_id: String,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::receipt_emit_handler(
        sync_receipt_id,
    )
}

/// Start an authenticated session and persist the token.
#[verb("login", "session")]
fn session_login(
    token: String,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::session_login_handler(
        token,
    )
}

/// Zero-argument liveness check with a fixed response body -- entirely ontology-specified, no hand-written handler required.
#[verb("ping", "session")]
fn session_ping(
) -> Result<serde_json::Value> {
    // Zero-handler command: cnv:staticResponse fully specifies this
    // command's behavior in the ontology. No `crate::verbs::handlers::*`
    // fn is called or required to exist for `session ping`.
    Ok(json!({ "status": "alive", "noun": "session", "verb": "ping" }))
}

/// Verify the active session token against the stored keyring credential.
#[verb("verify", "session")]
fn session_verify(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::session_verify_handler(
    )
}

/// Create a user resource and emit its serialized record.
#[verb("create", "user")]
fn user_create(
    name: String,
    email: Option<String>,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::user_create_handler(
        name,
        email,
    )
}


// ---------------------------------------------------------------------
// Noun `--help` descriptions, generated from each `cnv:Noun` individual's
// `rdfs:comment`. clap-noun-verb's `#[verb]` macro can ALSO auto-scrape a
// noun's `about` text by re-reading its source file's `//!` doc comment
// from disk at runtime via a `file!()`-derived path — but that path only
// resolves when the process's current directory happens to be the source
// checkout, which a distributed/installed CLI binary cannot rely on.
// Registering here instead is robust regardless of working directory:
// `__NOUN_REGISTRY` entries all run before `__VERB_REGISTRY` entries at
// first access, and `CommandRegistry::register_noun` is first-writer-wins
// (`entry(..).or_insert_with(..)`), so this generated registration always
// wins over the macro's own runtime scrape attempt.
// ---------------------------------------------------------------------


#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_ALGORITHM_NOUN: fn() = register_algorithm_noun;
fn register_algorithm_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "algorithm",
        "Inspect the wasm4pm process-intelligence algorithm catalog.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_COGNITION_NOUN: fn() = register_cognition_noun;
fn register_cognition_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "cognition",
        "Inspect the wasm4pm cognition breed catalog.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_RECEIPT_NOUN: fn() = register_receipt_noun;
fn register_receipt_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "receipt",
        "Emit OCEL events for the wasm4pm-compat receipt/pack lifecycle.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_SESSION_NOUN: fn() = register_session_noun;
fn register_session_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "session",
        "Manage authenticated session tokens.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_USER_NOUN: fn() = register_user_noun;
fn register_user_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "user",
        "Manage user resources.",
    );
}


#[cfg(test)]
mod clap_noun_verb_routes_proof_tests {
    // Proof tests for this pack's own generated routes, in the same file
    // (not a separate `tests/*.rs` file): the wrapper fns above (e.g.
    // `session_login`, `session_verify`, `user_create`) and the noun
    // registration fns are private to this module -- a separate
    // integration-test crate under `tests/` has zero visibility into them
    // (Rust privacy is unaffected by `pub mod`/`#[path]` re-mounting from a
    // sibling or parent module). Only a `#[cfg(test)] mod` declared *inside*
    // this same file is a descendant of this module and can `use super::*;`
    // to reach them directly. This also avoids FM-WRITE-008 (two templates
    // cannot both target `src/clap_noun_verb_routes.rs` in one `ggen sync`
    // pass, even with `inject: true` on one of them) by construction: there
    // is only ever one template, one `to:` target, for this file.
    //
    // Tier 1's per-command literals below (token/name/email fixture values)
    // are still hand-written proof INPUTS -- that's normal Chicago-TDD
    // arrange-phase data, not a drift risk. Tier 2's EXPECTED_* constants,
    // by contrast, are rendered by this same template pass from the
    // `commands`/`nouns` SPARQL projection that also produced the routes
    // above (see this template's own Tera for-loops in Tier 2 below). A
    // dropped, renamed, or mis-typed `cnv:Command`/`cnv:Noun` individual
    // changes the generated routes AND the generated expectations in the
    // same regen, so this is a real drift canary against the ontology, not
    // a tautological self-comparison of hand-copied strings.
    use super::*;

    // ---- Tier 1: real calls through the generated wrapper into the real,
    // hand-written `crate::verbs::handlers::*` seam (no mocks/test doubles --
    // Chicago TDD real collaborator). A required/optional-arg mapping bug
    // (e.g. `email` generated as `String` instead of `Option<String>`) fails
    // to COMPILE here, before any assertion runs -- a stronger signal than an
    // assert. The `.is_ok()` checks are genuine runtime assertions against
    // the real handler's return value, not a mock interaction.

    #[test]
    fn session_login_takes_required_token_and_succeeds() {
        // cnv:SessionLogin cnv:args "token|String|true|..." -> a single
        // required `String` parameter (no `Option<..>` wrapper).
        let result = session_login("proof-token".to_string());
        assert!(
            result.is_ok(),
            "session_login(\"proof-token\") should succeed via the real handler: {result:?}"
        );
    }

    #[test]
    fn session_verify_is_zero_arg_and_succeeds() {
        // cnv:SessionVerify cnv:args "" -> zero-arg function.
        let result = session_verify();
        assert!(
            result.is_ok(),
            "session_verify() should succeed via the real handler: {result:?}"
        );
    }

    // cnv:SessionPing carries cnv:staticResponse -- its ENTIRE behavior,
    // not just its signature, is specified in ontology.ttl. This asserts
    // on actual output CONTENT (not merely `.is_ok()`), and the expected
    // content below is the literal ontology fact
    // `json!({ "status": "alive", "noun": "session", "verb": "ping" })`,
    // reached with zero hand-written `crate::verbs::handlers::*` code:
    // there is no `session_ping_handler` anywhere in this crate.
    #[test]
    fn session_ping_is_zero_handler_and_returns_its_ontology_specified_body() {
        let result = session_ping().expect("session_ping has no handler dependency; always Ok");
        assert_eq!(result["status"], "alive");
        assert_eq!(result["noun"], "session");
        assert_eq!(result["verb"], "ping");
    }

    #[test]
    fn user_create_required_name_with_optional_email_present() {
        // cnv:UserCreate cnv:args
        // "name|String|true|...@@email|String|false|..." -> `name: String`
        // required, `email: Option<String>` optional.
        let result = user_create("Ada".to_string(), Some("ada@example.com".to_string()));
        assert!(
            result.is_ok(),
            "user_create(\"Ada\", Some(email)) should succeed via the real handler: {result:?}"
        );
    }

    #[test]
    fn user_create_optional_email_absent() {
        let result = user_create("Ada".to_string(), None);
        assert!(
            result.is_ok(),
            "user_create(\"Ada\", None) should succeed via the real handler: {result:?}"
        );
    }

    // ---- Tier 2: drift canary. Re-reads this same generated file's own
    // source text at compile time and checks it against literal
    // counts/strings rendered by THIS SAME TEMPLATE PASS from the same
    // `commands`/`nouns` SPARQL-projected context that produced the routes
    // above (see this template's own command/noun for-loops that emitted
    // the wrapper fns and noun registrations) --
    // NOT hand-transcribed by a human re-reading ontology.ttl. An ontology
    // edit that adds/removes/renames a `cnv:Command`/`cnv:Noun` individual
    // therefore regenerates BOTH the production code and these expected
    // literals in the same `ggen sync` pass: there is no separate manual
    // transcription step left to drift out of sync with the ontology.
    const EXPECTED_COMMAND_COUNT: usize = 7;
    const EXPECTED_NOUN_COUNT: usize = 5;
    const EXPECTED_DOCS: &[&str] = &[
        "List every wasm4pm process-intelligence algorithm in the generated catalog.",
        "List every wasm4pm cognition breed in the generated catalog.",
        "Emit a receipt_chained OCEL event for a given sync-receipt id.",
        "Start an authenticated session and persist the token.",
        "Zero-argument liveness check with a fixed response body -- entirely ontology-specified, no hand-written handler required.",
        "Verify the active session token against the stored keyring credential.",
        "Create a user resource and emit its serialized record.",
    ];
    const EXPECTED_NOUN_DESCRIPTIONS: &[&str] = &[
        "Inspect the wasm4pm process-intelligence algorithm catalog.",
        "Inspect the wasm4pm cognition breed catalog.",
        "Emit OCEL events for the wasm4pm-compat receipt/pack lifecycle.",
        "Manage authenticated session tokens.",
        "Manage user resources.",
    ];
    //
    // `src/clap_noun_verb_routes.rs` is this pack's own fixed `to:` path
    // (see this template's frontmatter) -- not derived from `file!()`, so
    // this is stable regardless of how the module happens to be mounted
    // (`#[path = "..."]`, `mod`, etc.) by the consuming project.
    //
    // Two things this scan must account for, both discovered by actually
    // running this test against a real consumer (`examples/receiptctl`),
    // not assumed:
    //
    // 1. `include_str!` reads the WHOLE file, including this test module's
    //    own source. A naive `.matches("#[verb(")` on the full text counts
    //    the literal string inside this very assertion's argument as a
    //    match too (off-by-one). `ROUTES_ONLY` slices `GENERATED_SOURCE` up
    //    to the `#[cfg(test)]` marker -- text this template always emits
    //    immediately before the test module -- so counts only look at the
    //    actually-generated routes, never at this test's own source.
    // 2. `clap-noun-verb-pack` is a routing pack, not a self-contained-data
    //    pack: a consuming project's OWN ontology (e.g.
    //    `examples/receiptctl/schema/domain.ttl`) can assert additional
    //    `cnv:Command`/`cnv:Noun` individuals in the SAME `cnv:` namespace,
    //    which the union graph legitimately adds to this file (receiptctl
    //    itself does exactly this: 3 more commands, 3 more nouns, on top of
    //    this pack's own 3 commands / 2 nouns). So this pack can only
    //    guarantee its OWN individuals are present -- never that they are
    //    the ONLY ones -- and the counts below are `>=`, not `==`.
    const GENERATED_SOURCE: &str =
        include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/clap_noun_verb_routes.rs"));

    fn routes_only() -> &'static str {
        GENERATED_SOURCE
            .split("#[cfg(test)]")
            .next()
            .expect("GENERATED_SOURCE is a non-empty &str; split always yields >=1 part")
    }

    #[test]
    fn generated_source_has_at_least_this_packs_verb_commands() {
        let count = routes_only().matches("#[verb(").count();
        assert!(
            count >= EXPECTED_COMMAND_COUNT,
            "expected at least the {EXPECTED_COMMAND_COUNT} verb commands from this pack's own \
             ontology.ttl (count itself rendered from the same `commands` SPARQL projection), \
             found {count} in the generated routes portion (a consuming project's own ontology \
             may legitimately add more)"
        );
    }

    #[test]
    fn generated_source_has_at_least_this_packs_registered_nouns() {
        let count = routes_only()
            .matches("CommandRegistry::register_noun(")
            .count();
        assert!(
            count >= EXPECTED_NOUN_COUNT,
            "expected at least the {EXPECTED_NOUN_COUNT} nouns from this pack's own ontology.ttl \
             (count itself rendered from the same `nouns` SPARQL projection), found {count} in \
             the generated routes portion (a consuming project's own ontology may legitimately \
             add more)"
        );
    }

    #[test]
    fn generated_source_carries_literal_command_docs_from_ontology() {
        for doc in EXPECTED_DOCS {
            assert!(
                GENERATED_SOURCE.contains(doc),
                "generated routes missing doc comment {doc:?} (rendered from the same \
                 `commands` projection as the routes themselves)"
            );
        }
    }

    #[test]
    fn generated_source_carries_literal_noun_descriptions_from_ontology() {
        for about in EXPECTED_NOUN_DESCRIPTIONS {
            let needle = format!("\"{about}\"");
            assert!(
                GENERATED_SOURCE.contains(&needle),
                "generated routes missing noun description {needle:?} (rendered from the same \
                 `nouns` projection as the registrations themselves)"
            );
        }
    }

    #[test]
    fn generated_source_marshals_user_create_args_with_correct_types() {
        // Asserts the exact generated parameter-list text for `user_create`,
        // proving `name` stayed required (`String`) and `email` stayed
        // optional (`Option<String>`) per cnv:UserCreate's `cnv:args` literal.
        assert!(GENERATED_SOURCE.contains("name: String,"));
        assert!(GENERATED_SOURCE.contains("email: Option<String>,"));
    }
}
