//! clap-noun-verb routes — GENERATED by `ggen sync` from the
//! `clap-noun-verb-pack` ontology (`cnv:Command` individuals). Do not edit
//! by hand: routes are a pure projection of the ontology; there is NO logic
//! slot here — business logic lives behind the stable seam in
//! `crate::verbs::handlers::*` (hand-written; a missing impl is a compile
//! error). To freeze this file against regeneration, add a comment
//! containing the literal marker "ggen" + ":" + "local-override" (written
//! apart here so this instructional comment doesn't itself trigger the
//! freeze).
//!
//! Pattern aligned with ~/clap-noun-verb's own authoritative pack
//! conventions (templates/verb.rs.tera): thin wrapper, typed args,
//! Rust-reserved-word raw-identifier escaping.

use clap_noun_verb::Result;
use clap_noun_verb_macros::verb;/// List every wasm4pm process-intelligence algorithm in the generated catalog.
#[verb("list", "algorithm")]
fn algorithm_list(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::algorithm_list_handler(
    )
}

/// List every wasm4pm cognition breed in the generated catalog.
#[verb("list", "cognition")]
fn cognition_list(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::cognition_list_handler(
    )
}

/// Emit a receipt_chained OCEL event for a given sync-receipt id.
#[verb("emit", "receipt")]
fn receipt_emit(
    sync_receipt_id: String,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::receipt_emit_handler(
        sync_receipt_id,
    )
}

/// Start an authenticated session and persist the token.
#[verb("login", "session")]
fn session_login(
    token: String,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::session_login_handler(
        token,
    )
}

/// Verify the active session token against the stored keyring credential.
#[verb("verify", "session")]
fn session_verify(
) -> Result<serde_json::Value> {
    crate::verbs::handlers::session_verify_handler(
    )
}

/// Create a user resource and emit its serialized record.
#[verb("create", "user")]
fn user_create(
    name: String,
    email: Option<String>,
) -> Result<serde_json::Value> {
    crate::verbs::handlers::user_create_handler(
        name,
        email,
    )
}


// ---------------------------------------------------------------------
// Noun `--help` descriptions, generated from each `cnv:Noun` individual's
// `rdfs:comment`. clap-noun-verb's `#[verb]` macro can ALSO auto-scrape a
// noun's `about` text by re-reading its source file's `//!` doc comment
// from disk at runtime via a `file!()`-derived path — but that path only
// resolves when the process's current directory happens to be the source
// checkout, which a distributed/installed CLI binary cannot rely on.
// Registering here instead is robust regardless of working directory:
// `__NOUN_REGISTRY` entries all run before `__VERB_REGISTRY` entries at
// first access, and `CommandRegistry::register_noun` is first-writer-wins
// (`entry(..).or_insert_with(..)`), so this generated registration always
// wins over the macro's own runtime scrape attempt.
// ---------------------------------------------------------------------


#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_ALGORITHM_NOUN: fn() = register_algorithm_noun;
fn register_algorithm_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "algorithm",
        "Inspect the wasm4pm process-intelligence algorithm catalog.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_COGNITION_NOUN: fn() = register_cognition_noun;
fn register_cognition_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "cognition",
        "Inspect the wasm4pm cognition breed catalog.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_RECEIPT_NOUN: fn() = register_receipt_noun;
fn register_receipt_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "receipt",
        "Emit OCEL events for the wasm4pm-compat receipt/pack lifecycle.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_SESSION_NOUN: fn() = register_session_noun;
fn register_session_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "session",
        "Manage authenticated session tokens.",
    );
}

#[linkme::distributed_slice(::clap_noun_verb::cli::registry::__NOUN_REGISTRY)]
static REGISTER_USER_NOUN: fn() = register_user_noun;
fn register_user_noun() {
    ::clap_noun_verb::cli::registry::CommandRegistry::register_noun(
        "user",
        "Manage user resources.",
    );
}

