//! Typed catalog of the wasm4pm process-intelligence ALGORITHM surface.
//!
//! Generated by `wasm4pm-algorithms-pack` from `pi:ProcessIntelligenceAlgorithm`
//! individuals carried over from the wasm4pm algorithm ontology. This is a
//! CATALOG/CALLER surface only: discovery, conformance, fitness, and variant
//! analysis all execute inside wasm4pm, never here.

/// Every wasm4pm process-intelligence algorithm this catalog knows about.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlgorithmId {
    /// `a_star` (discovery) — A* shortest-path discovery over DFG — finds optimal path through the directly-follows graph using heuristic search, producing a Petri net model.
    AStar,
    /// `aco` (discovery) — Ant Colony Optimisation discovery — stochastic population-based search inspired by ant foraging, producing Petri net models with good fitness/precision balance.
    Aco,
    /// `agentic_pipeline` (agentic) — Orchestrated multi-step agentic pipeline — chains discovery, conformance, and analytics algorithms in a reasoning loop, selecting next operation based on intermediate results.
    AgenticPipeline,
    /// `alignments` (conformance) — Alignment-based conformance checking — synchronously replays each trace on the Petri net, computing optimal alignment cost using A* over the synchronous product automaton.
    Alignments,
    /// `alpha_plus_plus` (discovery) — Alpha++ miner — extends the original Alpha algorithm to handle length-one and length-two loops, producing a Petri net from the directly-follows footprint matrix.
    AlphaPlusPlus,
    /// `analyze_process_speedup` (discovery_analytics) — Measures speedup potential across trace variants — identifies bottleneck activity pairs and quantifies theoretical throughput gain from parallelisation.
    AnalyzeProcessSpeedup,
    /// `analyze_variant_complexity` (discovery_analytics) — Complexity metrics per trace variant — computes length distribution, unique activity count, loop density, and entropy for each distinct variant in the log.
    AnalyzeVariantComplexity,
    /// `automl_classify` (ml_analytics) — AutoML classification — automatically selects and tunes a classifier (decision tree, random forest, gradient boosting) from process feature vectors.
    AutomlClassify,
    /// `automl_forecast` (ml_analytics) — AutoML time-series forecasting — automatically selects and tunes a forecasting model for process throughput or case duration prediction.
    AutomlForecast,
    /// `batches` (discovery_analytics) — Detects batch-execution patterns — identifies when a resource processes multiple cases simultaneously (sequential, concurrent, simultaneous, or interleaved batches).
    Batches,
    /// `bpmn_import` (import_export) — Import BPMN 2.0 XML to process tree — parses a BPMN 2.0 XML document and converts flow elements to a block-structured process tree.
    BpmnImport,
    /// `causal_graph` (discovery_analytics) — Causal dependency graph — applies causal inference to distinguish spurious correlations in the DFG from genuine causal dependencies between activities.
    CausalGraph,
    /// `complexity_metrics` (conformance) — Structural complexity metrics (size, CFC, depth) — computes Control Flow Complexity, model size, connector degree distribution, and depth without replaying the log.
    ComplexityMetrics,
    /// `compute_activity_transition_matrix` (discovery_analytics) — Activity-to-activity transition probability matrix — computes the n x n matrix of empirical transition probabilities between all activity pairs.
    ComputeActivityTransitionMatrix,
    /// `compute_ewma` (prediction) — Exponentially weighted moving average on case metrics — applies EWMA smoothing to process KPI time-series for trend-aware monitoring.
    ComputeEwma,
    /// `compute_trace_similarity_matrix` (discovery_analytics) — Pairwise trace similarity matrix — computes edit-distance or Jaccard similarity for all trace pairs; used as input to clustering and variant analysis.
    ComputeTraceSimilarityMatrix,
    /// `correlation_miner` (discovery_analytics) — Correlation-based dependency miner — discovers dependencies from statistical correlation of activity occurrences without requiring case identifiers.
    CorrelationMiner,
    /// `declare` (discovery) — Declarative constraint mining using LTL-based temporal logic — discovers existence, response, and precedence constraints rather than a procedural model.
    Declare,
    /// `detect_drift` (prediction) — Concept drift detection — applies statistical change-point tests (ADWIN, Page-Hinkley) to a sliding window to detect when the underlying process has changed.
    DetectDrift,
    /// `dfg` (discovery) — Directly-Follows Graph — fastest baseline discovery, counting how often one activity directly follows another. Serves as input to most other discovery algorithms.
    Dfg,
    /// `etconformance_precision` (conformance) — ETConformance precision — measures how much of the model's behaviour is actually observed in the log using escaping-edges token-based precision.
    EtconformancePrecision,
    /// `generalization` (conformance) — Van der Aalst generalization score — measures how well the model generalises beyond the observed log by penalising infrequently visited transitions.
    Generalization,
    /// `genetic_algorithm` (discovery) — Genetic algorithm process model search — evolves a population of candidate Petri nets using fitness, precision, generalization and simplicity as multi-objective fitness functions.
    GeneticAlgorithm,
    /// `handover_network` (discovery_analytics) — Social network: handover-of-work between resources — nodes are resources, arcs represent how frequently one resource hands a case to another.
    HandoverNetwork,
    /// `heuristic_miner` (discovery) — Heuristics Miner — uses dependency measures to filter noise before constructing a causal net. Dependency threshold controls filtering aggressiveness.
    HeuristicMiner,
    /// `hierarchical_dfg` (discovery) — Hierarchical DFG — extends the standard DFG with automatic detection and collapsing of recurring sub-process patterns.
    HierarchicalDfg,
    /// `hill_climbing` (discovery) — Hill-climbing local search — iteratively improves a candidate model by applying local operators, terminating at a local optimum.
    HillClimbing,
    /// `ilp` (discovery) — ILP Miner — solves an integer linear programming problem to find a Petri net fitting the directly-follows relations; produces high-precision sound models.
    Ilp,
    /// `inductive_miner` (discovery) — Inductive Miner — recursively discovers a sound, block-structured process tree from the event log by detecting cut types (sequence, parallel, choice, loop).
    InductiveMiner,
    /// `log_to_trie` (discovery) — Prefix-tree (trie) representation — inserts all traces into a trie where each path from root to leaf represents a unique trace variant.
    LogToTrie,
    /// `ml_anomaly` (ml_analytics) — Anomaly detection — applies isolation forest or one-class SVM to process feature vectors to flag statistically anomalous traces or events.
    MlAnomaly,
    /// `ml_classify` (ml_analytics) — Supervised classification — trains a classifier on labeled process feature vectors and predicts labels for unseen cases.
    MlClassify,
    /// `ml_cluster` (ml_analytics) — Unsupervised clustering — applies k-means or DBSCAN to process feature vectors to discover natural groupings of cases or traces.
    MlCluster,
    /// `ml_forecast` (ml_analytics) — Time-series forecasting — trains a forecasting model on historical process metrics and produces forward projections.
    MlForecast,
    /// `ml_pca` (ml_analytics) — Principal Component Analysis — reduces dimensionality of process feature vectors, revealing principal axes of variation.
    MlPca,
    /// `ml_regress` (ml_analytics) — Regression — fits a regression model to predict a continuous target (e.g., case duration) from process feature vectors.
    MlRegress,
    /// `monte_carlo_simulation` (simulation) — Monte Carlo simulation from discovered model — samples synthetic traces from empirical transition probability distribution to estimate throughput time distributions.
    MonteCarloSimulation,
    /// `ocel_dfg` (object_centric) — Object-centric DFG across all object types — flattens the OCEL log into a unified DFG weighted by event frequency regardless of type.
    OcelDfg,
    /// `ocel_dfg_per_type` (object_centric) — Separate DFG per object type — produces one DFG for each object type in the OCEL log, enabling per-type flow analysis without cross-type interference.
    OcelDfgPerType,
    /// `ocel_encode` (object_centric) — Encodes OCEL log to feature matrix — transforms the object-centric log into a numeric feature matrix suitable for downstream ML algorithms.
    OcelEncode,
    /// `ocel_oc_declare` (object_centric) — Object-centric Declare constraint discovery — mines LTL-based temporal constraints from the OCEL log, relating events across different object types.
    OcelOcDeclare,
    /// `ocel_ocla` (object_centric) — Object-centric log abstraction analytics — computes summary statistics: object interaction counts, event density, and type co-occurrence matrices.
    OcelOcla,
    /// `ocel_petri_net` (object_centric) — Per-type flattened Petri nets — applies the Inductive Miner to each object-type-flattened sub-log to produce a sound Petri net per type.
    OcelPetriNet,
    /// `optimized_dfg` (discovery) — DFG with arc-weight optimisation pass — builds a standard DFG then applies pruning to remove statistically insignificant arcs.
    OptimizedDfg,
    /// `performance_spectrum` (discovery_analytics) — Performance spectrum — segments all arc traversals in the DFG by time, producing a time-sliced frequency matrix for flow rate visualisation.
    PerformanceSpectrum,
    /// `playout` (simulation) — Stochastic playout from Petri net — generates synthetic event logs by firing enabled transitions according to stochastic weights until all tokens reach the final marking.
    Playout,
    /// `pnml_import` (import_export) — Import PNML to Petri net — parses a PNML XML document and reconstructs the place-transition structure for use as a conformance reference model.
    PnmlImport,
    /// `powl_to_process_tree` (import_export) — Convert POWL model to process tree — translates a Partially Ordered Workflow Language model to a block-structured process tree.
    PowlToProcessTree,
    /// `predict_next_activity` (prediction) — Next-activity prediction from trace prefix — encodes the trace prefix as a feature vector and predicts the most likely next activity.
    PredictNextActivity,
    /// `predict_outcome` (prediction) — Case outcome prediction — predicts the final outcome of a running case from its prefix using a trained binary or multi-class classifier.
    PredictOutcome,
    /// `predict_remaining_time` (prediction) — Remaining time prediction from trace prefix — estimates time until case completion using a regression model trained on completed cases.
    PredictRemainingTime,
    /// `process_skeleton` (discovery) — Minimal skeleton DFG — retains only the highest-frequency directly-follows arcs to produce a sparse backbone of the process.
    ProcessSkeleton,
    /// `pso` (discovery) — Particle Swarm Optimisation discovery — maintains a swarm of candidate models whose positions evolve toward the global best according to social and cognitive acceleration.
    Pso,
    /// `simd_streaming_dfg` (discovery) — SIMD-accelerated streaming DFG — processes the event log in a single pass using SIMD vector intrinsics for maximum throughput on large logs.
    SimdStreamingDfg,
    /// `simulated_annealing` (discovery) — Simulated Annealing stochastic search — probabilistically accepts worse candidate models according to a cooling schedule to escape local optima.
    SimulatedAnnealing,
    /// `smart_engine` (discovery) — Auto-selects the best algorithm for the input characteristics — inspects log size, variant count, and noise level, then dispatches to the most appropriate discovery algorithm.
    SmartEngine,
    /// `streaming_log` (discovery) — Streaming event log ingestion — processes events in arrival order without materialising the full log in memory; emits running DFG statistics.
    StreamingLog,
    /// `transition_system` (discovery) — Transition system from event log — constructs a finite-state automaton where states are abstractions of trace history and arcs are activity labels.
    TransitionSystem,
    /// `working_together_network` (discovery_analytics) — Social network: co-worker collaboration — arcs represent how frequently two resources work on the same case, regardless of handover direction.
    WorkingTogetherNetwork,
    /// `yawl_export` (import_export) — Export process model to YAWL format — serialises a discovered process model as a YAWL specification for import into YAWL-compatible workflow engines.
    YawlExport,
}

/// One catalog row: identity + call metadata for a wasm4pm algorithm.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AlgorithmInfo {
    pub id: AlgorithmId,
    /// Canonical snake_case identifier (matches the wasm4pm Rust enum id()).
    pub algorithm_id: &'static str,
    /// PascalCase label (the enum variant name).
    pub label: &'static str,
    /// Functional category (discovery | conformance | prediction | simulation | ...).
    pub category: &'static str,
    /// WASM-exported function name callable on the wasm4pm module.
    pub wasm_export: &'static str,
    /// CLI alias for `wpm run` — empty when the algorithm has no alias.
    pub cli_alias: &'static str,
}

/// The full catalog, ordered by `algorithm_id`.
pub const CATALOG: &[AlgorithmInfo] = &[
    AlgorithmInfo {
        id: AlgorithmId::AStar,
        algorithm_id: "a_star",
        label: "AStar",
        category: "discovery",
        wasm_export: "discover_a_star",
        cli_alias: "astar",
    },
    AlgorithmInfo {
        id: AlgorithmId::Aco,
        algorithm_id: "aco",
        label: "Aco",
        category: "discovery",
        wasm_export: "discover_aco",
        cli_alias: "ant-colony",
    },
    AlgorithmInfo {
        id: AlgorithmId::AgenticPipeline,
        algorithm_id: "agentic_pipeline",
        label: "AgenticPipeline",
        category: "agentic",
        wasm_export: "run_agentic_pipeline",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::Alignments,
        algorithm_id: "alignments",
        label: "Alignments",
        category: "conformance",
        wasm_export: "compute_alignments",
        cli_alias: "alignment",
    },
    AlgorithmInfo {
        id: AlgorithmId::AlphaPlusPlus,
        algorithm_id: "alpha_plus_plus",
        label: "AlphaPlusPlus",
        category: "discovery",
        wasm_export: "discover_alpha_plus_plus",
        cli_alias: "alpha",
    },
    AlgorithmInfo {
        id: AlgorithmId::AnalyzeProcessSpeedup,
        algorithm_id: "analyze_process_speedup",
        label: "AnalyzeProcessSpeedup",
        category: "discovery_analytics",
        wasm_export: "analyze_process_speedup",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::AnalyzeVariantComplexity,
        algorithm_id: "analyze_variant_complexity",
        label: "AnalyzeVariantComplexity",
        category: "discovery_analytics",
        wasm_export: "analyze_variant_complexity",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::AutomlClassify,
        algorithm_id: "automl_classify",
        label: "AutomlClassify",
        category: "ml_analytics",
        wasm_export: "automl_classify",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::AutomlForecast,
        algorithm_id: "automl_forecast",
        label: "AutomlForecast",
        category: "ml_analytics",
        wasm_export: "automl_forecast",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::Batches,
        algorithm_id: "batches",
        label: "Batches",
        category: "discovery_analytics",
        wasm_export: "analyze_batches",
        cli_alias: "batches",
    },
    AlgorithmInfo {
        id: AlgorithmId::BpmnImport,
        algorithm_id: "bpmn_import",
        label: "BpmnImport",
        category: "import_export",
        wasm_export: "read_bpmn",
        cli_alias: "import-bpmn",
    },
    AlgorithmInfo {
        id: AlgorithmId::CausalGraph,
        algorithm_id: "causal_graph",
        label: "CausalGraph",
        category: "discovery_analytics",
        wasm_export: "compute_causal_graph",
        cli_alias: "causal-graph",
    },
    AlgorithmInfo {
        id: AlgorithmId::ComplexityMetrics,
        algorithm_id: "complexity_metrics",
        label: "ComplexityMetrics",
        category: "conformance",
        wasm_export: "compute_complexity_metrics",
        cli_alias: "complexity",
    },
    AlgorithmInfo {
        id: AlgorithmId::ComputeActivityTransitionMatrix,
        algorithm_id: "compute_activity_transition_matrix",
        label: "ComputeActivityTransitionMatrix",
        category: "discovery_analytics",
        wasm_export: "compute_activity_transition_matrix",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::ComputeEwma,
        algorithm_id: "compute_ewma",
        label: "ComputeEwma",
        category: "prediction",
        wasm_export: "compute_ewma",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::ComputeTraceSimilarityMatrix,
        algorithm_id: "compute_trace_similarity_matrix",
        label: "ComputeTraceSimilarityMatrix",
        category: "discovery_analytics",
        wasm_export: "compute_trace_similarity_matrix",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::CorrelationMiner,
        algorithm_id: "correlation_miner",
        label: "CorrelationMiner",
        category: "discovery_analytics",
        wasm_export: "compute_correlation_miner",
        cli_alias: "correlation",
    },
    AlgorithmInfo {
        id: AlgorithmId::Declare,
        algorithm_id: "declare",
        label: "Declare",
        category: "discovery",
        wasm_export: "discover_declare",
        cli_alias: "declare",
    },
    AlgorithmInfo {
        id: AlgorithmId::DetectDrift,
        algorithm_id: "detect_drift",
        label: "DetectDrift",
        category: "prediction",
        wasm_export: "detect_drift",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::Dfg,
        algorithm_id: "dfg",
        label: "Dfg",
        category: "discovery",
        wasm_export: "discover_dfg",
        cli_alias: "dfg",
    },
    AlgorithmInfo {
        id: AlgorithmId::EtconformancePrecision,
        algorithm_id: "etconformance_precision",
        label: "EtconformancePrecision",
        category: "conformance",
        wasm_export: "compute_align_etconformance_precision",
        cli_alias: "etconformance",
    },
    AlgorithmInfo {
        id: AlgorithmId::Generalization,
        algorithm_id: "generalization",
        label: "Generalization",
        category: "conformance",
        wasm_export: "generalization",
        cli_alias: "generalization",
    },
    AlgorithmInfo {
        id: AlgorithmId::GeneticAlgorithm,
        algorithm_id: "genetic_algorithm",
        label: "GeneticAlgorithm",
        category: "discovery",
        wasm_export: "discover_genetic_algorithm",
        cli_alias: "genetic",
    },
    AlgorithmInfo {
        id: AlgorithmId::HandoverNetwork,
        algorithm_id: "handover_network",
        label: "HandoverNetwork",
        category: "discovery_analytics",
        wasm_export: "compute_handover_network",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::HeuristicMiner,
        algorithm_id: "heuristic_miner",
        label: "HeuristicMiner",
        category: "discovery",
        wasm_export: "discover_heuristic_miner",
        cli_alias: "heuristic",
    },
    AlgorithmInfo {
        id: AlgorithmId::HierarchicalDfg,
        algorithm_id: "hierarchical_dfg",
        label: "HierarchicalDfg",
        category: "discovery",
        wasm_export: "discover_hierarchical_dfg",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::HillClimbing,
        algorithm_id: "hill_climbing",
        label: "HillClimbing",
        category: "discovery",
        wasm_export: "discover_hill_climbing",
        cli_alias: "hill-climbing",
    },
    AlgorithmInfo {
        id: AlgorithmId::Ilp,
        algorithm_id: "ilp",
        label: "Ilp",
        category: "discovery",
        wasm_export: "discover_ilp_petri_net",
        cli_alias: "ilp",
    },
    AlgorithmInfo {
        id: AlgorithmId::InductiveMiner,
        algorithm_id: "inductive_miner",
        label: "InductiveMiner",
        category: "discovery",
        wasm_export: "discover_inductive_miner",
        cli_alias: "inductive",
    },
    AlgorithmInfo {
        id: AlgorithmId::LogToTrie,
        algorithm_id: "log_to_trie",
        label: "LogToTrie",
        category: "discovery",
        wasm_export: "discover_log_to_trie",
        cli_alias: "prefix-tree",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlAnomaly,
        algorithm_id: "ml_anomaly",
        label: "MlAnomaly",
        category: "ml_analytics",
        wasm_export: "ml_anomaly",
        cli_alias: "ml-anomaly",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlClassify,
        algorithm_id: "ml_classify",
        label: "MlClassify",
        category: "ml_analytics",
        wasm_export: "ml_classify",
        cli_alias: "ml-classify",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlCluster,
        algorithm_id: "ml_cluster",
        label: "MlCluster",
        category: "ml_analytics",
        wasm_export: "ml_cluster",
        cli_alias: "ml-cluster",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlForecast,
        algorithm_id: "ml_forecast",
        label: "MlForecast",
        category: "ml_analytics",
        wasm_export: "ml_forecast",
        cli_alias: "ml-forecast",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlPca,
        algorithm_id: "ml_pca",
        label: "MlPca",
        category: "ml_analytics",
        wasm_export: "ml_pca",
        cli_alias: "ml-pca",
    },
    AlgorithmInfo {
        id: AlgorithmId::MlRegress,
        algorithm_id: "ml_regress",
        label: "MlRegress",
        category: "ml_analytics",
        wasm_export: "ml_regress",
        cli_alias: "ml-regress",
    },
    AlgorithmInfo {
        id: AlgorithmId::MonteCarloSimulation,
        algorithm_id: "monte_carlo_simulation",
        label: "MonteCarloSimulation",
        category: "simulation",
        wasm_export: "monte_carlo_simulation",
        cli_alias: "montecarlo",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelDfg,
        algorithm_id: "ocel_dfg",
        label: "OcelDfg",
        category: "object_centric",
        wasm_export: "discover_ocel_dfg",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelDfgPerType,
        algorithm_id: "ocel_dfg_per_type",
        label: "OcelDfgPerType",
        category: "object_centric",
        wasm_export: "discover_ocel_dfg_per_type",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelEncode,
        algorithm_id: "ocel_encode",
        label: "OcelEncode",
        category: "object_centric",
        wasm_export: "encode_ocel",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelOcDeclare,
        algorithm_id: "ocel_oc_declare",
        label: "OcelOcDeclare",
        category: "object_centric",
        wasm_export: "discover_ocel_oc_declare",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelOcla,
        algorithm_id: "ocel_ocla",
        label: "OcelOcla",
        category: "object_centric",
        wasm_export: "discover_ocel_ocla",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OcelPetriNet,
        algorithm_id: "ocel_petri_net",
        label: "OcelPetriNet",
        category: "object_centric",
        wasm_export: "discover_ocel_petri_net",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::OptimizedDfg,
        algorithm_id: "optimized_dfg",
        label: "OptimizedDfg",
        category: "discovery",
        wasm_export: "discover_optimized_dfg",
        cli_alias: "dfg-optimized",
    },
    AlgorithmInfo {
        id: AlgorithmId::PerformanceSpectrum,
        algorithm_id: "performance_spectrum",
        label: "PerformanceSpectrum",
        category: "discovery_analytics",
        wasm_export: "compute_performance_spectrum",
        cli_alias: "perf-spectrum",
    },
    AlgorithmInfo {
        id: AlgorithmId::Playout,
        algorithm_id: "playout",
        label: "Playout",
        category: "simulation",
        wasm_export: "petri_net_playout",
        cli_alias: "playout",
    },
    AlgorithmInfo {
        id: AlgorithmId::PnmlImport,
        algorithm_id: "pnml_import",
        label: "PnmlImport",
        category: "import_export",
        wasm_export: "from_pnml_wasm",
        cli_alias: "import-pnml",
    },
    AlgorithmInfo {
        id: AlgorithmId::PowlToProcessTree,
        algorithm_id: "powl_to_process_tree",
        label: "PowlToProcessTree",
        category: "import_export",
        wasm_export: "convert_powl_to_process_tree",
        cli_alias: "powl-to-tree",
    },
    AlgorithmInfo {
        id: AlgorithmId::PredictNextActivity,
        algorithm_id: "predict_next_activity",
        label: "PredictNextActivity",
        category: "prediction",
        wasm_export: "predict_next_activity",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::PredictOutcome,
        algorithm_id: "predict_outcome",
        label: "PredictOutcome",
        category: "prediction",
        wasm_export: "predict_outcome",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::PredictRemainingTime,
        algorithm_id: "predict_remaining_time",
        label: "PredictRemainingTime",
        category: "prediction",
        wasm_export: "predict_case_duration",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::ProcessSkeleton,
        algorithm_id: "process_skeleton",
        label: "ProcessSkeleton",
        category: "discovery",
        wasm_export: "discover_process_skeleton",
        cli_alias: "skeleton",
    },
    AlgorithmInfo {
        id: AlgorithmId::Pso,
        algorithm_id: "pso",
        label: "Pso",
        category: "discovery",
        wasm_export: "discover_pso",
        cli_alias: "pso",
    },
    AlgorithmInfo {
        id: AlgorithmId::SimdStreamingDfg,
        algorithm_id: "simd_streaming_dfg",
        label: "SimdStreamingDfg",
        category: "discovery",
        wasm_export: "discover_dfg_simd",
        cli_alias: "simd-dfg",
    },
    AlgorithmInfo {
        id: AlgorithmId::SimulatedAnnealing,
        algorithm_id: "simulated_annealing",
        label: "SimulatedAnnealing",
        category: "discovery",
        wasm_export: "discover_simulated_annealing",
        cli_alias: "simulated-annealing",
    },
    AlgorithmInfo {
        id: AlgorithmId::SmartEngine,
        algorithm_id: "smart_engine",
        label: "SmartEngine",
        category: "discovery",
        wasm_export: "discover_smart_engine",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::StreamingLog,
        algorithm_id: "streaming_log",
        label: "StreamingLog",
        category: "discovery",
        wasm_export: "discover_streaming_log",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::TransitionSystem,
        algorithm_id: "transition_system",
        label: "TransitionSystem",
        category: "discovery",
        wasm_export: "discover_transition_system",
        cli_alias: "transition-system",
    },
    AlgorithmInfo {
        id: AlgorithmId::WorkingTogetherNetwork,
        algorithm_id: "working_together_network",
        label: "WorkingTogetherNetwork",
        category: "discovery_analytics",
        wasm_export: "compute_working_together_network",
        cli_alias: "",
    },
    AlgorithmInfo {
        id: AlgorithmId::YawlExport,
        algorithm_id: "yawl_export",
        label: "YawlExport",
        category: "import_export",
        wasm_export: "export_yawl",
        cli_alias: "export-yawl",
    },
];

impl AlgorithmId {
    /// Canonical snake_case identifier for this algorithm.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AStar => "a_star",
            Self::Aco => "aco",
            Self::AgenticPipeline => "agentic_pipeline",
            Self::Alignments => "alignments",
            Self::AlphaPlusPlus => "alpha_plus_plus",
            Self::AnalyzeProcessSpeedup => "analyze_process_speedup",
            Self::AnalyzeVariantComplexity => "analyze_variant_complexity",
            Self::AutomlClassify => "automl_classify",
            Self::AutomlForecast => "automl_forecast",
            Self::Batches => "batches",
            Self::BpmnImport => "bpmn_import",
            Self::CausalGraph => "causal_graph",
            Self::ComplexityMetrics => "complexity_metrics",
            Self::ComputeActivityTransitionMatrix => "compute_activity_transition_matrix",
            Self::ComputeEwma => "compute_ewma",
            Self::ComputeTraceSimilarityMatrix => "compute_trace_similarity_matrix",
            Self::CorrelationMiner => "correlation_miner",
            Self::Declare => "declare",
            Self::DetectDrift => "detect_drift",
            Self::Dfg => "dfg",
            Self::EtconformancePrecision => "etconformance_precision",
            Self::Generalization => "generalization",
            Self::GeneticAlgorithm => "genetic_algorithm",
            Self::HandoverNetwork => "handover_network",
            Self::HeuristicMiner => "heuristic_miner",
            Self::HierarchicalDfg => "hierarchical_dfg",
            Self::HillClimbing => "hill_climbing",
            Self::Ilp => "ilp",
            Self::InductiveMiner => "inductive_miner",
            Self::LogToTrie => "log_to_trie",
            Self::MlAnomaly => "ml_anomaly",
            Self::MlClassify => "ml_classify",
            Self::MlCluster => "ml_cluster",
            Self::MlForecast => "ml_forecast",
            Self::MlPca => "ml_pca",
            Self::MlRegress => "ml_regress",
            Self::MonteCarloSimulation => "monte_carlo_simulation",
            Self::OcelDfg => "ocel_dfg",
            Self::OcelDfgPerType => "ocel_dfg_per_type",
            Self::OcelEncode => "ocel_encode",
            Self::OcelOcDeclare => "ocel_oc_declare",
            Self::OcelOcla => "ocel_ocla",
            Self::OcelPetriNet => "ocel_petri_net",
            Self::OptimizedDfg => "optimized_dfg",
            Self::PerformanceSpectrum => "performance_spectrum",
            Self::Playout => "playout",
            Self::PnmlImport => "pnml_import",
            Self::PowlToProcessTree => "powl_to_process_tree",
            Self::PredictNextActivity => "predict_next_activity",
            Self::PredictOutcome => "predict_outcome",
            Self::PredictRemainingTime => "predict_remaining_time",
            Self::ProcessSkeleton => "process_skeleton",
            Self::Pso => "pso",
            Self::SimdStreamingDfg => "simd_streaming_dfg",
            Self::SimulatedAnnealing => "simulated_annealing",
            Self::SmartEngine => "smart_engine",
            Self::StreamingLog => "streaming_log",
            Self::TransitionSystem => "transition_system",
            Self::WorkingTogetherNetwork => "working_together_network",
            Self::YawlExport => "yawl_export",
        }
    }
}

/// Look an algorithm up by the WASM export name it is dispatched through.
pub fn by_wasm_export(export: &str) -> Option<AlgorithmId> {
    match export {
        "discover_a_star" => Some(AlgorithmId::AStar),
        "discover_aco" => Some(AlgorithmId::Aco),
        "run_agentic_pipeline" => Some(AlgorithmId::AgenticPipeline),
        "compute_alignments" => Some(AlgorithmId::Alignments),
        "discover_alpha_plus_plus" => Some(AlgorithmId::AlphaPlusPlus),
        "analyze_process_speedup" => Some(AlgorithmId::AnalyzeProcessSpeedup),
        "analyze_variant_complexity" => Some(AlgorithmId::AnalyzeVariantComplexity),
        "automl_classify" => Some(AlgorithmId::AutomlClassify),
        "automl_forecast" => Some(AlgorithmId::AutomlForecast),
        "analyze_batches" => Some(AlgorithmId::Batches),
        "read_bpmn" => Some(AlgorithmId::BpmnImport),
        "compute_causal_graph" => Some(AlgorithmId::CausalGraph),
        "compute_complexity_metrics" => Some(AlgorithmId::ComplexityMetrics),
        "compute_activity_transition_matrix" => Some(AlgorithmId::ComputeActivityTransitionMatrix),
        "compute_ewma" => Some(AlgorithmId::ComputeEwma),
        "compute_trace_similarity_matrix" => Some(AlgorithmId::ComputeTraceSimilarityMatrix),
        "compute_correlation_miner" => Some(AlgorithmId::CorrelationMiner),
        "discover_declare" => Some(AlgorithmId::Declare),
        "detect_drift" => Some(AlgorithmId::DetectDrift),
        "discover_dfg" => Some(AlgorithmId::Dfg),
        "compute_align_etconformance_precision" => Some(AlgorithmId::EtconformancePrecision),
        "generalization" => Some(AlgorithmId::Generalization),
        "discover_genetic_algorithm" => Some(AlgorithmId::GeneticAlgorithm),
        "compute_handover_network" => Some(AlgorithmId::HandoverNetwork),
        "discover_heuristic_miner" => Some(AlgorithmId::HeuristicMiner),
        "discover_hierarchical_dfg" => Some(AlgorithmId::HierarchicalDfg),
        "discover_hill_climbing" => Some(AlgorithmId::HillClimbing),
        "discover_ilp_petri_net" => Some(AlgorithmId::Ilp),
        "discover_inductive_miner" => Some(AlgorithmId::InductiveMiner),
        "discover_log_to_trie" => Some(AlgorithmId::LogToTrie),
        "ml_anomaly" => Some(AlgorithmId::MlAnomaly),
        "ml_classify" => Some(AlgorithmId::MlClassify),
        "ml_cluster" => Some(AlgorithmId::MlCluster),
        "ml_forecast" => Some(AlgorithmId::MlForecast),
        "ml_pca" => Some(AlgorithmId::MlPca),
        "ml_regress" => Some(AlgorithmId::MlRegress),
        "monte_carlo_simulation" => Some(AlgorithmId::MonteCarloSimulation),
        "discover_ocel_dfg" => Some(AlgorithmId::OcelDfg),
        "discover_ocel_dfg_per_type" => Some(AlgorithmId::OcelDfgPerType),
        "encode_ocel" => Some(AlgorithmId::OcelEncode),
        "discover_ocel_oc_declare" => Some(AlgorithmId::OcelOcDeclare),
        "discover_ocel_ocla" => Some(AlgorithmId::OcelOcla),
        "discover_ocel_petri_net" => Some(AlgorithmId::OcelPetriNet),
        "discover_optimized_dfg" => Some(AlgorithmId::OptimizedDfg),
        "compute_performance_spectrum" => Some(AlgorithmId::PerformanceSpectrum),
        "petri_net_playout" => Some(AlgorithmId::Playout),
        "from_pnml_wasm" => Some(AlgorithmId::PnmlImport),
        "convert_powl_to_process_tree" => Some(AlgorithmId::PowlToProcessTree),
        "predict_next_activity" => Some(AlgorithmId::PredictNextActivity),
        "predict_outcome" => Some(AlgorithmId::PredictOutcome),
        "predict_case_duration" => Some(AlgorithmId::PredictRemainingTime),
        "discover_process_skeleton" => Some(AlgorithmId::ProcessSkeleton),
        "discover_pso" => Some(AlgorithmId::Pso),
        "discover_dfg_simd" => Some(AlgorithmId::SimdStreamingDfg),
        "discover_simulated_annealing" => Some(AlgorithmId::SimulatedAnnealing),
        "discover_smart_engine" => Some(AlgorithmId::SmartEngine),
        "discover_streaming_log" => Some(AlgorithmId::StreamingLog),
        "discover_transition_system" => Some(AlgorithmId::TransitionSystem),
        "compute_working_together_network" => Some(AlgorithmId::WorkingTogetherNetwork),
        "export_yawl" => Some(AlgorithmId::YawlExport),
        _ => None,
    }
}
