//! wasm4pm cognition dispatch-surface skeleton (generated by
//! `wasm4pm-cognition-pack`, ALWAYS regenerated -- `force: true` -- so a
//! new breed added to `ontology.ttl` always gets a wrapper here on the
//! next `ggen sync`).
//!
//! Typed per-breed entry points over the curated stable 6-verb ABI exposed
//! by `wasm4pm-cognition` (`cognition_show`, `cognition_run`,
//! `cognition_verify`, `cognition_replay`, `system_build`, `system_verify`).
//! Each stub delegates to
//! [`w4pm_cognition_dispatch_handler::dispatch_cognition_run`], generated
//! ONCE (see that module) into a separate file the consumer hand-completes
//! -- splitting the always-regenerated wrapper surface from the
//! hand-completed handler is this pack's freeze-slot mechanism: adding
//! breed #56 regenerates this file safely without touching or reverting
//! the consumer's hand-written handler body. Caller surface only: no
//! evidence, witness, or receipt schemas live here.

pub use crate::w4pm_cognition_dispatch_handler::dispatch_cognition_run;

/// Run the `AbductiveIbe` cognition breed (`abductive_ibe`).
///
/// Citation: Harman, G. H. (1965). The Inference to the Best Explanation. The Philosophical Review, 74(1), 88–95. Thagard, P. R. (1978). The Best Explanation: Criteria for Theory Choice. The Journal of Philosophy, 75(2), 76–92.
pub fn run_abductive_ibe(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("abductive_ibe", input_json)
}

/// Run the `AbductiveLp` cognition breed (`abductive_lp`).
///
/// Citation: Kakas, A. C., Kowalski, R. A., & Toni, F. (1992). Abductive Logic Programming. Journal of Logic and Computation, 2(6), 719–770.
pub fn run_abductive_lp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("abductive_lp", input_json)
}

/// Run the `ActR` cognition breed (`act_r`).
///
/// Citation: Anderson, J. R., & Lebiere, C. (1998). Lawrence Erlbaum Associates. Chapter 3 (the activation equation A_i = B_i + Σ_j W_j·S_ji) and Chapter 9 (cognitive arithmetic: retrieval of addition facts).
pub fn run_act_r(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("act_r", input_json)
}

/// Run the `AllenTemporal` cognition breed (`allen_temporal`).
///
/// Citation: Allen, J. F. (1983). Maintaining Knowledge about Temporal Intervals. Communications of the ACM, 26(11), 832-843.
pub fn run_allen_temporal(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("allen_temporal", input_json)
}

/// Run the `AnalogySme` cognition breed (`analogy_sme`).
///
/// Citation: Falkenhainer, B., Forbus, K. D., & Gentner, D. (1989). Artificial Intelligence, 41(1), 1-63.
pub fn run_analogy_sme(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("analogy_sme", input_json)
}

/// Run the `Asp` cognition breed (`asp`).
///
/// Citation: Gelfond, M., & Lifschitz, V. (1988). The Stable Model Semantics for Logic Programming. In: Proceedings of the Fifth International Conference and Symposium on Logic Programming (ICLP/SLP 1988), MIT Press, pp. 1070–1080.
pub fn run_asp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("asp", input_json)
}

/// Run the `AutoinstinctLearning` cognition breed (`autoinstinct_learning`).
///
/// Citation: Sussman, Gerald Jay. "A Computational Model of Skill Acquisition." MIT Artificial Intelligence Laboratory Technical Report AI TR-297, August 1973. Thesis Supervisor: Seymour A. Papert.
pub fn run_autoinstinct_learning(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("autoinstinct_learning", input_json)
}

/// Run the `AutoinstinctNeurosis` cognition breed (`autoinstinct_neurosis`).
///
/// Citation: Boden, M. A. (1977). Artificial Intelligence and Natural Man. New York: Basic Books. Chapter 6: "Programs That Model the Mind." [Conflict detection framework: neurosis as simultaneous maintenance of mutually incompatible beliefs, pp. 198–212.]
pub fn run_autoinstinct_neurosis(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("autoinstinct_neurosis", input_json)
}

/// Run the `AutoinstinctSemantics` cognition breed (`autoinstinct_semantics`).
///
/// Citation: Schank, R. C. (1972). Conceptual dependency: A theory of natural language understanding. Cognitive Psychology, 3(4), 552–631. https://doi.org/10.1016/0010-0285(72)90022-9
pub fn run_autoinstinct_semantics(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("autoinstinct_semantics", input_json)
}

/// Run the `AutoinstinctVision` cognition breed (`autoinstinct_vision`).
///
/// Citation: Marr, D., & Poggio, T. (1976). Cooperative computation of stereo disparity. Science, 194(4262), 283–287. https://doi.org/10.1126/science.968816
pub fn run_autoinstinct_vision(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("autoinstinct_vision", input_json)
}

/// Run the `BayesianNetwork` cognition breed (`bayesian_network`).
///
/// Citation: Pearl, J. (1988). Probabilistic Reasoning in Intelligent Systems: Networks of Plausible Inference. Morgan Kaufmann.
pub fn run_bayesian_network(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("bayesian_network", input_json)
}

/// Run the `BeliefMerging` cognition breed (`belief_merging`).
///
/// Citation: Konieczny, S., & Pino Pérez, R. (2002). Merging Information Under Constraints: A Logical Framework. Journal of Logic and Computation, 12(5), 773–808.
pub fn run_belief_merging(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("belief_merging", input_json)
}

/// Run the `Cbr` cognition breed (`cbr`).
///
/// Citation: A. Aamodt, E. Plaza (1994). Case-Based Reasoning: Foundational Issues, Methodological Variations, and System Approaches. AI Communications, IOS Press, Vol. 7, No. 1, pp. 39–59.
pub fn run_cbr(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("cbr", input_json)
}

/// Run the `Circumscription` cognition breed (`circumscription`).
///
/// Citation: McCarthy, J. (1980). Artificial Intelligence, 13(1-2), 27-39.
pub fn run_circumscription(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("circumscription", input_json)
}

/// Run the `Clp` cognition breed (`clp`).
///
/// Citation: Jaffar, J., & Lassez, J.-L. (1987). Constraint Logic Programming. In: Proceedings of the 14th ACM SIGACT-SIGPLAN Symposium on Principles of Programming Languages (POPL 1987), pp. 111–119.
pub fn run_clp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("clp", input_json)
}

/// Run the `ConstructionGrammar` cognition breed (`construction_grammar`).
///
/// Citation: Adele E. Goldberg (1995). Constructions: A Construction Grammar Approach to Argument Structure. University of Chicago Press.
pub fn run_construction_grammar(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("construction_grammar", input_json)
}

/// Run the `ContingentPlan` cognition breed (`contingent_plan`).
///
/// Citation: Stuart Russell and Peter Norvig (2010). Artificial Intelligence: A Modern Approach (3rd ed.). Pearson.
pub fn run_contingent_plan(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("contingent_plan", input_json)
}

/// Run the `CspAc3` cognition breed (`csp_ac3`).
///
/// Citation: Mackworth, A. K. (1977). Consistency in Networks of Relations. Artificial Intelligence, 8(1), 99-118.
pub fn run_csp_ac3(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("csp_ac3", input_json)
}

/// Run the `CtlCheck` cognition breed (`ctl_check`).
///
/// Citation: Clarke, E. M., Emerson, E. A., & Sistla, A. P. (1986). ACM Transactions on Programming Languages and Systems, 8(2), 244-263.
pub fn run_ctl_check(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("ctl_check", input_json)
}

/// Run the `DefaultLogic` cognition breed (`default_logic`).
///
/// Citation: Reiter, R. (1980). A Logic for Default Reasoning. Artificial Intelligence, 13(1-2), 81-132.
pub fn run_default_logic(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("default_logic", input_json)
}

/// Run the `DempsterShafer` cognition breed (`dempster_shafer`).
///
/// Citation: Shafer, G. (1976). A Mathematical Theory of Evidence. Princeton University Press.
pub fn run_dempster_shafer(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("dempster_shafer", input_json)
}

/// Run the `Dendral` cognition breed (`dendral`).
///
/// Citation: Feigenbaum, E. A., Buchanan, B. G., & Lederberg, J. (1971). On generality and problem solving: A case study using the DENDRAL program. Stanford Artificial Intelligence Project Memo AIM-131, Computer Science Department Report CS176. Stanford University.
pub fn run_dendral(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("dendral", input_json)
}

/// Run the `DescriptionLogic` cognition breed (`description_logic`).
///
/// Citation: Baader, F., Brandt, S., & Lutz, C. (2005). Pushing the EL Envelope. In: Proceedings of the 19th International Joint Conference on Artificial Intelligence (IJCAI 2005), pp. 364–369.
pub fn run_description_logic(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("description_logic", input_json)
}

/// Run the `Ebl` cognition breed (`ebl`).
///
/// Citation: Mitchell, T. M., Keller, R. M., & Kedar-Cabelli, S. T. (1986). Explanation-Based Generalization: A Unifying View. Machine Learning, 1(1), 47-80.
pub fn run_ebl(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("ebl", input_json)
}

/// Run the `Eliza` cognition breed (`eliza`).
///
/// Citation: Weizenbaum, J. (1966). ELIZA—A computer program for the study of natural language communication between man and machine. Communications of the ACM, 9(1), 36–45. https://doi.org/10.1145/365153.365168
pub fn run_eliza(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("eliza", input_json)
}

/// Run the `EpisodicMemory` cognition breed (`episodic_memory`).
///
/// Citation: Tulving, E. (1983). Oxford University Press (Ch. 7: encoding specificity and temporal organisation). Nuxoll, A. M., & Laird, J. E. (2007). Proceedings of AAAI 2007, 1560-1565 (cue-based retrieval of the best partially-matching episode).
pub fn run_episodic_memory(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("episodic_memory", input_json)
}

/// Run the `EventCalculus` cognition breed (`event_calculus`).
///
/// Citation: Kowalski, R., & Sergot, M. (1986). A Logic-based Calculus of Events. New Generation Computing, 4(1), 67–95.
pub fn run_event_calculus(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("event_calculus", input_json)
}

/// Run the `FramesInheritance` cognition breed (`frames_inheritance`).
///
/// Citation: Minsky, M. (1974). A Framework for Representing Knowledge. MIT AI Laboratory Memo 306. Reprinted in Winston (Ed.), The Psychology of Computer Vision, 1975.
pub fn run_frames_inheritance(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("frames_inheritance", input_json)
}

/// Run the `FuzzyLogic` cognition breed (`fuzzy_logic`).
///
/// Citation: Mamdani, E. H., & Assilian, S. (1975). An Experiment in Linguistic Synthesis with a Fuzzy Logic Controller. International Journal of Man-Machine Studies, 7(1), 1-13.
pub fn run_fuzzy_logic(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("fuzzy_logic", input_json)
}

/// Run the `Gps` cognition breed (`gps`).
///
/// Citation: A. Newell and H. A. Simon, "GPS, A Program That Simulates Human Thought," RAND Corporation, P-2257, March 30, 1961 (Revised April 10, 1961). Presented at the Conference on Learning Automata, Karlsruhe, Germany, April 11–14, 1961.
pub fn run_gps(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("gps", input_json)
}

/// Run the `Hearsay` cognition breed (`hearsay`).
///
/// Citation: Erman, L. D., Hayes-Roth, F., Lesser, V. R., and Reddy, D. R. (1980). The Hearsay-II speech-understanding system: Integrating knowledge to resolve uncertainty. ACM Computing Surveys, 12(2), 213–253.
pub fn run_hearsay(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("hearsay", input_json)
}

/// Run the `HtnPlanning` cognition breed (`htn_planning`).
///
/// Citation: Nau, D., Au, T.-C., Ilghami, O., Kuter, U., Murdock, J. W., Wu, D., & Yaman, F. (2003). SHOP2: An HTN Planning System. Journal of Artificial Intelligence Research, 20, 379-404.
pub fn run_htn_planning(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("htn_planning", input_json)
}

/// Run the `Ilp` cognition breed (`ilp`).
///
/// Citation: Quinlan, J. R. (1990). Machine Learning, 5(3), 239-266.
pub fn run_ilp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("ilp", input_json)
}

/// Run the `LtlMonitor` cognition breed (`ltl_monitor`).
///
/// Citation: Havelund, K., & Rosu, G. (2001). Monitoring Programs Using Rewriting. Proceedings of ASE 2001 (16th IEEE International Conference on Automated Software Engineering), 135-143.
pub fn run_ltl_monitor(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("ltl_monitor", input_json)
}

/// Run the `MarkovLogic` cognition breed (`markov_logic`).
///
/// Citation: Matthew Richardson and Pedro Domingos (2006). Markov logic networks. Machine Learning 62(1-2):107-136.
pub fn run_markov_logic(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("markov_logic", input_json)
}

/// Run the `Mdp` cognition breed (`mdp`).
///
/// Citation: Bellman, R. (1957). Dynamic Programming. Princeton University Press. (Functional equation / principle of optimality, Chapter III; successive-approximation solution, Chapter IV.)
pub fn run_mdp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("mdp", input_json)
}

/// Run the `MetaReasoning` cognition breed (`meta_reasoning`).
///
/// Citation: Michael T. Cox and Anita Raja (eds.) (2011). Metareasoning: Thinking about Thinking. MIT Press.
pub fn run_meta_reasoning(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("meta_reasoning", input_json)
}

/// Run the `Morphological` cognition breed (`morphological`).
///
/// Citation: Zwicky, F. (1969). Discovery, Invention, Research Through the Morphological Approach. Macmillan.
pub fn run_morphological(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("morphological", input_json)
}

/// Run the `Mycin` cognition breed (`mycin`).
///
/// Citation: Shortliffe, E. H., & Buchanan, B. G. (1975). A model of inexact reasoning in medicine. Mathematical Biosciences, 23(3–4), 351–379. Reprinted as Chapter 11 in: Buchanan, B. G., & Shortliffe, E. H. (Eds.), Rule-Based Expert Systems. Addison-Wesley, 1984.
pub fn run_mycin(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("mycin", input_json)
}

/// Run the `NaivePhysics` cognition breed (`naive_physics`).
///
/// Citation: Hayes, P. J. (1979). In D. Michie (Ed.), Expert Systems in the Micro-Electronic Age. Edinburgh University Press. Hayes, P. J. (1985). In J. R. Hobbs & R. C. Moore (Eds.), Formal Theories of the Commonsense World (pp. 71-107). Ablex.
pub fn run_naive_physics(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("naive_physics", input_json)
}

/// Run the `OcpmRouteDiscoverer` cognition breed (`ocpm_route_discoverer`).
///
/// Citation: van der Aalst, W.M.P. (2019). Object-Centric Process Mining: Dealing with Divergence and Convergence.
pub fn run_ocpm_route_discoverer(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("ocpm_route_discoverer", input_json)
}

/// Run the `PartialOrderPlan` cognition breed (`partial_order_plan`).
///
/// Citation: McAllester, D., & Rosenblitt, D. (1991). Systematic Nonlinear Planning. In: Proceedings of the Ninth National Conference on Artificial Intelligence (AAAI-91), pp. 634–639.
pub fn run_partial_order_plan(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("partial_order_plan", input_json)
}

/// Run the `Pomdp` cognition breed (`pomdp`).
///
/// Citation: Leslie Pack Kaelbling, Michael L. Littman and Anthony R. Cassandra (1998). Planning and acting in partially observable stochastic domains. Artificial Intelligence 101(1-2):99-134.
pub fn run_pomdp(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("pomdp", input_json)
}

/// Run the `Problog` cognition breed (`problog`).
///
/// Citation: De Raedt, L., Kimmig, A., & Toivonen, H. (2007). Proceedings of IJCAI 2007, 2468-2473.
pub fn run_problog(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("problog", input_json)
}

/// Run the `Prolog` cognition breed (`prolog`).
///
/// Citation: Kowalski, R. A. (1974). Predicate logic as programming language. IFIP Congress 74, Stockholm, pp. 569–574.
pub fn run_prolog(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("prolog", input_json)
}

/// Run the `QualitativeReason` cognition breed (`qualitative_reason`).
///
/// Citation: de Kleer, J., & Brown, J. S. (1984). A Qualitative Physics Based on Confluences. Artificial Intelligence, 24(1–3), 7–83.
pub fn run_qualitative_reason(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("qualitative_reason", input_json)
}

/// Run the `RlSymbolic` cognition breed (`rl_symbolic`).
///
/// Citation: Watkins, C. J. C. H., & Dayan, P. (1992). Machine Learning, 8(3-4), 279-292.
pub fn run_rl_symbolic(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("rl_symbolic", input_json)
}

/// Run the `SatCdcl` cognition breed (`sat_cdcl`).
///
/// Citation: Marques-Silva, J. P., & Sakallah, K. A. (1999). IEEE Transactions on Computers, 48(5), 506-521.
pub fn run_sat_cdcl(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("sat_cdcl", input_json)
}

/// Run the `ScriptSam` cognition breed (`script_sam`).
///
/// Citation: Schank, R. C., & Abelson, R. P. (1977). Scripts, Plans, Goals and Understanding: An Inquiry into Human Knowledge Structures. Lawrence Erlbaum Associates.
pub fn run_script_sam(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("script_sam", input_json)
}

/// Run the `SituationCalculus` cognition breed (`situation_calculus`).
///
/// Citation: Reiter, R. (1991). In V. Lifschitz (Ed.), Artificial Intelligence and Mathematical Theory of Computation: Papers in Honor of John McCarthy (pp. 359-380). Academic Press.
pub fn run_situation_calculus(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("situation_calculus", input_json)
}

/// Run the `Soar` cognition breed (`soar`).
///
/// Citation: Laird, J. E., Newell, A., & Rosenbloom, P. S. (1987). Soar: An architecture for general intelligence. Artificial Intelligence, 33(1), 1–64. https://doi.org/10.1016/0004-3702(87)90050-6
pub fn run_soar(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("soar", input_json)
}

/// Run the `Strips` cognition breed (`strips`).
///
/// Citation: Fikes, R. E., & Nilsson, N. J. (1971). STRIPS: A new approach to the application of theorem proving to problem solving. Artificial Intelligence, 2(3–4), 189–208.
pub fn run_strips(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("strips", input_json)
}

/// Run the `Tableaux` cognition breed (`tableaux`).
///
/// Citation: Raymond M. Smullyan (1968). First-Order Logic. Springer-Verlag, Ergebnisse der Mathematik und ihrer Grenzgebiete 43.
pub fn run_tableaux(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("tableaux", input_json)
}

/// Run the `Triz` cognition breed (`triz`).
///
/// Citation: Altshuller, G. (1984). Creativity as an Exact Science. Gordon and Breach Science Publishers.
pub fn run_triz(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("triz", input_json)
}

/// Run the `VersionSpace` cognition breed (`version_space`).
///
/// Citation: Mitchell, T. M. (1982). Generalization as Search. Artificial Intelligence, 18(2), 203–226.
pub fn run_version_space(input_json: &str) -> Result<String, String> {
    dispatch_cognition_run("version_space", input_json)
}
