//! Real, executable certify-pipeline logic precipitated from
//! `packs/affidavit-pack/ontology.ttl`'s `afd:rejectCondition` /
//! `afd:order` facts on `afd:CertifyStage` individuals -- not just a
//! reference table. Two behaviors are actually generated:
//!
//! 1. Stage dispatch (`next_stage` / `is_terminal` / `reject_condition_for`)
//!    -- a real, ordered state machine over the 7 stages, computed from the
//!    ontology's `afd:order` values (adding an 8th stage regenerates a
//!    correct dispatcher automatically).
//! 2. `check_continuity` -- a real, callable implementation of the
//!    `afd:Continuity` stage's `afd:rejectCondition` ("sequenceNumber
//!    values are strictly increasing with no duplicates"). Round 3
//!    (2026-07-18) reworked this from one affidavit-specific hand-written
//!    body into a *composition* of two generic, domain-independent
//!    structural primitives -- `check_strictly_increasing` and
//!    `check_unique` -- dispatched by the `afd:checksMonotonic` /
//!    `afd:checksUnique` boolean facts the ontology now carries per stage
//!    (`STAGE_CHECKS`, generated below). Only `afd:Continuity` currently
//!    sets both flags true, so `check_continuity` is still the only caller,
//!    but the primitives themselves are stage-agnostic: a future stage (or
//!    another pack's ontology reusing this pattern) that sets the same
//!    flags gets the same generated dispatch with zero new hand-written
//!    logic. The other 6 stages require real BLAKE3 receipt bytes this pack
//!    does not parse (modeling ~/affidavit's on-disk receipt format is out
//!    of scope for a label/doc-derived pack), so they have no flags and no
//!    generated check function.
//!
//! Generated by `affidavit-pack`. Reference only -- this crate does not
//! invoke `affi`.

/// One stage of the 7-stage certify pipeline, in ontology order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Stage {
    /// Decode
    Decode,
    /// Format Check
    FormatCheck,
    /// Chain Integrity
    ChainIntegrity,
    /// Continuity
    Continuity,
    /// Commitment Verify
    CommitmentVerify,
    /// Profile Evaluation
    ProfileEvaluation,
    /// Final Verdict
    FinalVerdict,
}

/// All stages in ascending `afd:order`, for iteration/dispatch.
pub const ALL_STAGES: &[Stage] = &[
    Stage::Decode,
    Stage::FormatCheck,
    Stage::ChainIntegrity,
    Stage::Continuity,
    Stage::CommitmentVerify,
    Stage::ProfileEvaluation,
    Stage::FinalVerdict,
];

impl Stage {
    /// 1-based ontology order (`afd:order`).
    pub fn order(self) -> u32 {
        match self {
            Stage::Decode => 1,
            Stage::FormatCheck => 2,
            Stage::ChainIntegrity => 3,
            Stage::Continuity => 4,
            Stage::CommitmentVerify => 5,
            Stage::ProfileEvaluation => 6,
            Stage::FinalVerdict => 7,
        }
    }

    /// The `afd:rejectCondition` literal for this stage (structural
    /// predicate that must hold or the pipeline halts with REJECT here).
    pub fn reject_condition(self) -> &'static str {
        match self {
            Stage::Decode => "receipt bytes deserialize to a well-formed Receipt with a recognized version tag",
            Stage::FormatCheck => "every field required by the core/v1 schema is present and correctly typed",
            Stage::ChainIntegrity => "recomputed BLAKE3 rolling hash over all Events equals the receipt's stored chain seal",
            Stage::Continuity => "afd:sequenceNumber values across all Events are strictly increasing with no duplicates",
            Stage::CommitmentVerify => "every Event's afd:hasCommitment resolves to exactly one well-formed BLAKE3 digest",
            Stage::ProfileEvaluation => "conformance score against the configured profile meets its pass threshold",
            Stage::FinalVerdict => "all 6 prior stages returned no rejection",
        }
    }
}

/// The stage that runs immediately after `current`, or `None` if `current`
/// is the terminal stage (`afd:FinalVerdict`, the highest `afd:order`).
/// Computed from `ALL_STAGES`'s ontology-derived order -- adding an 8th
/// `afd:CertifyStage` individual to the ontology changes this function's
/// behavior on next `ggen sync` with zero template edits.
pub fn next_stage(current: Stage) -> Option<Stage> {
    let idx = ALL_STAGES.iter().position(|s| *s == current)?;
    ALL_STAGES.get(idx + 1).copied()
}

/// True iff `stage` is the last stage in ontology order (no `next_stage`).
pub fn is_terminal(stage: Stage) -> bool {
    next_stage(stage).is_none()
}

/// Per-stage `(afd:checksMonotonic, afd:checksUnique)` flags, in ontology
/// order. Generic structural facts, not affidavit-specific -- a template
/// dispatches on these rather than a human transcribing which stages need
/// which checks.
pub const STAGE_CHECKS: &[(Stage, bool, bool)] = &[
    (Stage::Decode, false, false),
    (Stage::FormatCheck, false, false),
    (Stage::ChainIntegrity, false, false),
    (Stage::Continuity, true, true),
    (Stage::CommitmentVerify, false, false),
    (Stage::ProfileEvaluation, false, false),
    (Stage::FinalVerdict, false, false),
];

/// Generic structural primitive: adjacent values must not *decrease*
/// (strictly-less-than is a violation; equal values are `check_unique`'s
/// concern, kept separate so the two primitives are independently
/// meaningful and independently testable). Domain-independent -- knows
/// nothing about affidavits, receipts, or `afd:Continuity`; reusable by any
/// stage/pack that sets `afd:checksMonotonic`.
pub fn check_strictly_increasing(sequence_numbers: &[u64]) -> Result<(), String> {
    for (i, w) in sequence_numbers.windows(2).enumerate() {
        if w[1] < w[0] {
            return Err(format!(
                "sequenceNumber {} at index {} is not greater than preceding {}, \
                 violating the strictly-increasing requirement",
                w[1], i + 1, w[0]
            ));
        }
    }
    Ok(())
}

/// Generic structural primitive: adjacent values must not repeat.
/// Domain-independent -- reusable by any stage/pack that sets
/// `afd:checksUnique`. Composed with `check_strictly_increasing` (unique
/// checked first, matching `check_stage`'s dispatch order) the pair together
/// enforce the full "strictly increasing with no duplicates" predicate.
pub fn check_unique(sequence_numbers: &[u64]) -> Result<(), String> {
    for (i, w) in sequence_numbers.windows(2).enumerate() {
        if w[1] == w[0] {
            return Err(format!(
                "duplicate sequenceNumber {} at index {} violates the uniqueness requirement",
                w[1], i + 1
            ));
        }
    }
    Ok(())
}

/// Dispatches `sequence_numbers` through whichever of the two generic
/// primitives `stage`'s `STAGE_CHECKS` flags require, composing them
/// fail-fast -- uniqueness first, then strict monotonicity (so a repeated
/// value is reported as a duplicate, not merely "not greater"). Stages with
/// both flags false trivially accept -- there is nothing this pack knows how
/// to check for them yet (see module doc).
pub fn check_stage(stage: Stage, sequence_numbers: &[u64]) -> Result<(), String> {
    let (_, monotonic, unique) = STAGE_CHECKS
        .iter()
        .find(|(s, _, _)| *s == stage)
        .copied()
        .unwrap_or((stage, false, false));
    if unique {
        check_unique(sequence_numbers)?;
    }
    if monotonic {
        check_strictly_increasing(sequence_numbers)?;
    }
    Ok(())
}

/// Real implementation of the `afd:Continuity` stage's reject condition:
/// event sequence numbers must be strictly increasing with no duplicates.
/// Returns `Ok(())` (ACCEPT for this stage) or `Err(reason)` (REJECT),
/// mirroring the ACCEPT/REJECT atomic-verdict semantics `afd:Verdict`
/// describes for the pipeline as a whole. Now a thin, named call into the
/// ontology-driven `check_stage` dispatch (kept for API stability -- prior
/// callers/tests referencing `check_continuity` directly still compile).
pub fn check_continuity(sequence_numbers: &[u64]) -> Result<(), String> {
    check_stage(Stage::Continuity, sequence_numbers)
}
