
/**
 * Generated API request/response types from RDF ontology
 * DO NOT EDIT - auto-generated by ggen sync
 */
/**
 * CreatePostRequest
 */
export interface CreatePostRequest {
  authorId: string;
  content: string;
  title: string;
}


/**
 * UpdatePostRequest
 */
export interface UpdatePostRequest {
  content?: string;
  title?: string;
}


/**
 * CreateUserRequest
 */
export interface CreateUserRequest {
  bio?: string;
  email: string;
  username: string;
}


/**
 * UpdateUserRequest
 */
export interface UpdateUserRequest {
  bio?: string;
  email?: string;
  username?: string;
}
