
/**
 * @fileoverview Generated Zod request schemas from RDF ontology
 * DO NOT EDIT - auto-generated by ggen sync
 * @module generated/request-schemas
 */

import { z } from "zod";
/**
 * createPostRequest validation schema
 */
export const createPostRequestSchema = z.object({
  authorId: z.string().min(1),
  content: z.string().min(1),
  title: z.string().min(1).max(500),
});

/**
 * @typedef {z.infer<typeof createPostRequestSchema>} CreatepostrequestType
 */


/**
 * updatePostRequest validation schema
 */
export const updatePostRequestSchema = z.object({
  content: z.string().min(1).optional(),
  title: z.string().min(1).max(500).optional(),
});

/**
 * @typedef {z.infer<typeof updatePostRequestSchema>} UpdatepostrequestType
 */


/**
 * createUserRequest validation schema
 */
export const createUserRequestSchema = z.object({
  bio: z.string().max(500).optional(),
  email: z.string(),
  username: z.string().min(1).max(255),
});

/**
 * @typedef {z.infer<typeof createUserRequestSchema>} CreateuserrequestType
 */


/**
 * updateUserRequest validation schema
 */
export const updateUserRequestSchema = z.object({
  bio: z.string().max(500).optional(),
  email: z.string().optional(),
  username: z.string().min(1).max(255).optional(),
});

/**
 * @typedef {z.infer<typeof updateUserRequestSchema>} UpdateuserrequestType
 */
