//! Generated by rmcp-pack. Do not edit.
//!
//! SECOND proof for `rmcp:HandlerMethod`, ALONGSIDE `rmcp_handler_catalog_proof.rs.tmpl`
//! (never a replacement for it -- both are generated by every `ggen sync run`). That
//! sibling proof hand-transcribes its expected literals from `ontology.ttl` and
//! deliberately carries no `sparql:` frontmatter key, for a real, disclosed reason
//! (its own header): looping the SAME query that produced `RMCP_SERVER_METHODS`/
//! `RMCP_CLIENT_METHODS` into that test's own expectations would let a wrong
//! field-mapping bug corrupt both identically, and the test could never catch it.
//! That reasoning is correct for what THAT proof checks -- spot-checked rows plus
//! structural invariants (sortedness, no duplicates) -- but it leaves a gap: a
//! hand-transcribed literal is authored once and never auto-updates, so it cannot
//! detect the case where `ontology.ttl` changes LATER and the checked-in generated
//! artifact falls behind it.
//!
//! This proof closes that gap by checking a DIFFERENT thing, not the same thing more
//! strictly: whether `src/rmcp_handler_catalog.rs`, as it actually sits on disk right
//! now, still agrees with what `rmcp:HandlerMethod` individuals say RIGHT NOW. It
//! cannot and does not claim to validate "is the ontology itself correct" (nothing
//! can, that is definitional) -- only "has the checked-in generated module silently
//! drifted from the ontology since it was last written."
//!
//! ## Why this is not the same tautology the sibling proof's header warns about
//! (reapplying `star-toml-pack`'s wave-2 cap05 reference pattern verbatim, see
//! `packs/star-toml-pack/templates/star_toml_config_sparql_derived_proof.rs.tmpl`)
//!
//! 1. Asymmetric freshness, not identical-execution self-agreement.
//!    `rmcp_handler_catalog.rs.tmpl` writes its output under `freeze_policy: checksum`
//!    (`freeze_slots_dir: .ggen/freeze/rmcp-pack`): once a consumer hand-edits
//!    `src/rmcp_handler_catalog.rs`, or an ontology-driven content change lands
//!    without `force: true`, a further sync can leave the checked-in file behind
//!    whatever `ontology.ttl` now says while `ggen sync run` still (eventually)
//!    exits 0. This template carries NO `freeze_policy` of its own: its `LIVE_*`
//!    arrays below are re-baked from a live query against whatever `ontology.ttl`
//!    says at the moment THIS file is (re)generated. So the two sides of every
//!    assertion below are not guaranteed to come from the same sync execution --
//!    one (`RS_CONTENT`, via `include_str!`) is whatever was last actually written
//!    to disk, frozen or not; the other (`LIVE_*`) is always "right now." A
//!    hand-transcribed expectation frozen at authoring time cannot distinguish
//!    those two states from each other; this one can, and fails loudly when they
//!    diverge.
//! 2. Independent rendering, not the same substitution checked twice.
//!    This template's own for-loops over the `server_rows`/`client_rows` SPARQL
//!    results are a SEPARATE Tera render pass from `rmcp_handler_catalog.rs.tmpl`'s
//!    own loops over the identical queries. A field-mapping bug local to ONE of the
//!    two templates (wrong variable, dropped row, stray whitespace, a broken
//!    `replace(from='"', ...)` transform) produces a generated-module string that
//!    this proof's independently-rendered `LIVE_*` values will not match, and the
//!    assertions below fail.
//!
//! ## Honest scope
//!
//! This still compares rendered TEXT via substring search, not a parsed Rust AST --
//! the same limitation the sibling proof's structural test avoids by
//! literal-construction-must-compile instead. It does not repeat the sibling proof's
//! spot-checks / sortedness / no-duplicate invariants (that is that proof's job;
//! duplicating it here would be scope creep, not a second check), nor does it repeat
//! `rmcp_stub_handler_proof.rs`'s real-crate behavioral coverage. It cannot prove
//! ggen's own SPARQL/Tera pipeline is bug-free in some absolute sense -- only that,
//! on the sync run that (re)generated this file, the live ontology and the
//! checked-in generated module said the same thing.

const RS_CONTENT: &str = include_str!("../src/rmcp_handler_catalog.rs");

/// Every `rmcp:HandlerMethod` individual with `rmcp:role "server"` as of the sync
/// run that generated THIS file -- (method_name, params_type, return_type,
/// default_behavior, source_file) -- freshly baked from the `server_rows` SPARQL
/// result, never hand-typed. `default_behavior`/`source_file` go through the exact
/// same `replace(from='"', to="'")` transform `rmcp_handler_catalog.rs.tmpl` itself
/// applies, so the two sides compare like for like.
const LIVE_SERVER_ROWS: &[(&str, &str, &str, &str, &str)] = &[
    (
        "call_tool",
        "CallToolRequestParams",
        "CallToolResult",
        "Returns Err(McpError::method_not_found::<CallToolRequestMethod>()). The method's own real doc comment (lines 283-310) explains a genuine API-design subtlety: Ok(CallToolResult::error(...)) reaches the caller's UI (rendered content), while Err(McpError) is a JSON-RPC protocol error the caller typically cannot read -- almost every 'tool didn't work' path should return the former, not the latter.",
        "src/handler/server.rs:311-317",
    ),
    (
        "cancel_task",
        "CancelTaskParams",
        "CancelTaskResult",
        "Returns Err(McpError::method_not_found::<CancelTaskMethod>()).",
        "src/handler/server.rs:419-426",
    ),
    (
        "complete",
        "CompleteRequestParams",
        "CompleteResult",
        "Returns Ok(CompleteResult::default()).",
        "src/handler/server.rs:214-220",
    ),
    (
        "enqueue_task",
        "CallToolRequestParams",
        "CreateTaskResult",
        "Returns Err(McpError::internal_error('Task processing not implemented', None)) -- task-based tool invocation is opt-in via #[task_handler].",
        "src/handler/server.rs:184-193",
    ),
    (
        "get_info",
        "",
        "ServerInfo",
        "Returns ServerInfo::default() -- the one real sync method every #[tool_handler]/#[prompt_handler]-based server typically overrides (or lets the macro auto-generate).",
        "src/handler/server.rs:389-391",
    ),
    (
        "get_prompt",
        "GetPromptRequestParams",
        "GetPromptResult",
        "Returns Err(McpError::method_not_found::<GetPromptRequestMethod>()).",
        "src/handler/server.rs:228-234",
    ),
    (
        "get_task_info",
        "GetTaskParams",
        "GetTaskResult",
        "Returns Err(McpError::method_not_found::<GetTaskMethod>()).",
        "src/handler/server.rs:401-408",
    ),
    (
        "get_task_result",
        "GetTaskPayloadParams",
        "GetTaskPayloadResult",
        "Returns Err(McpError::method_not_found::<GetTaskPayloadMethod>()).",
        "src/handler/server.rs:410-417",
    ),
    (
        "get_tool",
        "&str",
        "Option<Tool>",
        "Returns None (the one real sync, non-Result method besides get_info; its own doc comment notes returning None bypasses task-support validation, and that #[tool_handler] auto-implements it).",
        "src/handler/server.rs:329-331",
    ),
    (
        "initialize",
        "InitializeRequestParams",
        "InitializeResult",
        "Records the peer's declared info, negotiates the protocol version against self.get_info(), and returns Ok(info) with the negotiated version.",
        "src/handler/server.rs:201-213",
    ),
    (
        "list_prompts",
        "Option<PaginatedRequestParams>",
        "ListPromptsResult",
        "Returns Ok(ListPromptsResult::default()) (an empty prompt list, not an error).",
        "src/handler/server.rs:235-241",
    ),
    (
        "list_resource_templates",
        "Option<PaginatedRequestParams>",
        "ListResourceTemplatesResult",
        "Returns Ok(ListResourceTemplatesResult::default()) (an empty list, not an error).",
        "src/handler/server.rs:249-257",
    ),
    (
        "list_resources",
        "Option<PaginatedRequestParams>",
        "ListResourcesResult",
        "Returns Ok(ListResourcesResult::default()) (an empty resource list, not an error).",
        "src/handler/server.rs:242-248",
    ),
    (
        "list_tasks",
        "Option<PaginatedRequestParams>",
        "ListTasksResult",
        "Returns Err(McpError::method_not_found::<ListTasksMethod>()).",
        "src/handler/server.rs:393-399",
    ),
    (
        "list_tools",
        "Option<PaginatedRequestParams>",
        "ListToolsResult",
        "Returns Ok(ListToolsResult::default()) (an empty tool list, not an error).",
        "src/handler/server.rs:318-324",
    ),
    (
        "on_cancelled",
        "CancelledNotificationParam",
        "()",
        "No-op: returns () (a notification, not a request).",
        "src/handler/server.rs:346-352",
    ),
    (
        "on_custom_notification",
        "CustomNotification",
        "()",
        "No-op: returns ().",
        "src/handler/server.rs:380-387",
    ),
    (
        "on_custom_request",
        "CustomRequest",
        "CustomResult",
        "Returns Err(McpError::new(ErrorCode::METHOD_NOT_FOUND, method, None)) using the custom request's own method name.",
        "src/handler/server.rs:332-344",
    ),
    (
        "on_initialized",
        "",
        "()",
        "Logs 'client initialized' via tracing::info!, then returns ().",
        "src/handler/server.rs:360-366",
    ),
    (
        "on_progress",
        "ProgressNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/server.rs:353-359",
    ),
    (
        "on_roots_list_changed",
        "",
        "()",
        "No-op: returns ().",
        "src/handler/server.rs:367-372",
    ),
    (
        "on_task_status",
        "TaskStatusNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/server.rs:373-379",
    ),
    (
        "ping",
        "",
        "()",
        "Returns Ok(()) unconditionally.",
        "src/handler/server.rs:194-199",
    ),
    (
        "read_resource",
        "ReadResourceRequestParams",
        "ReadResourceResult",
        "Returns Err(McpError::method_not_found::<ReadResourceRequestMethod>()).",
        "src/handler/server.rs:258-266",
    ),
    (
        "set_level",
        "SetLevelRequestParams",
        "()",
        "Returns Err(McpError::method_not_found::<SetLevelRequestMethod>()).",
        "src/handler/server.rs:221-227",
    ),
    (
        "subscribe",
        "SubscribeRequestParams",
        "()",
        "Returns Err(McpError::method_not_found::<SubscribeRequestMethod>()).",
        "src/handler/server.rs:267-273",
    ),
    (
        "unsubscribe",
        "UnsubscribeRequestParams",
        "()",
        "Returns Err(McpError::method_not_found::<UnsubscribeRequestMethod>()).",
        "src/handler/server.rs:274-282",
    ),
];

/// Every `rmcp:HandlerMethod` individual with `rmcp:role "client"` -- same shape as
/// `LIVE_SERVER_ROWS`, freshly baked from the `client_rows` SPARQL result.
const LIVE_CLIENT_ROWS: &[(&str, &str, &str, &str, &str)] = &[
    (
        "create_elicitation",
        "ElicitRequestParams",
        "ElicitResult",
        "Returns Ok(ElicitResult { action: ElicitationAction::Decline, content: None, meta: None }) -- automatically declines every elicitation request; real interactive clients override this. The method's own doc comment (lines 114-169) includes a real, complete `impl ClientHandler for MyClient` example matching on ElicitRequestParams::{FormElicitationParam, UrlElicitationParam}.",
        "src/handler/client.rs:170-182",
    ),
    (
        "create_message",
        "CreateMessageRequestParams",
        "CreateMessageResult",
        "Returns Err(McpError::method_not_found::<CreateMessageRequestMethod>()) -- sampling is opt-in, real clients override this.",
        "src/handler/client.rs:97-105",
    ),
    (
        "get_info",
        "",
        "ClientInfo",
        "Returns ClientInfo::default() -- the one real sync method in ClientHandler.",
        "src/handler/client.rs:268-270",
    ),
    (
        "list_roots",
        "",
        "ListRootsResult",
        "Returns Ok(ListRootsResult::default()) (an empty roots list, not an error).",
        "src/handler/client.rs:107-112",
    ),
    (
        "on_cancelled",
        "CancelledNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:198-204",
    ),
    (
        "on_custom_notification",
        "CustomNotification",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:259-266",
    ),
    (
        "on_custom_request",
        "CustomRequest",
        "CustomResult",
        "Returns Err(McpError::new(ErrorCode::METHOD_NOT_FOUND, method, None)) using the custom request's own method name.",
        "src/handler/client.rs:184-196",
    ),
    (
        "on_logging_message",
        "LoggingMessageNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:212-218",
    ),
    (
        "on_progress",
        "ProgressNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:205-211",
    ),
    (
        "on_prompt_list_changed",
        "",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:238-243",
    ),
    (
        "on_resource_list_changed",
        "",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:226-231",
    ),
    (
        "on_resource_updated",
        "ResourceUpdatedNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:219-225",
    ),
    (
        "on_task_status",
        "TaskStatusNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:252-258",
    ),
    (
        "on_tool_list_changed",
        "",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:232-237",
    ),
    (
        "on_url_elicitation_notification_complete",
        "ElicitationResponseNotificationParam",
        "()",
        "No-op: returns ().",
        "src/handler/client.rs:245-251",
    ),
    (
        "ping",
        "",
        "()",
        "Returns Ok(()) unconditionally.",
        "src/handler/client.rs:90-95",
    ),
];

fn assert_row_present(role: &str, row: &(&str, &str, &str, &str, &str)) {
    let (method_name, params_type, return_type, default_behavior, source_file) = *row;
    let needle = format!(
        "role: \"{role}\", method_name: \"{method_name}\", params_type: \"{params_type}\", \
         return_type: \"{return_type}\", default_behavior: \"{default_behavior}\", \
         source_file: \"{source_file}\" }},"
    );
    assert!(
        RS_CONTENT.contains(&needle),
        "live ontology has rmcp:HandlerMethod `{method_name}` (role {role}) with \
         params_type={params_type:?} return_type={return_type:?} \
         default_behavior={default_behavior:?} source_file={source_file:?}, but generated \
         src/rmcp_handler_catalog.rs does not contain a matching RmcpHandlerMethod row -- \
         generated module has drifted behind ontology.ttl. Looked for: {needle:?}"
    );
}

/// Floor sanity check: guards against a silently-broken or silently-empty SPARQL
/// query (e.g. a query engine regression, a typo in the query text that still
/// parses but matches nothing) making every loop-based assertion below vacuously
/// true. If this fails, the failure is in a query itself, not in drift between the
/// ontology and the generated module.
#[test]
fn sparql_queries_returned_at_least_one_row_each() {
    assert!(
        !LIVE_SERVER_ROWS.is_empty(),
        "the `server_rows` SPARQL query against ontology.ttl returned zero \
         rmcp:HandlerMethod(role=server) rows -- either the ontology lost every \
         individual or the query itself is broken"
    );
    assert!(
        !LIVE_CLIENT_ROWS.is_empty(),
        "the `client_rows` SPARQL query against ontology.ttl returned zero \
         rmcp:HandlerMethod(role=client) rows -- either the ontology lost every \
         individual or the query itself is broken"
    );
}

/// Row-count parity between what the live ontology says right now (43 total: 27
/// server + 16 client, per ontology.ttl's own header) and what the query actually
/// returned this sync run.
#[test]
fn live_row_counts_match_the_ontologys_own_43_total() {
    assert_eq!(
        LIVE_SERVER_ROWS.len(),
        27,
        "live ontology query returned {} rmcp:HandlerMethod(role=server) rows, expected 27",
        LIVE_SERVER_ROWS.len()
    );
    assert_eq!(
        LIVE_CLIENT_ROWS.len(),
        16,
        "live ontology query returned {} rmcp:HandlerMethod(role=client) rows, expected 16",
        LIVE_CLIENT_ROWS.len()
    );
}

/// Every one of the 27 live `rmcp:HandlerMethod(role=server)` rows is present,
/// verbatim, in the checked-in `src/rmcp_handler_catalog.rs` -- the core
/// drift-detection assertion, run once per row rather than spot-checked.
#[test]
fn every_live_server_row_is_present_in_generated_source() {
    for row in LIVE_SERVER_ROWS {
        assert_row_present("server", row);
    }
}

/// Every one of the 16 live `rmcp:HandlerMethod(role=client)` rows is present,
/// verbatim, in the checked-in `src/rmcp_handler_catalog.rs`.
#[test]
fn every_live_client_row_is_present_in_generated_source() {
    for row in LIVE_CLIENT_ROWS {
        assert_row_present("client", row);
    }
}
