//! Auto-generated commands reference and noun-default compatibility law.
//! DO NOT EDIT — generated by root ggen.toml rule `cli-commands-reference`
//! from imported CLI ontologies. Edit RDF law, then `ggen sync run`.

/// (command IRI, label, description) rows, ontology-ordered by label.
pub const COMMANDS_REFERENCE: &[(&str, &str, &str)] = &[
    ("http://ggen.org/cli#DeployCommand", "deploy", "Deploy infrastructure to target environment"),
    ("http://ggen.org/cli#DescribeCommand", "describe", "Describe a resource (service, datastore, etc.) in detail"),
    ("http://ggen.org/cli#DoctorCommand", "doctor", "Run fast local health checks over the project (manifest, ontology, generated outputs)"),
    ("http://ggen.org/cli#ExplainCommand", "explain", "Explain RDF concepts, properties, and relationships"),
    ("http://ggen.org/cli#GenerateCommand", "generate", "Generate infrastructure artifacts from RDF specifications"),
    ("http://ggen.org/cli#LogsCommand", "logs", "Stream logs from services"),
    ("http://ggen.org/cli#ReceiptCommand", "receipt", "Verify the BLAKE3 chain hash and signature of the current sync receipt (.ggen-v2/receipt.json)"),
    ("http://ggen.org/cli#StatusCommand", "status", "Show current status of services and infrastructure"),
    ("http://ggen.org/cli#SyncCommand", "sync", "Synchronize specifications with RDF store and infrastructure"),
    ("http://ggen.org/cli#ValidateCommand", "validate", "Validate specifications and generated artifacts"),
];

/// Ontology-ordered `(noun, default verb)` compatibility bindings.
pub const DEFAULT_VERBS: &[(&str, &str)] = &[
    ("sync", "run"),
    ("doctor", "check"),
    ("receipt", "verify"),
];

/// Look up the ontology-declared description for a CLI command by its label.
///
/// Returns `None` when the label is not declared as a `cli:Command`
/// individual in `.specify/cli-commands.ttl`.
pub fn describe_command(label: &str) -> Option<&'static str> {
    COMMANDS_REFERENCE
        .iter()
        .find(|(_, l, _)| *l == label)
        .map(|(_, _, comment)| *comment)
}

/// Return the ontology-declared compatibility default for one noun.
pub fn default_verb(noun: &str) -> Option<&'static str> {
    DEFAULT_VERBS
        .iter()
        .find(|(candidate, _)| *candidate == noun)
        .map(|(_, verb)| *verb)
}

/// Insert a default verb only when argv does not contain an explicit verb.
///
/// Flags following the noun remain flags for the inserted default verb, while
/// noun-level `--help`/`-h` is never rewritten.
pub fn inject_default_verbs(mut args: Vec<String>) -> Vec<String> {
    let noun = args.get(1).map(String::as_str).unwrap_or_default();
    let next = args.get(2).map(String::as_str);
    let is_help_flag = matches!(next, Some("--help" | "-h"));
    let has_verb = next.is_some_and(|value| !value.starts_with('-'));
    if !has_verb && !is_help_flag {
        if let Some(verb) = default_verb(noun) {
            args.insert(2, verb.to_string());
        }
    }
    args
}

#[cfg(test)]
mod default_verb_tests {
    use super::{inject_default_verbs, DEFAULT_VERBS};

    fn strings(values: &[&str]) -> Vec<String> {
        values.iter().map(|value| (*value).to_string()).collect()
    }

    #[test]
    fn every_binding_injects_exactly_one_declared_verb() {
        for (noun, verb) in DEFAULT_VERBS {
            assert_eq!(
                inject_default_verbs(strings(&["ggen", noun])),
                strings(&["ggen", noun, verb])
            );
        }
    }

    #[test]
    fn explicit_verbs_and_noun_help_are_preserved() {
        for (noun, verb) in DEFAULT_VERBS {
            let explicit = strings(&["ggen", noun, verb]);
            assert_eq!(inject_default_verbs(explicit.clone()), explicit);
            for help in ["--help", "-h"] {
                let argv = strings(&["ggen", noun, help]);
                assert_eq!(inject_default_verbs(argv.clone()), argv);
            }
        }
    }

    #[test]
    fn noun_flags_follow_the_inserted_default_verb() {
        assert_eq!(
            inject_default_verbs(strings(&["ggen", "sync", "--dry-run"])),
            strings(&["ggen", "sync", "run", "--dry-run"])
        );
    }

    #[test]
    fn graph_and_unknown_nouns_are_not_rewritten() {
        for noun in ["graph", "unknown"] {
            let argv = strings(&["ggen", noun]);
            assert_eq!(inject_default_verbs(argv.clone()), argv);
        }
    }
}
