package com.example.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Generated Data Transfer Object: YTaskDTO
 * Used for REST API communication and JSON serialization.
 *
 * Generated by ggen Rule 5: DTOs
 * Source: YAWL ontology
 */
public class YTaskDTO {

    @JsonProperty("task_id")
    private String taskId;

    @JsonProperty("task_name")
    private String taskName;

    @JsonProperty("net_id")
    private String netId;

    @JsonProperty("task_type")
    private String taskType;

    @JsonProperty("is_enabled")
    private Boolean isEnabled;

    @JsonProperty("configuration_xml")
    private String configurationXml;

    // Constructors
    public YTaskDTO() {
    }

    public YTaskDTO(String taskId, String taskName, String netId, String taskType) {
        this.taskId = taskId;
        this.taskName = taskName;
        this.netId = netId;
        this.taskType = taskType;
        this.isEnabled = true;
    }

    // Getters and Setters
    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getNetId() {
        return netId;
    }

    public void setNetId(String netId) {
        this.netId = netId;
    }

    public String getTaskType() {
        return taskType;
    }

    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    public Boolean getIsEnabled() {
        return isEnabled;
    }

    public void setIsEnabled(Boolean enabled) {
        isEnabled = enabled;
    }

    public String getConfigurationXml() {
        return configurationXml;
    }

    public void setConfigurationXml(String configurationXml) {
        this.configurationXml = configurationXml;
    }

    @Override
    public String toString() {
        return "YTaskDTO{" +
                "taskId='" + taskId + '\'' +
                ", taskName='" + taskName + '\'' +
                ", netId='" + netId + '\'' +
                ", taskType='" + taskType + '\'' +
                ", isEnabled=" + isEnabled +
                '}';
    }
}
