//! Generated Commands - DO NOT EDIT
//!
//! This file is automatically generated by ggen from ontology/commands.ttl
//! To make changes, edit the ontology and run: ggen sync

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Mark subscription as canceled
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CancelSubscription {
    pub cancel_date:DateTime,/// Mark subscription as canceled
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CancelSubscription {
    pub subscription_id:Uuid,/// Compute attribution for clicks
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ComputeAttribution {
    pub click_id:Uuid,/// Calculate payout for publisher
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProcessPayout {
    pub period_end:DateTime,/// Calculate payout for publisher
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProcessPayout {
    pub period_start:DateTime,/// Calculate payout for publisher
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProcessPayout {
    pub publisher_id:Uuid,/// Record a click event
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordClick {
    pub ip_hash:Option<String>,/// Record a click event
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordClick {
    pub offer_id:Uuid,/// Record a click event
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordClick {
    pub publisher_id:Uuid,/// Record a click event
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordClick {
    pub user_agent:Option<String>,/// Record monthly commission for active subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordRecurringCommission {
    /// Billing period end
    pub period_end:DateTime,/// Record monthly commission for active subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordRecurringCommission {
    /// Billing period start
    pub period_start:DateTime,/// Record monthly commission for active subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RecordRecurringCommission {
    /// Active subscription ID
    pub subscription_id:Uuid,/// Look up route by slug
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ResolveRoute {
    /// Route slug from URL
    pub slug:String,/// Record click and generate receipt
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackClick {
    pub referrer:Option<String>,/// Record click and generate receipt
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackClick {
    pub route_id:Uuid,/// Record click and generate receipt
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackClick {
    pub user_agent:Option<String>,/// Record click and generate receipt
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackClick {
    /// Will be hashed before storage
    pub visitor_ip:String,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    pub currency:Option<String>,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    /// External customer ID
    pub customer_id:String,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    /// Monthly recurring revenue
    pub mrr_amount:Decimal,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    /// Subscription plan
    pub plan:String,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    /// SaaS program ID
    pub program_id:Uuid,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    /// Publisher who referred subscription
    pub publisher_id:Uuid,/// Track new or updated SaaS subscription
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TrackSubscription {
    pub start_date:DateTime,
}
